- platform: rest
  resource: !env_var DESK_HID_IDLE_TIME_RESOURCE
  name: Jesse's desktop
  value_template: '{{ value_json < 60}}'
- platform: template
  sensors:
    living_room_motion:
      entity_id: sensor.alarm_sensors
      value_template: |
        {{ "No motion activity detected." not in (states.sensor.alarm_sensors.state | default("")) }}
    entry_door:
      entity_id: sensor.alarm_sensors
      value_template: |
        {{ "Entry" in (states.sensor.alarm_sensors.state | default("")) }}
    master_door:
      entity_id: sensor.alarm_sensors
      value_template: |
        {{ "Master" in (states.sensor.alarm_sensors.state | default("")) }}
    garage:
      entity_id: cover.garage
      value_template: |
        {{ states("cover.garage") | default("") == "open" }}
    gate:
      entity_id: cover.gate
      value_template: |
        {{ states("cover.gate") | default("") == "open" }}
    rain_today:
      entity_id:
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      value_template: |
        {{
          states.sensor.dark_sky_precip_probability.state != None and
          states.sensor.dark_sky_precip_intensity.state != None and
          (
            float(states.sensor.dark_sky_precip_probability.state) > 0 or
            float(states.sensor.dark_sky_precip_intensity.state) > 0
          )
        }}
    together:
      entity_id:
      - device_tracker.jphone_6s
      - device_tracker.katies_iphone
      value_template: |
        {{
          states.device_tracker.katies_iphone != None and
          states.device_tracker.jphone_6s != None and
          distance(states.device_tracker.jphone_6s, states.device_tracker.katies_iphone) != None and
          distance(states.device_tracker.jphone_6s, states.device_tracker.katies_iphone) < 0.25
        }}
    front_door_battery_low:
      entity_id: lock.front_door_12
      value_template: |
        {{ states.lock.front_door_12.attributes.battery_level | int < 50 }}
