- platform: rest
  resource: !env_var DESK_HID_IDLE_TIME_RESOURCE
  name: Desk active
  value_template: '{{ value_json < 60}}'
- platform: template
  sensors:
    front_gate:
      entity_id: binary_sensor.front_gate_81
      value_template: '{% if is_state("binary_sensor.front_gate_81", "on") %}closed{% else %}open{% endif %}'
      friendly_name: 'Front gate'
    rain_today:
      entity_id:
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_intensity
      value_template: |
        {{
          float(states.sensor.dark_sky_daily_max_precip_intensity.state) > 0 or
          float(states.sensor.dark_sky_precip_probability.state) > 0 or
          float(states.sensor.dark_sky_precip_intensity.state) > 0
        }}
    together:
      entity_id:
      - device_tracker.jphone_jphone
      - device_tracker.kphone_kphone
      value_template: |
        {{
          distance(states.device_tracker.jphone_jphone, states.device_tracker.kphone_kphone) != None and
          distance(states.device_tracker.jphone_jphone, states.device_tracker.kphone_kphone) < 0.25
        }}
