- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_1
  name: gate
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_2
  name: back porch
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_3
  name: front yard left
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_4
  name: atrium
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_5
  name: garage
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_6
  name: ac
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_7
  name: front yard right
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_8
  name: side yard
- platform: ffmpeg
  name: capitol
  input: https://wms-prod-1.wetmet.net/live/192-07-01/playlist.m3u8

- platform: local_file
  file_path: /tmp/doods_atrium.jpg
  name: doods_atrium
- platform: local_file
  file_path: /tmp/doods_back_porch.jpg
  name: doods_back_porch
# - platform: local_file
#   file_path: /tmp/doods_front_yard_left.jpg
#   name: doods_front_yard_left
- platform: local_file
  file_path: /tmp/doods_garage.jpg
  name: doods_garage
# - platform: local_file
#   file_path: /tmp/doods_gate.jpg
#   name: doods_gate
