- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_1
  name: gate
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_2
  name: back porch
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_3
  name: front yard left
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_4
  name: atrium
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_5
  name: garage
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_6
  name: ac
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_7
  name: front yard right
- platform: mjpeg
  mjpeg_url: !env_var CAMERA_URL_8
  name: side yard
