homeassistant:
  name: Home
  latitude: !env_var LAT
  longitude: !env_var LONG
  elevation: !env_var ELEVATION
  unit_system: imperial
  time_zone: America/Chicago
  country: US
  currency: USD
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages
  auth_providers: !include auth_providers.yaml
  external_url: !env_var SELF_LINK
  allowlist_external_dirs:
    - /tmp
  allowlist_external_urls:
    - !env_var SELF_LINK
    - !env_var FRIGATE_URL

adaptive_lighting: !include_dir_list adaptive_lighting
default_config:
binary_sensor: !include_dir_list binary_sensors
circadian_lighting:
  min_colortemp: 2500
  max_colortemp: 3500

conversation:
emulated_hue:
  expose_by_default: false
frontend: !include frontend.yaml
group: !include_dir_named groups
history:
http: !include http.yaml
homekit: !include homekit.yaml
ifttt: !include ifttt.yaml
input_boolean: !include input_boolean.yaml
light:
light yaml: !include_dir_list lights
lovelace: !include lovelace.yaml
logger: !include logger.yaml
media_player: !include media_player.yaml
python_script:
recorder: !include recorder.yaml
scene: !include_dir_list scenes
script: !include_dir_named scripts
sensor: !include_dir_list sensors
sun:
stream:
  ll_hls: true
switch: !include_dir_list switches
system_health:
system_log:
  fire_event: true
tts:
  - platform: google_translate
zone: !include zone.yaml

automation ui: !include automations.yaml
