- platform: unifi
  host: !env_var UNIFI_IP
  port: !env_var UNIFI_PORT
  verify_ssl: false
  username: !env_var UNIFI_USERNAME
  password: !env_var UNIFI_PASSWORD
  track_new_devices: false
  consider_home: 15
- platform: ping
  consider_home: 15
  hosts:
    jesse_music_room: !env_var JESSE_MUSIC_ROOM_IP
