- platform: doods
  scan_interval: 10
  timeout: 60
  url: "http://doods.home-assistant.svc.kubernetes.home.jnewland.com:8080"
  detector: default
  source:
    - entity_id: camera.atrium
      name: atrium
  file_out:
    - "/tmp/doods_{{ camera_entity.split('.')[1] }}.jpg"
  area:
    # Exclude left part of image
    left: 0.25
  labels:
    - name: dog
      confidence: 30
    - name: person
      confidence: 60

- platform: doods
  scan_interval: 10
  timeout: 60
  url: "http://doods.home-assistant.svc.kubernetes.home.jnewland.com:8080"
  detector: default
  source:
    - entity_id: camera.back_porch
      name: back porch
  file_out:
    - "/tmp/doods_{{ camera_entity.split('.')[1] }}.jpg"
  area:
    # Exclude right half of image
    right: 0.5
  labels:
    - name: dog
      confidence: 30
    - name: person
      confidence: 60


# The bottom two thirds of the front yard camera
- platform: doods
  scan_interval: 10
  timeout: 60
  url: "http://doods.home-assistant.svc.kubernetes.home.jnewland.com:8080"
  detector: default
  source:
    - entity_id: camera.front_yard_left
      name: front yard left
  file_out:
    - "/tmp/doods_{{ camera_entity.split('.')[1] }}.jpg"
  area:
    # Exclude street
    top: 0.25
    left: 0.25
  labels:
    - name: dog
      confidence: 30
    - name: person
      confidence: 60
