# Detect on all parts of these cameras
- platform: doods
  scan_interval: 10
  timeout: 60
  url: "http://doods.home-assistant.svc.kubernetes.home.jnewland.com:8080"
  detector: default
  source:
    - entity_id: camera.atrium
      name: atrium
    - entity_id: camera.back_porch
      name: back_porch
  file_out:
    - "/tmp/doods_{{ camera_entity.split('.')[1] }}.jpg"
  confidence: 50
  labels:
    - dog
    - person

# The bottom two thirds of the front yard camera
- platform: doods
  scan_interval: 10
  timeout: 60
  url: "http://doods.home-assistant.svc.kubernetes.home.jnewland.com:8080"
  detector: default
  source:
    - entity_id: camera.front_yard_left
      name: front yard left
  file_out:
    - "/tmp/doods_{{ camera_entity.split('.')[1] }}.jpg"
  confidence: 50
  area:
    # Exclude top third of image
    top: 0.33
    covers: true
  labels:
    - dog
    - person
