- platform: channels
  name: music room channels
  host: music-room-channels
- platform: channels
  name: lounge channels
  host: lounge-channels
- platform: channels
  name: bedroom channels
  host: bedroom-channels
- platform: channels
  name: garage channels
  host: garage-channels
