- platform: channels
  name: music room channels
  host: music-room
- platform: channels
  name: lounge channels
  host: lounge
- platform: channels
  name: bedroom channels
  host: bedroom
- platform: channels
  name: garage channels
  host: garage-tv
