# Powered sub is attached to this zone's preamp out
- platform: mpr_6zhmaut
  name: living speakers
  host: !env_var MPR_API_IP
  port: !env_var MPR_API_PORT
  zone: 11
- platform: mpr_6zhmaut
  name: kitchen speakers
  host: !env_var MPR_API_IP
  port: !env_var MPR_API_PORT
  zone: 12
- platform: mpr_6zhmaut
  name: patio speakers
  host: !env_var MPR_API_IP
  port: !env_var MPR_API_PORT
  zone: 13
- platform: mpr_6zhmaut
  name: atrium speakers
  host: !env_var MPR_API_IP
  port: !env_var MPR_API_PORT
  zone: 14
- platform: mpr_6zhmaut
  name: master bedroom speakers
  host: !env_var MPR_API_IP
  port: !env_var MPR_API_PORT
  zone: 15
- platform: mpr_6zhmaut
  name: master bathroom speakers
  host: !env_var MPR_API_IP
  port: !env_var MPR_API_PORT
  zone: 16
- platform: samsungtv
  host: !env_var OFFICE_TV_IP
  mac: !env_var OFFICE_TV_MAC
  name: Office TV
- platform: itunes
  host: !env_var ITUNES_IP
- platform: airfoil
  host: !env_var ITUNES_IP
