- platform: slack
  name: slack
  api_key: !env_var SLACK_API_KEY
  default_channel: "#general"
- platform: group
  name: iphones
  services:
  - service: mobile_app_jphone_12
  - service: mobile_app_katie_s_iphone
