- platform: thinkingcleaner
- platform: darksky
  api_key: !env_var FORECAST_API_KEY
  monitored_conditions:
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
#      - type: swap_use_percent
#      - type: network_in
#        arg: eth0
#      - type: network_out
#        arg: eth0

- platform: rest
  resource: https://iaspub.epa.gov/enviro/efservice/getEnvirofactsUVDAILY/ZIP/78722/JSON
  name: Today's uv index
  value_template: |
    {%- for day in value_json -%}
      {{ day.UV_INDEX }}
    {%- endfor -%}

- platform: rest
  resource: https://iaspub.epa.gov/enviro/efservice/getEnvirofactsUVHOURLY/ZIP/78722/JSON
  name: Today's low uv hours
  value_template: |
    {%- for hour in value_json -%}
    {%- if hour.UV_VALUE < 3 and hour.UV_VALUE > 0 -%}
    {%- set date = hour.DATE_TIME.split(' ') -%}
    {{ date[1] | round }}{{ date[2] | lower }} {% endif -%}
    {%- endfor -%}

- platform: template
  sensors:
    front_gate:
      entity_id: binary_sensor.front_gate_81
      value_template: '{% if is_state("binary_sensor.front_gate_81", "on") %}open{% else %}closed{% endif %}'
      friendly_name: Front gate
    sunrise:
      entity_id: sun.sun
      value_template: |
        {% if states.sun.sun %}
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_local }}
        {% endif %}
    sunset:
      entity_id: sun.sun
      value_template: |
        {% if states.sun.sun %}
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_local }}
        {% endif %}
    great_room_temperature:
      entity_id: climate.great_room
      unit_of_measurement: '°F'
      value_template: |
        {% if states.climate.great_room %}
          {{ states.climate.great_room.attributes.current_temperature }}
        {% endif %}
    hall_temperature:
      entity_id: climate.hall
      unit_of_measurement: '°F'
      value_template: |
        {% if states.climate.hall %}
          {{ states.climate.hall.attributes.current_temperature }}
        {% endif %}
    upstairs_temperature:
      entity_id: climate.upstairs
      unit_of_measurement: '°F'
      value_template: |
        {% if states.climate.upstairs %}
          {{ states.climate.upstairs.attributes.current_temperature }}
        {% endif %}
    # battery_level
    lock_front_door_battery_level:
      entity_id: lock.front_door
      unit_of_measurement: '%'
      value_template: |
        {% if states.lock.front_door %}
          {{ states.lock.front_door.attributes.battery_level | replace('%', '') }}
        {% endif %}
    switch_master_ac_water_battery_level:
      entity_id: switch.master_ac_water
      unit_of_measurement: '%'
      value_template: |
        {% if states.switch.master_ac_water %}
          {{ states.switch.master_ac_water.attributes.battery_level | replace('%', '') }}
        {% endif %}
    switch_master_bath_motion_battery_level:
      entity_id: switch.master_bath_motion
      unit_of_measurement: '%'
      value_template: |
        {% if states.switch.master_bath_motion %}
          {{ states.switch.master_bath_motion.attributes.battery_level | replace('%', '') }}
        {% endif %}
    switch_stairs_motion_battery_level:
      entity_id: switch.stairs_motion
      unit_of_measurement: '%'
      value_template: |
        {% if states.switch.stairs_motion %}
          {{ states.switch.stairs_motion.attributes.battery_level | replace('%', '') }}
        {% endif %}

- platform: command_line
  name: haconfig_branch
  command: "tail -n 1 /config/.git/logs/HEAD | rev | cut -f 1 -d \\/ | rev"
- platform: command_line
  name: homeassistant_branch
  command: "tail -n 1 /usr/src/app/.git/logs/HEAD | rev | cut -f 1 -d \\/ | rev"
- platform: command_line
  name: haconfig_sha
  command: "tail -n 1 /config/.git/logs/HEAD | awk '{print $2'}"
- platform: command_line
  name: homeassistant_sha
  command: "tail -n 1 /usr/src/app/.git/logs/HEAD | awk '{print $2'}"
