name: Rancho de Newland
views:
  - title: Home
    icon: mdi:home
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            image: http://wwc.instacam.com/instacamimg/UTAUS/UTAUS_l.jpg
            entities:
              - input_select.mode
              - alarm_control_panel.alarm
              - lock.front_door
              - cover.garage
              - cover.gate
              - binary_sensor.front_gate
              - input_number.brightness
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.front_yard_left
            - type: picture-entity
              entity: camera.gate
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.side_yard
            - type: picture-entity
              entity: camera.atrium
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.garage
            - type: picture-entity
              entity: camera.back_porch
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: picture
            image: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=GRK&brand=wui&num=10&delay=25&type=N0R&frame=0&scale=1&noclutter=1&showstorms=99&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=1&smooth=1&rand=24691285&lat=0&lon=0&label=you
          - type: glance
            entities:
            - device_tracker.katie_s_iphone
            - device_tracker.jphone_11_pro
  - title: Cameras
    icon: mdi:video
    cards:
      - type: picture-entity
        entity: camera.gate
      - type: picture-entity
        entity: camera.front_yard_right
      - type: picture-entity
        entity: camera.front_yard_left
      - type: picture-entity
        entity: camera.atrium
      - type: picture-entity
        entity: camera.side_yard
      - type: picture-entity
        entity: camera.back_porch
      - type: picture-entity
        entity: camera.ac
      - type: picture-entity
        entity: camera.garage
  - title: Office
    icon: mdi:desktop-mac
    cards:
      - type: entities
        entities:
        - light.office_overhead
        - light.office_chandelier
  - title: Music Room
    icon: mdi:guitar-pick
    cards:
      - type: entities
        entities:
        - light.music_room
        - light.bookshelf
  - title: Lights
    icon: mdi:lightbulb
    cards:
    - type: custom:monster-card
      show_empty: false
      card:
        type: glance
        title: "On"
      filter:
        include:
          - domain: light
        exclude:
          - entity_id: "*sml*"
          - state: 'off'
          - state: 'unavailable'
    - type: custom:monster-card
      show_empty: false
      card:
        type: glance
        title: "Off"
      filter:
        include:
          - domain: light
        exclude:
          - state: 'on'
  - title: Batteries
    icon: mdi:battery
    cards:
    - type: sensor
      entity: sensor.jphone_11_pro_battery_level
    - type: sensor
      entity: sensor.katie_s_iphone_battery_level
    - type: custom:entity-attributes-card
      heading_name: Sensor
      heading_state: Battery level
      filter:
        name_attribute: friendly_name
        include:
          # ahh i wish this could be a wildcard or a monster card
          - switch.closet_motion.battery_level
          - switch.front_door.battery_level
          - switch.front_gate.battery_level
          - switch.garage_hall_motion.battery_level
          - switch.great_hall_motion.battery_level
          - switch.guest_bath_motion.battery_level
          - switch.kitchen_motion.battery_level
          - switch.master_ac_water.battery_level
          - switch.music_room_motion.battery_level
          - switch.office_motion.battery_level
          - switch.powder_room_motion.battery_level
          - switch.stairs_motion.battery_level
          - switch.upstairs_motion.battery_level
          - switch.wine_room_motion.battery_level
          # - vacuum.downstairs_roomba.battery_level
  - title: Speakers
    icon: mdi:speaker
    cards:
    - type: media-control
      entity: media_player.atrium_speakers
    - type: media-control
      entity: media_player.kitchen_speakers
    - type: media-control
      entity: media_player.living_speakers
    - type: media-control
      entity: media_player.master_bathroom_speakers
    - type: media-control
      entity: media_player.master_bedroom_speakers
    - type: media-control
      entity: media_player.patio_speakers
  - title: Upstairs
    icon: mdi:hotel
    cards:
    - type: entities
      entities:
      - light.chandelier
      - light.chandelier_lamp
      - light.master_overhead
      - light.master_closet
      - light.master_nook
      - light.master_windows
      - light.bedside_lamp
      - light.master_patio
    - type: entities
      entities:
      - light.master_bath_overhead
      - light.master_shower
      - light.master_mirror
      - light.master_toilet
      - switch.master_bath_fan
  - title: Great Room
    icon: mdi:sofa
    cards:
    - type: entities
      entities:
      - light.cabinets
      - light.dining_room_table
      - light.kitchen
      - light.living
      - light.pendants
      - light.couch_lamp_right
      - light.couch_lamp_left
      - switch.christmas_tree
  - title: Outdoor
    icon: mdi:tree
    cards:
    - type: entities
      entities:
      - switch.bug_zapper
      - light.atrium
      - switch.back_porch
      - light.front_porch
      - light.front_door
      - light.patio
      - light.master_patio
      - light.ac
      - light.atrium_door
      - light.garage_door
    - type: entities
      entities:
      - binary_sensor.front_gate
      - cover.garage
      - cover.gate
  - title: Environment
    icon: mdi:temperature-fahrenheit
    cards:
    - type: entities
      entities:
      - climate.great_room
      - climate.upstairs
      - climate.office
  - title: Settings
    icon: mdi:settings
    cards:
    - type: entities
      entities:
      - input_boolean.guests
      - automation.away_mode
    - type: entities
      entities:
      - sensor.config_sha
      - sensor.latest_deployment_sha
      - script.deploy

resources:
- url: /local/monster-card.js?v=1
  type: js
- url: /local/entity-attributes-card.js?v=3
  type: js
