name: Rancho de Newland
views:
  - title: Home
    icon: mdi:home
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            image: http://wwc.instacam.com/instacamimg/UTAUS/UTAUS_l.jpg
            entities:
              - input_select.mode
              - alarm_control_panel.alarm
              - lock.front_door_12
              - cover.garage
              - cover.gate
              - input_number.brightness
          - type: weather-forecast
            entity: weather.dark_sky
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - media_player.atrium_speakers
              - media_player.kitchen_speakers
              - media_player.living_speakers
          - type: picture-entity
            entity: camera.front_yard_left
  - title: Cameras
    icon: mdi:video
    cards:
      - type: picture-entity
        entity: camera.gate
      - type: picture-entity
        entity: camera.front_yard_right
      - type: picture-entity
        entity: camera.front_yard_left
      - type: picture-entity
        entity: camera.atrium
      - type: picture-entity
        entity: camera.side_yard
      - type: picture-entity
        entity: camera.back_porch
      - type: picture-entity
        entity: camera.ac
      - type: picture-entity
        entity: camera.garage
  - title: Office
    icon: mdi:desktop-mac
    cards:
      - type: entities
        entities:
        - light.office_desk_lamp
        - light.office_overhead_11
        - light.office_chandelier_69
        - light.floor_lamp
  - title: Music Room
    icon: mdi:guitar-pick
    cards:
      - type: entities
        entities:
        - light.music_room_118
        - light.desk_63
  - title: Speakers
    icon: mdi:speaker
    cards:
    - type: entities
      entities:
      - media_player.atrium_speakers
      - media_player.kitchen_speakers
      - media_player.living_speakers
      - media_player.master_bathroom_speakers
      - media_player.master_bedroom_speakers
      - media_player.patio_speakers
      
