name: Rancho de Newland
views:
  - name: Home
    view_icon: mdi:home
    theme: dark-mode
    cards:
      - type: picture-glance
        image: http://wwc.instacam.com/instacamimg/UTAUS/UTAUS_l.jpg
        entities:
          - input_select.mode
          - alarm_control_panel.alarm
          - lock.front_door_12
          - cover.garage
          - cover.gate
          - input_number.brightness

      - type: camera-preview
        entity: camera.front_yard_left

      - type: entities
        entities:
          - sensor.christmas

      - type: weather-forecast
        entity: weather.dark_sky

      - type: media-control
        entity: media_player.house

      - type: glance
        entities:
          - media_player.atrium_speakers
          - media_player.kitchen_speakers
          - media_player.living_speakers
          - media_player.house_mpr6zhmaut
          - media_player.house_back_porch

      - type: entities
        entities:
          - light.cabinets_14
          - light.dining_room_table_52
          - light.kitchen_18
          - light.living_20
          - light.pendants_51
          - light.living_room_lamp_right
          - light.living_room_lamp_left

#   - tab_icon: mdi:home-assistant
#     name: Custom card
#     cards:
#       - type: "custom:big-state-card"
#         title: ''
#         entities:
#           - sensor.christmas
# resources:
#   - url: /local/big-state-card.js
#     type: module
