name: Rancho de Newland
views:
  - title: Home
    icon: mdi:home
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            image: http://wwc.instacam.com/instacamimg/UTAUS/UTAUS_l.jpg
            entities:
              - input_select.mode
              - alarm_control_panel.alarm
              - lock.front_door_12
              - cover.garage
              - cover.gate
              - input_number.brightness
          - type: weather-forecast
            entity: weather.dark_sky
      - type: vertical-stack
        cards:
          - type: glance
            entities:
            - device_tracker.katies_iphone
            - device_tracker.jphone_x
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.front_yard_left
            - type: picture-entity
              entity: camera.front_yard_right
  - title: Cameras
    icon: mdi:video
    cards:
      - type: picture-entity
        entity: camera.gate
      - type: picture-entity
        entity: camera.front_yard_right
      - type: picture-entity
        entity: camera.front_yard_left
      - type: picture-entity
        entity: camera.atrium
      - type: picture-entity
        entity: camera.side_yard
      - type: picture-entity
        entity: camera.back_porch
      - type: picture-entity
        entity: camera.ac
      - type: picture-entity
        entity: camera.garage
  - title: Office
    icon: mdi:desktop-mac
    cards:
      - type: entities
        entities:
        - light.office_desk_lamp
        - light.office_overhead_11
        - light.office_chandelier_69
        - light.floor_lamp
  - title: Music Room
    icon: mdi:guitar-pick
    cards:
      - type: entities
        entities:
        - light.music_room_118
        - light.desk_63
  - title: Speakers
    icon: mdi:speaker
    cards:
    - type: media-control
      entity: media_player.atrium_speakers
    - type: media-control
      entity: media_player.kitchen_speakers
    - type: media-control
      entity: media_player.living_speakers
    - type: media-control
      entity: media_player.master_bathroom_speakers
    - type: media-control
      entity: media_player.master_bedroom_speakers
    - type: media-control
      entity: media_player.patio_speakers
  - title: Upstairs
    icon: mdi:hotel
    cards:
    - type: entities
      entities:
      - light.chandelier_154
      - light.chandelier_lamp_33
      - light.master_overhead_30
      - light.master_closet_32
      - light.master_nook_42
      - light.master_windows_128
      - light.bedside_lamp_141
      - light.master_patio_31
    - type: entities
      entities:
      - light.master_bath_overhead_36
      - light.master_shower_34
      - light.master_mirror_35
      - light.master_toilet_62
      - switch.master_bath_fan_129
  - title: Great Room
    icon: mdi:sofa
    cards:
    - type: entities
      entities:
      - light.cabinets_14
      - light.dining_room_table_52
      - light.kitchen_18
      - light.living_20
      - light.pendants_51
      - light.living_room_lamp_right
      - light.living_room_lamp_left
  - title: Outdoor
    icon: mdi:tree
    cards:
    - type: entities
      entities:
      - switch.fountain_26
      - light.atrium_22
      - light.back_porch_46
      - light.front_porch_19
      - light.front_door_21
      - light.patio_29
      - light.master_patio_31
      - light.ac_125
      - light.atrium_door_123
      - light.garage_door_124
  - title: Environment
    icon: mdi:temperature-fahrenheit
    cards:
    - type: entities
      entities:
      - climate.great_room_27
      - climate.upstairs_28
      - climate.hall_48
  - title: Settings
    icon: mdi:settings
    cards:
    - type: entities
      entities:
      - input_boolean.guests
      - automation.away_mode

resources:
  - url: /local/monster-card.js?v=1
    type: js