name: Rancho de Newland
views:
  - title: Home
    icon: mdi:home
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            image: http://wwc.instacam.com/instacamimg/UTAUS/UTAUS_l.jpg
            entities:
              - input_select.mode
              - alarm_control_panel.alarm
              - lock.front_door
              - cover.garage
              - cover.gate
              - binary_sensor.front_gate
              - input_number.brightness
              - vacuum.downstairs_roomba
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.front_yard_left
            - type: picture-entity
              entity: camera.gate
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.pergola
            - type: picture-entity
              entity: camera.atrium
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.garage
            - type: picture-entity
              entity: camera.back_porch
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: picture-entity
            entity: camera.capitol
          - type: picture
            image: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=GRK&brand=wui&num=10&delay=25&type=N0R&frame=0&scale=1&noclutter=1&showstorms=99&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=1&smooth=1&rand=24691285&lat=0&lon=0&label=you
          - type: glance
            entities:
            - device_tracker.katie_s_iphone
            - device_tracker.jphone_11_pro
  - title: Cameras
    icon: mdi:video
    cards:
      - type: picture-entity
        entity: camera.gate
      - type: picture-entity
        entity: camera.front_yard_right
      - type: picture-entity
        entity: camera.front_yard_left
      - type: picture-entity
        entity: camera.atrium
      - type: picture-entity
        entity: camera.pergola
      - type: picture-entity
        entity: camera.back_porch
      - type: picture-entity
        entity: camera.ac
      - type: picture-entity
        entity: camera.garage
      - type: picture-entity
        entity: camera.doods_atrium
      - type: picture-entity
        entity: camera.doods_back_porch
      - type: picture-entity
        entity: camera.doods_front_yard_left
  - title: Office
    icon: mdi:desktop-mac
    cards:
      - type: entities
        entities:
        - light.office_overhead
        - light.office_chandelier
        - light.exercise_bike
        - binary_sensor.office_motion
  - title: Music Room
    icon: mdi:guitar-pick
    cards:
      - type: entities
        entities:
        - light.music_room
        - light.bookshelf
        - binary_sensor.music_room_motion
  - title: Lights
    icon: mdi:lightbulb
    cards:
    - type: custom:auto-entities
      show_empty: false
      sort:
        method: name
      card:
        type: entities
        title: Lights on
      filter:
        include:
          - domain: light
        exclude:
          - entity_id: '/_[0-9]+$/'
          - state: "off"
          - state: "unavailable"
    - type: custom:auto-entities
      sort:
        method: name
      show_empty: false
      card:
        type: entities
        title: Lights off
      filter:
        include:
          - domain: light
            state: "off"
            options:
              tap_action:
                action: toggle
        exclude:
          - entity_id: '/_[0-9]+$/'
  - title: Batteries
    icon: mdi:battery
    cards:
    - type: sensor
      entity: sensor.jphone_11_pro_battery_level
    - type: sensor
      entity: sensor.katie_s_iphone_battery_level
    - type: custom:entity-attributes-card
      heading_name: Sensor
      heading_state: Battery level
      filter:
        name_attribute: friendly_name
        include:
          # ahh i wish this could be a wildcard or a monster card
          - switch.closet_motion.battery_level
          - switch.front_door.battery_level
          - switch.front_gate.battery_level
          - switch.garage_hall_motion.battery_level
          - switch.great_hall_motion.battery_level
          - switch.guest_bath_motion.battery_level
          - switch.kitchen_motion.battery_level
          - switch.master_ac_water.battery_level
          - switch.music_room_motion.battery_level
          - switch.office_motion.battery_level
          - switch.powder_room_motion.battery_level
          - switch.stairs_motion.battery_level
          - switch.upstairs_motion.battery_level
          - switch.wine_room_motion.battery_level
          - vacuum.downstairs_roomba.battery_level
  - title: Speakers
    icon: mdi:speaker
    cards:
    - type: media-control
      entity: media_player.atrium_speakers
    - type: media-control
      entity: media_player.kitchen_speakers
    - type: media-control
      entity: media_player.living_speakers
    - type: media-control
      entity: media_player.master_bathroom_speakers
    - type: media-control
      entity: media_player.master_bedroom_speakers
    - type: media-control
      entity: media_player.patio_speakers
  - title: Upstairs
    icon: mdi:hotel
    cards:
    - type: entities
      entities:
      - light.chandelier
      - light.chandelier_lamp
      - light.master_overhead
      - light.master_closet
      - light.master_nook
      - light.master_windows
      - light.bedside_lamp
      - light.master_patio
      - binary_sensor.closet_motion
    - type: entities
      entities:
      - light.master_bath_overhead
      - light.master_shower
      - light.master_mirror
      - light.master_toilet
      - switch.master_bath_fan
      - binary_sensor.master_bath_motion
  - title: Great Room
    icon: mdi:sofa
    cards:
    - type: entities
      entities:
      - light.cabinets
      - light.dining_room_table
      - light.kitchen
      - light.living
      - light.pendants
      - light.couch_lamp_right
      - light.couch_lamp_left
      - switch.christmas_tree
      - binary_sensor.kitchen_motion
      - binary_sensor.living_room_motion
  - title: Outdoor
    icon: mdi:tree
    cards:
    - type: entities
      entities:
      - switch.bug_zapper
      - light.atrium
      - switch.back_porch
      - light.front_porch
      - light.front_door
      - light.patio
      - light.master_patio
      - light.ac
      - light.atrium_door
      - light.garage_door
    - type: entities
      entities:
      - binary_sensor.front_gate
      - cover.garage
      - cover.gate
  - title: Climate
    icon: mdi:temperature-fahrenheit
    cards:
    - type: thermostat
      entity: climate.great_room
    - type: thermostat
      entity: climate.office
    - type: thermostat
      entity: climate.upstairs

    - type: entities
      entities:
      - automation.downstairs_ac
      - automation.downstairs_heat
      - automation.upstairs_ac
      - automation.upstairs_heat
      - automation.upstairs_evening_ac
      - automation.upstairs_reading_fan
      - automation.upstairs_sleeping_fan_reset
      - automation.upstairs_morning_climate_reset

    - type: custom:auto-entities
      card:
        type: history-graph
        hours_to_show: 72
      filter:
        include:
          - entity_id: "/^sensor.*_temperature$/"

    - type: custom:auto-entities
      card:
        type: history-graph
        hours_to_show: 72
      filter:
        include:
          - entity_id: "/^sensor.*_temp$/"
        exclude:
          - entity_id: sensor.wine_room_temp

    - type: history-graph
      hours_to_show: 72
      entities:
        - sensor.wine_room_temp

    - type: custom:auto-entities
      card:
        type: history-graph
        hours_to_show: 72
      filter:
        include:
          - entity_id: "/^sensor.*_light$/"

  - title: Settings
    icon: mdi:settings
    cards:
    - type: entities
      entities:
      - input_boolean.guests
      - automation.away_mode
      - vacuum.downstairs_roomba
    - type: entities
      entities:
      - sensor.current_version
      - binary_sensor.updater
      - sensor.config_sha
      - sensor.latest_deployment_sha
      - script.deploy
    - type: custom:auto-entities
      show_empty: false
      sort:
        method: id
      card:
        type: glance
        title: Unconfigured devices
      filter:
        include:
          - entity_id: '/_[0-9]+$/'
        exclude:
          - entity_id: "*_sim_*"

resources:
- url: /local/monster-card.js?v=1
  type: js
- url: /local/entity-attributes-card.js?v=3
  type: js
- url: /local/auto-entities.js
  type: module