name: Rancho de Newland
views:
  - title: Home
    icon: mdi:home
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            image: http://wwc.instacam.com/instacamimg/UTAUS/UTAUS_l.jpg
            entities:
              - input_select.mode
              - alarm_control_panel.alarm
              - lock.front_door_12
              - cover.garage
              - cover.gate
              - binary_sensor.front_gate_121
              - input_number.brightness
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.front_yard_left
            - type: picture-entity
              entity: camera.gate
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.side_yard
            - type: picture-entity
              entity: camera.atrium
          - type: horizontal-stack
            cards:
            - type: picture-entity
              entity: camera.garage
            - type: picture-entity
              entity: camera.back_porch
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: picture
            image: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=GRK&brand=wui&num=10&delay=25&type=N0R&frame=0&scale=1&noclutter=1&showstorms=99&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=1&smooth=1&rand=24691285&lat=0&lon=0&label=you
          - type: glance
            entities:
            - device_tracker.katies_iphone
            - device_tracker.jphone_xs
  - title: Cameras
    icon: mdi:video
    cards:
      - type: picture-entity
        entity: camera.gate
      - type: picture-entity
        entity: camera.front_yard_right
      - type: picture-entity
        entity: camera.front_yard_left
      - type: picture-entity
        entity: camera.atrium
      - type: picture-entity
        entity: camera.side_yard
      - type: picture-entity
        entity: camera.back_porch
      - type: picture-entity
        entity: camera.ac
      - type: picture-entity
        entity: camera.garage
  - title: Office
    icon: mdi:desktop-mac
    cards:
      - type: entities
        entities:
        - light.office_desk_lamp
        - light.office_overhead_11
        - light.office_chandelier_69
        - light.floor_lamp
  - title: Music Room
    icon: mdi:guitar-pick
    cards:
      - type: entities
        entities:
        - light.music_room_118
        - light.desk_63
  - title: Lights
    icon: mdi:lightbulb
    cards:
    - type: custom:monster-card
      show_empty: false
      card:
        type: glance
        title: "On"
      filter:
        include:
          - domain: light
        exclude:
          - entity_id: "*sml*"
          - state: 'off'
          - state: 'unavailable'
    - type: custom:monster-card
      show_empty: false
      card:
        type: glance
        title: "Off"
      filter:
        include:
          - domain: light
        exclude:
          - state: 'on'
  - title: Batteries
    icon: mdi:battery
    cards:
    - type: sensor
      entity: sensor.jphone_xs_battery_level
    - type: sensor
      entity: sensor.katie_s_iphone_battery_level
    - type: custom:entity-attributes-card
      heading_name: Sensor
      heading_state: Battery level
      filter:
        name_attribute: friendly_name
        include:
          # ahh i wish this could be a wildcard or a monster card
          - switch.closet_motion_61.battery_level
          - switch.front_door_12.battery_level
          - switch.front_gate_121.battery_level
          - switch.garage_hall_motion_132.battery_level
          - switch.great_hall_motion_131.battery_level
          - switch.guest_bath_motion_70.battery_level
          - switch.kitchen_motion_160.battery_level
          - switch.master_ac_water_13.battery_level
          - switch.music_room_motion_107.battery_level
          - switch.office_motion_82.battery_level
          - switch.powder_room_motion_75.battery_level
          - switch.stairs_motion_102.battery_level
          - switch.upstairs_motion_87.battery_level
          - switch.wine_room_motion_97.battery_level
          - vacuum.downstairs_roomba.battery_level
  - title: Speakers
    icon: mdi:speaker
    cards:
    - type: media-control
      entity: media_player.atrium_speakers
    - type: media-control
      entity: media_player.kitchen_speakers
    - type: media-control
      entity: media_player.living_speakers
    - type: media-control
      entity: media_player.master_bathroom_speakers
    - type: media-control
      entity: media_player.master_bedroom_speakers
    - type: media-control
      entity: media_player.patio_speakers
  - title: Upstairs
    icon: mdi:hotel
    cards:
    - type: entities
      entities:
      - light.chandelier_154
      - light.chandelier_lamp_33
      - light.master_overhead_30
      - light.master_closet_32
      - light.master_nook_42
      - light.master_windows_128
      - light.bedside_lamp_141
      - light.master_patio_31
    - type: entities
      entities:
      - light.master_bath_overhead_36
      - light.master_shower_34
      - light.master_mirror_35
      - light.master_toilet_62
      - switch.master_bath_fan_129
  - title: Great Room
    icon: mdi:sofa
    cards:
    - type: entities
      entities:
      - light.cabinets_14
      - light.dining_room_table_52
      - light.kitchen_18
      - light.living_20
      - light.pendants_51
      - light.couch_lamp_right_206
      - light.couch_lamp_left_207
  - title: Outdoor
    icon: mdi:tree
    cards:
    - type: entities
      entities:
      - switch.fountain_26
      - light.atrium_22
      - switch.back_porch_fans_228
      - light.front_porch_19
      - light.front_door_21
      - light.patio_29
      - light.master_patio_31
      - light.ac_125
      - light.atrium_door_123
      - light.garage_door_124
    - type: entities
      entities:
      - binary_sensor.front_gate_121
      - cover.garage
      - cover.gate
  - title: Environment
    icon: mdi:temperature-fahrenheit
    cards:
    - type: entities
      entities:
      - climate.great_room_27
      - climate.upstairs_28
      - climate.hall_48
  - title: Settings
    icon: mdi:settings
    cards:
    - type: entities
      entities:
      - input_boolean.guests
      - automation.away_mode
    - type: entities
      entities:
      - weblink.homeassistant_ci
      - weblink.upstream_changes
      - sensor.haconfig_branch
      - weblink.haconfig_ci
      - script.deploy_haconfig

resources:
- url: /local/monster-card.js?v=1
  type: js
- url: /local/entity-attributes-card.js?v=3
  type: js
