name: Rancho de Newland
views:
  - title: Home
    icon: mdi:home
    theme: dark-mode
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - sensor.christmas
          - type: weather-forecast
            entity: weather.dark_sky
          - type: camera-preview
            entity: camera.front_yard_left
      - type: vertical-stack
        cards:
          - type: picture-glance
            image: http://wwc.instacam.com/instacamimg/UTAUS/UTAUS_l.jpg
            entities:
              - input_select.mode
              - alarm_control_panel.alarm
              - lock.front_door_12
              - cover.garage
              - cover.gate
              - input_number.brightness
          - type: media-control
            entity: media_player.house
          - type: glance
            entities:
              - media_player.atrium_speakers
              - media_player.kitchen_speakers
              - media_player.living_speakers
              - media_player.house_mpr6zhmaut
              - media_player.house_back_porch

#   - tab_icon: mdi:home-assistant
#     title: Custom card
#     cards:
#       - type: "custom:big-state-card"
#         title: ''
#         entities:
#           - sensor.christmas
# resources:
#   - url: /local/big-state-card.js
#     type: module
