#!/bin/bash
set -xeuo pipefail

hass -c . --script check_config -i all -f > ./log
grep MainThread ./log
test "$(grep -c ERROR ./log)" -eq 0

# Confirm some specific entities
grep entry_door: ./log
grep "Jesse's desktop" ./log
