#!/bin/bash
set -euo pipefail
export $(cat .env | xargs)
touch automations.yaml
hass -c . --script check_config -i all -f | tee /tmp/log
set -x
test "$(grep -v "Unknown device" /tmp/log | grep -c ^ERROR)" -eq 0
