#!/bin/bash
# TODO document infra and deployment automation
set -e

# Bail if the git tree is dirty
if [ -n "$(git status --porcelain)" ]; then
  set -x
  exec git status
fi

# Automatically detect branch and push
: ${HA_CONFIG_BRANCH:=$(git symbolic-ref -q HEAD)}
HA_CONFIG_BRANCH=${HA_CONFIG_BRANCH##refs/heads/}
if [ -z "$HA_CONFIG_BRANCH" ]; then
  echo "What branch are you on?"
  exit 1
fi
git push origin "$HA_CONFIG_BRANCH"

# Deploy
export HA_CONFIG_BRANCH=$HA_CONFIG_BRANCH
cd $PWD/../rancho-de-newland
exec ./script/deploy
