#!/bin/bash

set -ex

rm -rf custom_components/apple_tv
git clone https://github.com/postlund/hass-atv-beta $TMPDIR/hass-atv-beta-$$
mv $TMPDIR/hass-atv-beta-$$/custom_components/apple_tv custom_components
rm -rf $TMPDIR/hass-atv-beta-$$

rm -rf custom_components/bhyve || true
git clone https://github.com/sebr/bhyve-home-assistant $TMPDIR/bhyve-home-assistant-$$
mv $TMPDIR/bhyve-home-assistant-$$/custom_components/bhyve custom_components
rm -rf $TMPDIR/bhyve-home-assistant-$$

rm -rf custom_components/homeassistant-aerogarden || true
git clone https://github.com/JeremyKennedy/homeassistant-aerogarden $TMPDIR/homeassistant-aerogarden-$$
mv $TMPDIR/homeassistant-aerogarden-$$/custom_components/aerogarden custom_components
rm -rf $TMPDIR/homeassistant-aerogarden-$$

git add custom_components