#!/bin/bash

set -ex

: ${TMPDIR:=$(mktemp -d)}

# renovate: datasource=github-releases depName=sebr/bhyve-home-assistant
BHYVE_VERSION=3.2.2
git clone --depth 1 --branch $BHYVE_VERSION https://github.com/sebr/bhyve-home-assistant $TMPDIR/$$-bhyve-home-assistant
rm -rf custom_components/bhyve || true
mv $TMPDIR/$$-bhyve-home-assistant/python_scripts/*.py python_scripts/
mv $TMPDIR/$$-bhyve-home-assistant/custom_components/bhyve custom_components

git clone https://github.com/Olen/homeassistant-plant $TMPDIR/$$-homeassistant-plant
rm -rf custom_components/plant || true
mv $TMPDIR/$$-homeassistant-plant/custom_components/plant custom_components

# renovate: datasource=github-releases depName=uvjustin/alarmdotcom
ALARM_DOT_COM_VERSION=v3.0.9
git clone --depth 1 --branch $ALARM_DOT_COM_VERSION https://github.com/uvjustin/alarmdotcom $TMPDIR/$$-alarmdotcom
rm -rf custom_components/alarmdotcom || true
mv $TMPDIR/$$-alarmdotcom/custom_components/alarmdotcom custom_components

# renovate: datasource=github-releases depName=blakeblackshear/frigate-hass-integration
FRIGATE_VERSION=v4.0.1
git clone --depth 1 --branch $FRIGATE_VERSION https://github.com/blakeblackshear/frigate-hass-integration $TMPDIR/$$-frigate
rm -rf custom_components/frigate || true
mv $TMPDIR/$$-frigate/custom_components/frigate custom_components

# renovate: datasource=github-releases depName=claytonjn/hass-circadian_lighting
CIRCADIAN_VERSION=2.1.4
git clone --depth 1 --branch $CIRCADIAN_VERSION https://github.com/claytonjn/hass-circadian_lighting $TMPDIR/$$-circadian_lighting
rm -rf custom_components/circadian_lighting || true
mv $TMPDIR/$$-circadian_lighting/custom_components/circadian_lighting custom_components

# renovate: datasource=github-releases depname=basnijholt/adaptive-lighting
ADAPTIVE_LIGHTING_VERSION=1.16.2
git clone --depth 1 --branch $ADAPTIVE_LIGHTING_VERSION https://github.com/basnijholt/adaptive-lighting $TMPDIR/$$-adaptive-lighting
rm -rf custom_components/adaptive_lighting || true
mv $TMPDIR/$$-adaptive-lighting/custom_components/adaptive_lighting custom_components

# renovate: datasource=github-releases depName=sopelj/hass-ember-mug-component
EMBER_VERSION=0.8.0
git clone --depth 1 --branch $EMBER_VERSION https://github.com/sopelj/hass-ember-mug-component $TMPDIR/$$-ember
rm -rf custom_components/ember_mug
mv $TMPDIR/$$-ember/custom_components/ember_mug custom_components

# renovate: datasource=github-releases depName=libdyson-wg/ha-dyson
DYSON_LOCAL_VERSION=v1.3.6
git clone --depth 1 --branch $DYSON_LOCAL_VERSION https://github.com/libdyson-wg/ha-dyson $TMPDIR/$$-dyson-local
rm -rf custom_components/dyson_local
mv $TMPDIR/$$-dyson-local/custom_components/dyson_local custom_components

# renovate: datasource=github-releases depName=libdyson-wg/ha-dyson-cloud
DYSON_CLOUD_VERSION=v0.19.2
git clone --depth 1 --branch $DYSON_CLOUD_VERSION https://github.com/libdyson-wg/ha-dyson-cloud $TMPDIR/$$-dyson-cloud
rm -rf custom_components/dyson_cloud
mv $TMPDIR/$$-dyson-cloud/custom_components/dyson_cloud custom_components

curl -sL --fail -o www/group-card.js https://raw.githubusercontent.com/custom-cards/group-card/0.0.6/group-card.js
curl -sL --fail -o www/auto-entities.js https://raw.githubusercontent.com/thomasloven/lovelace-auto-entities/1.12.1/auto-entities.js
curl -sL --fail -o www/mini-media-player-bundle.js https://github.com/kalkih/mini-media-player/releases/download/v1.16.6/mini-media-player-bundle.js
curl -sL --fail -o www/custom-sonos-card.js https://github.com/johanfrick/custom-sonos-card/releases/download/v5.20.1/custom-sonos-card.js
curl -sL --fail -o www/mini-graph-card-bundle.js https://github.com/kalkih/mini-graph-card/releases/download/v0.11.0/mini-graph-card-bundle.js
curl -sL --fail -o www/weather-chart-card.js https://github.com/Yevgenium/weather-chart-card/releases/download/1.2.0/weather-chart-card.js

git add custom_components
git add python_scripts
git add www

rm -rf $TMPDIR/$$-*
