#!/bin/bash

set -ex

: ${TMPDIR:=$(mktemp -d)}

# renovate: datasource=github-releases depName=sebr/bhyve-home-assistant
BHYVE_VERSION=3.2.5
git clone --depth 1 --branch $BHYVE_VERSION https://github.com/sebr/bhyve-home-assistant $TMPDIR/$$-bhyve-home-assistant
rm -rf custom_components/bhyve || true
mv $TMPDIR/$$-bhyve-home-assistant/python_scripts/*.py python_scripts/
mv $TMPDIR/$$-bhyve-home-assistant/custom_components/bhyve custom_components

git clone https://github.com/Olen/homeassistant-plant $TMPDIR/$$-homeassistant-plant
rm -rf custom_components/plant || true
mv $TMPDIR/$$-homeassistant-plant/custom_components/plant custom_components

# renovate: datasource=github-releases depName=uvjustin/alarmdotcom
ALARM_DOT_COM_VERSION=v3.0.14
git clone --depth 1 --branch $ALARM_DOT_COM_VERSION https://github.com/uvjustin/alarmdotcom $TMPDIR/$$-alarmdotcom
rm -rf custom_components/alarmdotcom || true
mv $TMPDIR/$$-alarmdotcom/custom_components/alarmdotcom custom_components

# renovate: datasource=github-releases depName=blakeblackshear/frigate-hass-integration
FRIGATE_VERSION=v5.8.0
git clone --depth 1 --branch $FRIGATE_VERSION https://github.com/blakeblackshear/frigate-hass-integration $TMPDIR/$$-frigate
rm -rf custom_components/frigate || true
mv $TMPDIR/$$-frigate/custom_components/frigate custom_components

# renovate: datasource=github-releases depName=claytonjn/hass-circadian_lighting
CIRCADIAN_VERSION=2.1.5

# a good fork, without a version
git clone --depth 1 https://github.com/obi11235/hass-circadian_lighting $TMPDIR/$$-circadian_lighting
cd $TMPDIR/$$-circadian_lighting
git checkout 844710be2753e409c27a59d5f64d1c5b025e915e
cd -
rm -rf custom_components/circadian_lighting || true
mv $TMPDIR/$$-circadian_lighting/custom_components/circadian_lighting custom_components

# renovate: datasource=github-releases depname=basnijholt/adaptive-lighting
ADAPTIVE_LIGHTING_VERSION=1.16.2
git clone --depth 1 --branch $ADAPTIVE_LIGHTING_VERSION https://github.com/basnijholt/adaptive-lighting $TMPDIR/$$-adaptive-lighting
rm -rf custom_components/adaptive_lighting || true
mv $TMPDIR/$$-adaptive-lighting/custom_components/adaptive_lighting custom_components

# renovate: datasource=github-releases depName=sopelj/hass-ember-mug-component
EMBER_VERSION=1.2.1
git clone --depth 1 --branch $EMBER_VERSION https://github.com/sopelj/hass-ember-mug-component $TMPDIR/$$-ember
rm -rf custom_components/ember_mug
mv $TMPDIR/$$-ember/custom_components/ember_mug custom_components

# renovate: datasource=github-releases depName=libdyson-wg/ha-dyson
DYSON_LOCAL_VERSION=v1.5.1
git clone --depth 1 --branch $DYSON_LOCAL_VERSION https://github.com/libdyson-wg/ha-dyson $TMPDIR/$$-dyson-local
rm -rf custom_components/dyson_local
mv $TMPDIR/$$-dyson-local/custom_components/dyson_local custom_components

# renovate: datasource=github-releases depName=libdyson-wg/ha-dyson-cloud
DYSON_CLOUD_VERSION=v0.19.2
git clone --depth 1 --branch $DYSON_CLOUD_VERSION https://github.com/libdyson-wg/ha-dyson-cloud $TMPDIR/$$-dyson-cloud
rm -rf custom_components/dyson_cloud
mv $TMPDIR/$$-dyson-cloud/custom_components/dyson_cloud custom_components

# renovate: datasource=github-releases depName=thomasddn/ha-volvo-cars
VOLVO_VERSION=v1.5.2
git clone --depth 1 --branch $VOLVO_VERSION https://github.com/thomasddn/ha-volvo-cars $TMPDIR/$$-volvo-cars
rm -rf custom_components/volvo_cars || true
mv $TMPDIR/$$-volvo-cars/custom_components/volvo_cars custom_components

# https://github.com/legrego/homeassistant-combustion
# renovate: datasource=github-releases depName=legrego/homeassistant-combustion
# TODO currently broken
# COMBUSTION_VERSION=v0.0.2
# git clone --depth 1 --branch $COMBUSTION_VERSION https://github.com/legrego/homeassistant-combustion $TMPDIR/$$-combustion
rm -rf custom_components/combustion || true
# mv $TMPDIR/$$-combustion/custom_components/combustion custom_components

# git clone --depth 1 --branch main https://github.com/codyc1515/ha-uber-eats $TMPDIR/$$-uber-eats
# rm -rf custom_components/uber_eats
# mv $TMPDIR/$$-uber-eats/custom_components/uber_eats custom_components

# https://github.com/PeteRager/lennoxs30
# renovate: datasource=github-releases depName=PeteRager/lennoxs30
LENOX_S30_VERSION=2025.5.1
git clone --depth 1 --branch $LENOX_S30_VERSION https://github.com/PeteRager/lennoxs30 $TMPDIR/$$-lennoxs30
rm -rf custom_components/lennoxs30 || true
mv $TMPDIR/$$-lennoxs30/custom_components/lennoxs30 custom_components

# renovate: datasource=github-releases depName=dahlb/ha_carrier
CARRIER_VERSION=v2.7.22
git clone --depth 1 --branch $CARRIER_VERSION https://github.com/dahlb/ha_carrier $TMPDIR/$$-carrier
rm -rf custom_components/ha_carrier || true
mv $TMPDIR/$$-carrier/custom_components/ha_carrier custom_components

# renovate datasource=github-releases depName=dolezsa/thermal_comfort
THERMAL_COMFORT_VERSION=2.2.5
git clone --depth 1 --branch $THERMAL_COMFORT_VERSION https://github.com/dolezsa/thermal_comfort $TMPDIR/$$-thermal_comfort
rm -rf custom_components/thermal_comfort || true
mv $TMPDIR/$$-thermal_comfort/custom_components/thermal_comfort custom_components

curl -sL --fail -o $TMPDIR/advanced-camera-card.zip https://github.com/dermotduffy/advanced-camera-card/releases/download/v7.2.1/advanced-camera-card.zip
# unzipping this file directly creates a folder called dist
# move all files into www
unzip -o $TMPDIR/advanced-camera-card.zip -d $TMPDIR
rm -rf www/advanced-camera-card
mv $TMPDIR/dist www/advanced-camera-card
rm -f $TMPDIR/advanced-camera-card.zip

curl -sL --fail -o www/group-card.js https://raw.githubusercontent.com/custom-cards/group-card/0.0.6/group-card.js
curl -sL --fail -o www/auto-entities.js https://raw.githubusercontent.com/thomasloven/lovelace-auto-entities/v1.16.1/auto-entities.js
curl -sL --fail -o www/card-mod.js https://raw.githubusercontent.com/thomasloven/lovelace-card-mod/v3.4.5/card-mod.js
curl -sL --fail -o www/mini-media-player-bundle.js https://github.com/kalkih/mini-media-player/releases/download/v1.16.9/mini-media-player-bundle.js
curl -sL --fail -o www/custom-sonos-card.js https://github.com/johanfrick/custom-sonos-card/releases/download/v8.6.0/custom-sonos-card.js
curl -sL --fail -o www/mini-graph-card-bundle.js https://github.com/kalkih/mini-graph-card/releases/download/v0.13.0/mini-graph-card-bundle.js

git add -A custom_components
git add -A python_scripts
git add -A www

rm -rf $TMPDIR/$$-*
