#!/bin/bash
set -e

# Inject logs into the main processes' stdout
ln -nsf /proc/1/fd/1 /var/log/docker.log
exec 1> >/var/log/docker.log 2>&1
set -x

which git || apt-get -y install git

: ${HA_CONFIG_BRANCH:=$1}

cd /config
git fetch origin
git reset --hard "origin/$HA_CONFIG_BRANCH"
