#!/bin/bash
# Usage: NWO=<username/repo> /config/script/update-config <branch>
# If branch isn't provided, we grab the most recently green one from TravisCI.

exec 1>>/proc/1/fd/1 2>&1
set -ex

BRANCH=$1

if [ -z "$BRANCH" ] && [ -n "$NWO" ]; then
  : ${TRAVIS:=travis-ci.org}
  which jq || (apt-get update && apt-get -y install jq)
  BRANCH=$(curl -s \
    https://api.$TRAVIS/repos/$NWO/builds | \
    jq -r 'map(select(.result == 0)) | sort_by(.finished_at) | .[0].branch')
fi

which git || (apt-get update && apt-get -y install git)
cd /config
git fetch origin
git reset --hard origin/$1
