# Describes the format for available virtual services

enable_rain_delay:
  description: Enable rain delay for a zone
  fields:
    entity_id:
      description: Zone
      example: "switch.backyard_zone"
    hours:
      description: Number of hours of rain delay
      example: 24

disable_rain_delay:
  description: Disable rain delay for a zone
  fields:
    entity_id:
      description: Zone
      example: "switch.backyard_zone"

start_watering:
  description: Start watering a zone
  fields:
    entity_id:
      description: Zone
      example: "switch.backyard_zone"
    minutes:
      description: Number of minutes to water the zone
      example: 15

stop_watering:
  description: Stop watering a zone
  fields:
    entity_id:
      description: Zone
      example: "switch.backyard_zone"

set_manual_preset_runtime:
  description: Set the manual preset runtime for a device entity
  fields:
    entity_id:
      description: Zone
      example: "switch.backyard_zone"
    minutes:
      description: Number of minutes to set the preset runtime
      example: 15
