alias: Ack no
mode: parallel
id: 7326c4e1-2f25-4619-be0b-07025456e3c7
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: ACK_NO
action:
  - service: notify.slack
    data:
      title: ':-1:'
      message: nope to {{ trigger.event.data.action_data.entity_id }} from {{ trigger.event.data.sourceDeviceName }}
