alias: Ack no
mode: parallel
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: ACK_NO
action:
  service: notify.slack
  data:
    title: ':-1:'
    message: nope to {{ trigger.event.data.action_data.entity_id }} from {{ trigger.event.data.sourceDeviceName }}
