alias: Ack
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: ACK_TURN_ON
action:
  - service: homeassistant.turn_on
    data_template:
      entity_id: '{{ trigger.event.data.action_data.entity_id }}'
  - service_template: '{{ trigger.event.data.action_data.notify_service }}'
    data_template:
      data:
        push:
          apns_headers:
            'apns-collapse-id': >
              {{ trigger.event.data.action_data.entity_id }}
      message: >
        {{ trigger.event.data.sourceDeviceName }} {{ trigger.event.data.action_data.confirmation_message }}.
  - service: notify.slack
    data_template:
      message: ':+1: to {{ trigger.event.data.action_data.entity_id }} from {{ trigger.event.data.sourceDeviceName }}'
      target: "#general"
