# Keep the gate closed
alias: Auto gate
trigger:
  platform: state
  entity_id: cover.gate
  to: open
  for:
    minutes: 5
action:
- service: script.ask_about_turning_on
  data:
    entity_id: script.lock_up
    message: "The gate has been open for a bit. Close it up?"
    confirmation_message: closed the gate
