# Keep the garage closed
alias: Auto garage
trigger:
  platform: state
  entity_id: cover.garage_2
  to: open
  for:
    minutes: 5
action:
- service: script.ask_about_turning_on
  data_template:
    entity_id: script.lock_up
    message: "The garage has been open for a bit. Close it up?"
