alias: Camera snaps
trigger:
  platform: time_pattern
  # Every hour
  minutes: 0
action:
  - service: script.notify_slack_about_camera
    data:
      entity_id: camera.front_yard_left
  - service: script.notify_slack_about_camera
    data:
      entity_id: camera.back_porch_fountain
  - service: script.notify_slack_about_camera
    data:
      entity_id: camera.atrium
