alias: Camera snaps
trigger:
  platform: time_pattern
  hours: "/4"
  minutes: "0"
condition:
  condition: state
  entity_id: input_select.mode
  state: Away
action:
  - service: script.notify_slack_about_camera
    data:
      entity_id: camera.front_yard_left
  - service: script.notify_slack_about_camera
    data:
      entity_id: camera.back_porch_fountain
  - service: script.notify_slack_about_camera
    data:
      entity_id: camera.atrium
