alias: Camera snaps
trigger:
  platform: time_pattern
  # Every hour
  minutes: 0
action:
  - service: notify.slack
    data_template:
      message: "Debug: {{ states.camera.front_yard_left.attributes.entity_picture }}"
  # - service: notify.slack
  #   data_template:
  #     message: ":camera_with_flash:"
  #     data:
  #       attachments:
  #       - title: Front yard left
  #         image_url: "https://home.jnewland.com/{{ states.camera.front_yard_left.attributes.entity_picture }}"
  # - service: notify.slack
  #   data_template:
  #     message: ":camera_with_flash:"
  #     data:
  #       attachments:
  #       - title: Back porch fountain
  #         image_url: "https://home.jnewland.com/{{ states.camera.back_porch_fountain.attributes.entity_picture }}"
  # - service: notify.slack
  #   data_template:
  #     message: ":camera_with_flash:"
  #     data:
  #       attachments:
  #       - title: Atrium
  #         image_url: "https://home.jnewland.com/{{ states.camera.atrium.attributes.entity_picture }}"