alias: Cooking
trigger:
  platform: state
  entity_id:
    - device_tracker.jphone_6s
    - device_tracker.katies_iphone
  to: Kitchen
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '
      {% set jphone = states.device_tracker.jphone_6s.state %}
      {% set kphone = states.device_tracker.katies_iphone.state %}
      {{
        (jphone == kphone or (jnewland == "not_home" or kphone == "not_home")) and
        states.input_select.mode.state != "Pause" and
        states.input_boolean.guests.state == "off" and
        states.input_select.mode.state != "Cooking"
      }}'
action:
  - service: script.turn_on
    entity_id: script.cooking
