alias: Gate Bell
trigger:
  platform: state
  entity_id: binary_sensor.front_gate_81
  to: 'on'
action:
  - service: notify.ios
    data_template:
      message: the front gate just opened!
      data:
        push:
          category: camera
        entity_id: camera.front_yard_left
        attachment:
          url: "{{ states.weblink.self.state }}{{ states.camera.front_yard_left.attributes.entity_picture }}"
          content-type: jpeg
          hide-thumbnail: false
