alias: Katie is home
trigger:
  platform: state
  entity_id: device_tracker.katies_iphone
  from: not_home
  to: home
condition:
  condition: template
  value_template: |
    {{ states.device_tracker.jphone_6s.state != "not_home" }}
action:
  service: notify.ios_jphone_6s
  data:
    message: 'Katie is home!'
