alias: Later
trigger:
  platform: state
  entity_id:
    - device_tracker.jphone_6s
    - device_tracker.katies_iphone
  to: not_home
  for:
    minutes: 10
condition:
  condition: template
  value_template: '
                  {{
                    states.input_boolean.guests.state == "off" and
                    states.input_select.mode.state != "Away" and
                    states.input_select.mode.state != "Pause" and
                    states.device_tracker.jphone_6s.state == "not_home" and
                    states.device_tracker.katies_iphone.state == "not_home"
                  }}
                  '
action:
  service: script.turn_on
  entity_id: script.mode_away_with_notification
