alias: Light daytime brightness
trigger:
  platform: state
  entity_id:
  - light.living_20
  to: "on"
condition:
  condition: state
  entity_id: sun.sun
  state: above_horizon
action:
  service: light.turn_on
  data_template:
    entity_id: {{ trigger.entity_id }}
    brightness: 255
