alias: log camera motion events to slack
trigger:
  platform: state
  entity_id:
    - camera.gate
    - camera.garage
    - camera.front_yard_left
  from: 'idle'
  to: 'recording'
action:
  service: notify.slack
  data_template:
    message: ':camera: motion detected'
    target: "#general"
    data:
      attachments:
        - title: '{{ trigger.to_state.attributes.friendly_name | capitalize }}'
          title_link: |
            {{ states.weblink.self.state }}{{ states[trigger.to_state.entity_id].attributes.entity_picture | replace("proxy", "proxy_stream") }}
          image_url: |
            {{ states.weblink.self.state }}{{ states[trigger.to_state.entity_id].attributes.entity_picture }}
