alias: log state changes to slack
id: 1dfd32fd-64e3-48cd-bc07-fee067110844
mode: parallel
trigger:
  platform: state
  entity_id:
    - binary_sensor.master_patio_door
    - binary_sensor.downstairs_bathroom
    - binary_sensor.downstairs_window
    - binary_sensor.music_room_window
    - binary_sensor.lounge_window
    - binary_sensor.entry_door
    - binary_sensor.garage
    - binary_sensor.gate
    - alarm_control_panel.alarm
    - automation.gate_bell
    - binary_sensor.bedroom_door_access_control_window_door_is_open
    - binary_sensor.bathroom_home_security_motion_detection
    - binary_sensor.stairs_home_security_motion_detection
    - binary_sensor.closet_motion_any
    - binary_sensor.guest_bath_home_security_motion_detection
    - binary_sensor.powder_room_home_security_motion_detection
    - binary_sensor.lounge_home_security_motion_detection
    - binary_sensor.upstairs_home_security_motion_detection
    - binary_sensor.guest_hall_home_security_motion_detection
    - binary_sensor.yoga_room_home_security_motion_detection
    - binary_sensor.dining_room_home_security_motion_detection
    - binary_sensor.front_gate_access_control_window_door_is_open
    - sensor.ups_state
    - sensor.jphone_12_battery_state
    - sensor.katie_s_iphone_battery_state
    - sensor.katie_s_iphone_activity
    - sensor.jphone_12_activity
    - device_tracker.katie_s_iphone
    - device_tracker.jphone_12
    - device_tracker.jesses_ipad
    - device_tracker.jesse_music_room
    - binary_sensor.bathroom_home_security_motion_detection
    - binary_sensor.master_ac_water
    - cover.garage
    - cover.gate
    - input_select.mode
    - lock.front_door
    - lock.back_porch
    - lock.garage
    - media_player.lounge
    - media_player.music_room
    - media_player.bedroom
    - media_player.atrium_speakers
    - media_player.house_back_porch
    - media_player.house_jnewland
    - media_player.kitchen_speakers
    - media_player.living_speakers
    - media_player.master_bathroom_speakers
    - media_player.master_bedroom_speakers
    - media_player.house_mpr6zhmaut
    - media_player.house_lounge
    - media_player.patio_speakers
    - media_player.record_cabinet
    - weather.dark_sky
    - light.kitchen_light
    - binary_sensor.kitchen_needs_nutrients
    - binary_sensor.kitchen_needs_water
    - switch.patio_irrigation_rain_delay
    - switch.patio_zone
    - group.back_porch_fan
condition:
  condition: template
  value_template: |
    {% set old_state = trigger.from_state %}
    {% set new_state = trigger.to_state %}
    {{
      (
        old_state != None and
        new_state.state != old_state.state and
        old_state.state != "Unknown"
      )
    }}
action:
  service: notify.slack
  data:
    title: state
    message: >
      {% set old_state = trigger.from_state %}
      {% set new_state = trigger.to_state %}
      {% set unit_of_measurement = state_attr(new_state.entity_id, 'unit_of_measurement') if state_attr(new_state.entity_id, 'unit_of_measurement') is not none %}
      {% set domain_emoji = {
        "alarm_control_panel": ":rotating_light:",
        "automation":          ":gear:",
        "input_select":        ":gear:",
        "media_player":        ":sound:",
        "cover":               ":house_with_garden:",
        "device_tracker":      ":iphone:",
        "weather":             ":cloud:"
      } %}
      {% set entity_emoji = {
        "sensor.jphone_12_battery_state":      ":iphone:",
        "sensor.katie_s_iphone_battery_state": ":iphone:",
        "binary_sensor.master_ac_water_13":   ":droplet:",
        "binary_sensor.front_gate_access_control_window_door_is_open":       ":house_with_garden:"
      } %}
      {% set domain_state = new_state.domain + "." + new_state.state %}
      {% set domain_state_emojis = {
        "lock.locked":   ":lock:",
        "lock.unlocked": ":unlock:"
      } %}
      {% if domain_state_emojis[domain_state] | default(none) != none -%}
        {{ domain_state_emojis[domain_state] -}}
        *{{ new_state.name | capitalize -}}*{{ " " -}}
        is {{ domain_state_emojis[domain_state] -}}
        {% set old_domain_state = new_state.domain + "." + old_state.state -%}
        after being {{ domain_state_emojis[domain_state] }}{{ " " -}}
        for {{ relative_time(old_state.last_changed) }}
      {% else -%}
        {% if entity_emoji[new_state.entity_id] | default(none) != none -%}
          {{ entity_emoji[new_state.entity_id] -}}{{ " " -}}
        {% else -%}
          {{ domain_emoji[new_state.domain] | default(":control_knobs:") -}}{{ " " -}}
        {% endif -%}
        *{{ new_state.name | capitalize -}}*{{ " " -}}
        is {% if new_state.state == "" %}{{ "'' " }}{% else %}*_{{ new_state.state | capitalize }}{{ unit_of_measurement }}_*{{ " " }}{% endif -%}
        after being {{ old_state.state | capitalize }}{{ unit_of_measurement }}{{ " " -}}
        for {{ relative_time(old_state.last_changed) }}
      {% endif -%}
