alias: Log config deploys to slack
trigger:
  platform: state
  entity_id: sensor.config_sha
action:
  service: notify.slack
  data_template:
    message: ':shipit: <https://github.com/jnewland/ha-config/commit/{{ states.sensor.config_sha.state }}|{{ states.sensor.config_sha.state }}>'
    target: "#general"
