alias: log state changes to slack
trigger:
  platform: state
  entity_id:
    - binary_sensor.living_room_motion
    - binary_sensor.master_patio_door
    - binary_sensor.entry_door
    - binary_sensor.garage
    - binary_sensor.gate
    - alarm_control_panel.alarm
    - automation.gate_bell
    - binary_sensor.master_motion
    - binary_sensor.master_bedroom_door
    - binary_sensor.master_bath_motion
    - binary_sensor.stairs_motion
    - binary_sensor.closet_motion
    - binary_sensor.guest_bath_motion
    - binary_sensor.powder_room_motion
    - binary_sensor.office_motion
    - binary_sensor.upstairs_motion
    - binary_sensor.guest_hall_motion
    - binary_sensor.music_room_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.front_gate
    - sensor.dark_sky_daily_summary
    - sensor.dark_sky_hourly_summary
    - sensor.jphone_11_pro_battery_state
    - sensor.katie_s_iphone_battery_state
    - sensor.katie_s_iphone_activity
    - sensor.jphone_11_pro_activity
    - device_tracker.katie_s_iphone
    - device_tracker.jphone_11_pro
    - device_tracker.jesses_ipad
    - device_tracker.jesse_music_room
    - binary_sensor.master_bath_motion
    - binary_sensor.master_ac_water
    - cover.garage
    - cover.gate
    - input_select.mode
    - lock.front_door
    - media_player.atrium_speakers
    - media_player.house_back_porch
    - media_player.house_jnewland
    - media_player.kitchen_speakers
    - media_player.living_speakers
    - media_player.master_bathroom_speakers
    - media_player.master_bedroom_speakers
    - media_player.house_mpr6zhmaut
    - media_player.house_office
    - media_player.patio_speakers
condition:
  condition: template
  value_template: |
    {% set old_state = trigger.from_state %}
    {% set new_state = trigger.to_state %}
    {{
      (
        old_state != None and
        new_state.state != old_state.state and
        old_state.state != "Unknown"
      )
    }}
action:
  service: notify.slack
  data_template:
    message: >
      {% set old_state = trigger.from_state %}
      {% set new_state = trigger.to_state %}
      {% set domain_emoji = {
        "alarm_control_panel": ":rotating_light:",
        "automation":          ":gear:",
        "input_select":        ":gear:",
        "media_player":        ":sound:",
        "cover":               ":house_with_garden:",
        "device_tracker":      ":iphone:"
      } %}
      {% set entity_emoji = {
        "media_player.office_tv":             ":tv:",
        "sensor.dark_sky_daily_summary":      ":cloud:",
        "sensor.dark_sky_hourly_summary":     ":cloud:",
        "sensor.jphone_11_pro_battery_state":      ":iphone:",
        "sensor.katie_s_iphone_battery_state": ":iphone:",
        "sensor.alarm_sensors":               ":door:",
        "binary_sensor.master_ac_water_13":   ":droplet:",
        "binary_sensor.front_gate_121":       ":house_with_garden:"
      } %}
      {% set entity_state = new_state.entity_id + "." + new_state.state %}
      {% set entity_state_emoji = {
        "lock.front_door.locked":   ":lock:",
        "lock.front_door.unlocked": ":unlock:"
      } %}
      {% if entity_state_emoji[entity_state] | default(none) != none -%}
        {{ entity_state_emoji[entity_state] -}}
        *{{ new_state.name | capitalize -}}*{{ " " -}}
        is {{ entity_state_emoji[entity_state] -}}
        {% set old_entity_state = new_state.entity_id + "." + old_state.state -%}
        after being {{ entity_state_emoji[old_entity_state] }}{{ " " -}}
        for {{ relative_time(old_state.last_changed) }}
      {% else -%}
        {% if entity_emoji[new_state.entity_id] | default(none) != none -%}
          {{ entity_emoji[new_state.entity_id] -}}{{ " " -}}
        {% else -%}
          {{ domain_emoji[new_state.domain] | default(":control_knobs:") -}}{{ " " -}}
        {% endif -%}
        *{{ new_state.name | capitalize -}}*{{ " " -}}
        is *_{{ new_state.state | capitalize }}{{ new_state.attributes.unit_of_measurement }}_*{{ " " -}}
        after being {{ old_state.state | capitalize }}{{ old_state.attributes.unit_of_measurement }}{{ " " -}}
        for {{ relative_time(old_state.last_changed) }}
      {% endif -%}
    target: "#general"
