alias: log climate changes to slack
mode: parallel
trigger:
  platform: state
  entity_id: climate.great_room_27, climate.upstairs_28, climate.lounge
action:
  service: notify.slack
  data:
    message: |
      {% set old_state = trigger.from_state %}
      {% set new_state = trigger.to_state %}
      :thermometer: *{{ new_state.name | capitalize }}* is currently *_{{ new_state.attributes.current_temperature }}{{ new_state.attributes.unit_of_measurement }}_*, set to *_{{ new_state.attributes.temperature }}{{ new_state.attributes.unit_of_measurement }}_* in *_{{ new_state.state }}_* mode
