alias: log climate changes to slack
id: 10f39381-28b1-427e-aec4-fb46bbf630a0
mode: parallel
trigger:
  platform: state
  entity_id: climate.upstairs, climate.downstairs
action:
  service: notify.slack
  data:
    title: ':thermometer:'
    message: >-
      {% set new_state = trigger.to_state %}
      {% set unit_of_measurement = state_attr(new_state.entity_id, 'unit_of_measurement') if state_attr(new_state.entity_id, 'unit_of_measurement') is not none %}
      *{{ new_state.name | capitalize }}*
      is currently
      *_{{ state_attr(new_state.entity_id, 'current_temperature') }}{{ unit_of_measurement }}_*,
      set to
      {% if state_attr(new_state.entity_id, 'temperature') is not none %}
      *_{{ state_attr(new_state.entity_id, 'temperature') }}{{ unit_of_measurement }}_*
      {% endif %}
      {% if state_attr(new_state.entity_id, 'target_temp_high') is not none %}
      *_{{ state_attr(new_state.entity_id, 'target_temp_low') }}{{ unit_of_measurement }}_* -
      *_{{ state_attr(new_state.entity_id, 'target_temp_high') }}{{ unit_of_measurement }}_*
      {% endif %}
      in *_{{ states(new_state.entity_id) }}_* mode
