alias: log light changes to slack
trigger:
  platform: event
  event_type: state_changed
condition:
  condition: template
  value_template: |
    {% set old_state = trigger.event.data.get("old_state") %}
    {% set new_state = trigger.event.data.get("new_state") %}
    {{
      new_state.domain == "light" and
      old_state != None and
      new_state.state != old_state.state
    }}
action:
  service: notify.slack
  data_template:
    message: |
      {% set new_state = trigger.event.data.get("new_state") %}
      {{ new_state.name | capitalize }} :bulb:
      {%- if new_state.state == "on" -%}
      {{ '%0.0f' % ( ( new_state.attributes.brightness / 255 | round ) * 100 ) }}%
      {%- else -%}
      Off
      {%- endif -%}
    target: "#general"
