alias: log climate changes to slack
trigger:
  platform: state
  entity_id: climate.great_room_27, climate.upstairs_28, climate.hall_48
action:
  service: notify.slack
  data_template:
    message: |
      {% set old_state = trigger.from_state %}
      {% set new_state = trigger.to_state %}
      :thermometer: {{ new_state.name | capitalize }} is currently {{ new_state.attributes.current_temperature }}{{ new_state.attributes.unit_of_measurement }}, and is set to {{ new_state.attributes.temperature }}{{ new_state.attributes.unit_of_measurement }} in {{ new_state.state }} mode
    target: "#general"
