alias: max brightness
trigger:
  platform: state
  entity_id: input_number.max_brightness
action:
  service: light.turn_on
  data_template:
    entity_id: |
      {%- for l in states.light if (
          l.entity_id not in states.group.ignore_max_brightness.attributes.entity_id and
          l.state == "on") -%}
        {{l.entity_id}}{% if not loop.last %}{{ ", " }}{% endif %}
      {%-endfor-%}
    brightness: |
      {{ states('input_number.max_brightness') | int }}
