alias: Mode day to evening
id: b9bd62f2-3e44-4320-9b01-8b59ccd00fd0
trigger:
  - platform: time
    at: '17:00:00'
condition:
  condition: state
  entity_id: input_select.mode
  state: Day
action:
  - service: script.turn_on
    entity_id: script.mode_evening
