alias: Morning mode
trigger:
  - platform: state
    entity_id: binary_sensor.closet_motion_61
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.master_bath_motion_200
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - sensor.jphone_xs_battery_state
    - sensor.katies_iphone_battery_state
    to: 'Unplugged'
    for:
      seconds: 30
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{ states.input_select.mode.state == "Sleeping" }}'
  - condition: time
    after: '05:00:00'
    before: '12:00:00'
  - condition: template
    value_template: '{{ states.input_boolean.guests.state == "off" }}'
action:
  # Delay a bit so the lights come on in nightlight mode
  - delay:
      seconds: 5
  - service: script.turn_on
    entity_id: script.mode_morning
