alias: Day mode
trigger:
  - platform: state
    entity_id: input_select.mode
    to: Morning
  - platform: state
    entity_id: binary_sensor.master_bath_motion_192
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - sensor.jphone_x_battery_state
    - sensor.katies_iphone_battery_state
    to: 'Unplugged'
    for:
      seconds: 60
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: input_select.mode
    state: Morning
  - condition: template
    value_template: |
      {{
        (states.device_tracker.jphone_x.state == "not_home" or states.sensor.jphone_x_battery_state.state == "Unplugged") and
        (states.device_tracker.katies_iphone.state == "not_home" or states.sensor.katies_iphone_battery_state.state == "Unplugged")
      }}
action:
  - service: script.turn_on
    entity_id: script.mode_day
  - condition: template
    value_template: '{{ states.device_tracker.jphone_x.state != "not_home" }}'
  - service: notify.ios_jphone_x
    data_template:
      message: Katie's up!
