alias: Mode away to day
trigger:
  - platform: state
    entity_id: lock.front_door
    to: 'unlocked'
  - platform: state
    entity_id: binary_sensor.garage
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.gate
    from: 'off'
    to: 'on'
  - platform: zone
    entity_id: device_tracker.jphone_11_pro
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: device_tracker.katie_s_iphone
    zone: zone.home
    event: enter
condition:
  condition: state
  entity_id: input_select.mode
  state: Away
action:
  - service: script.turn_on
    entity_id: script.mode_day
