alias: Reading mode
trigger:
  platform: state
  entity_id: binary_sensor.master_bedroom_door_205
  to: "off"
condition:
  condition: state
  entity_id: sun.sun
  state: below_horizon
action:
  - service: script.turn_on
    entity_id: script.mode_reading
