alias: Morning mode
trigger:
  - platform: state
    entity_id: binary_sensor.master_bath_motion_37
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - sensor.jphone_x_battery_state
    - sensor.katies_iphone_battery_state
    to: 'Unplugged'
    for:
      seconds: 30
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{ states.input_select.mode.state == "Sleeping" }}'
  - condition: time
    after: '05:00:00'
    before: '12:00:00'
  - condition: template
    value_template: '{{ states.input_boolean.guests.state == "off" }}'
action:
  # Delay a bit so the lights come on in nightlight mode
  - delay:
      seconds: 5
  - service: script.turn_on
    entity_id: script.mode_morning
  - condition: template
    value_template: '{{ states.device_tracker.jphone_x.state != "not_home" }}'
  - service: notify.ios_jphone_x
    data_template:
      message: |
        {{ states.weather.dark_sky.attributes.hourly_forecast_summary }}
  - condition: template
    value_template: |
      {{ not is_state("binary_sensor.roomba_on_dock", "on") }}
  - service: notify.ios_jphone_x
    data_template:
      message: |
        {% if is_state("binary_sensor.roomba_on_dock", "off") %}
        The roomba's not on the dock, btw. Help a robot out?
        {% endif %}
        {% if is_state("sensor.roomba_downstairs_state", "unavailable") %}
        The roomba's adrift. Help a robot out?
        {% endif %}
