alias: Reading mode
id: bb53911c-ef20-4ed1-8a83-84937a0a484b
trigger:
  platform: state
  entity_id: binary_sensor.bedroom_door_access_control_window_door_is_open
  to: "off"
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: input_select.mode
    state: Evening
  - condition: state
    entity_id: sun.sun
    state: below_horizon
action:
  - service: script.turn_on
    entity_id: script.mode_reading
