alias: Turn off lights after 5m
trigger:
  platform: state
  entity_id:
  - binary_sensor.powder_room_motion_75
  - binary_sensor.stairs_motion_102
  - binary_sensor.upstairs_motion_87
  - binary_sensor.closet_motion_61
  - binary_sensor.hall_motion_92
  - binary_sensor.music_room_motion_107
  to: "off"
  for:
    minutes: 5
action:
  service: homeassistant.turn_off
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_off | default(trigger.to_state.attributes.trigger_entity_id) }}
