alias: Turn on lights when motion is detected
trigger:
  platform: state
  entity_id:
  - binary_sensor.guest_bath_motion
  - binary_sensor.master_bath_motion
  - binary_sensor.powder_room_motion
  - binary_sensor.stairs_motion
  - binary_sensor.upstairs_motion
  - binary_sensor.closet_motion
  - binary_sensor.wine_room_motion
  - binary_sensor.guest_hall_motion
  - binary_sensor.music_room_motion
  - binary_sensor.living_room_motion
  - binary_sensor.kitchen_motion
  - binary_sensor.office_motion
  - binary_sensor.garage_hall_motion
  - binary_sensor.great_hall_motion
  - binary_sensor.master_motion
  to: "on"
condition:
  condition: template
  value_template: |
    {{ states.input_select.mode.state != "Away" }}
action:
  service_template: |
    {{ trigger.to_state.attributes.trigger_service | default('light.turn_on') }}
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_on | default(trigger.to_state.attributes.trigger_entity_id) | default('') }}
    brightness: |
      {{ trigger.to_state.attributes.fixed_brightness | default(states('input_number.brightness') | int) }}
