alias: Turn on lights when motion is detected
trigger:
  platform: state
  entity_id:
  - binary_sensor.guest_bath_motion_70
  - binary_sensor.master_bath_motion_37
  - binary_sensor.powder_room_motion_75
  - binary_sensor.stairs_motion_102
  - binary_sensor.upstairs_motion_87
  - binary_sensor.closet_motion_61
  - binary_sensor.wine_room_motion_97
  - binary_sensor.hall_motion_92
  - binary_sensor.music_room_motion_107
  - binary_sensor.living_room_motion
  - binary_sensor.office_motion_82
  - binary_sensor.desk_camera
  to: "on"
condition:
  condition: template
  value_template: |
    {{ states.input_select.mode.state != "Away" }}
action:
  service: homeassistant.turn_on
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_on | default(trigger.to_state.attributes.trigger_entity_id) }}
    brightness: |
      {{ states('input_number.max_brightness') | int }}
