alias: Turn off lights after 30m
trigger:
  platform: state
  entity_id:
  - binary_sensor.guest_bath_motion_70
  - binary_sensor.master_bath_motion_37
  - binary_sensor.binary_sensor.kitchen_motion_160
  to: "off"
  for:
    minutes: 30
action:
  service: homeassistant.turn_off
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_off | default(trigger.to_state.attributes.trigger_entity_id) }}
