alias: Turn off lights after 30m
trigger:
  platform: state
  entity_id:
  - binary_sensor.guest_bath_motion_70
  - binary_sensor.master_bath_motion_37
  - binary_sensor.powder_room_motion_75
  - binary_sensor.stairs_motion_6
  - binary_sensor.upstairs_motion_87
  - binary_sensor.closet_motion_61
  to: "off"
  for:
    minutes: 30
condition:
  condition: template
  value_template: '{{ states.input_select.mode.state != "Pause" }}'
action:
  service: homeassistant.turn_off
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_off | default(trigger.to_state.attributes.trigger_entity_id) }}
