alias: Turn off lights after 5m
trigger:
  platform: state
  entity_id:
  - binary_sensor.powder_room_motion
  - binary_sensor.stairs_motion
  - binary_sensor.upstairs_motion
  - binary_sensor.closet_motion
  - binary_sensor.garage_hall_motion
  - binary_sensor.great_hall_motion
  - binary_sensor.hall_motion
  - binary_sensor.music_room_motion
  to: "off"
  for:
    minutes: 5
action:
  service: homeassistant.turn_off
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_off | default(trigger.to_state.attributes.trigger_entity_id) }}
