alias: Turn off lights immediately
trigger:
  platform: state
  entity_id:
  - binary_sensor.desk_camera
  to: "off"
  for:
    minutes: 5
action:
  service: homeassistant.turn_off
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_off | default(trigger.to_state.attributes.trigger_entity_id) }}
