alias: Gate Bell
trigger:
  platform: state
  entity_id: binary_sensor.front_gate
  to: 'on'
action:
  - service: notify.iphones
    data_template:
      message: the front gate just opened!
      data:
        push:
          category: camera
        entity_id: camera.front_yard_left
        attachment:
          url: |
            https://home.jnewland.com{{ states.camera.front_yard_left.attributes.entity_picture }}
          content-type: jpeg
          hide-thumbnail: false
  - service: script.notify_with_lights
  - service: script.notify_all_channels
    data:
      message: the front gate just opened
  - service: notify.slack
    data_template:
      message: ":camera_with_flash: The front gate just opened!"
      data:
        file:
          url: |
            https://home.jnewland.com{{ states.camera.front_yard_left.attributes.entity_picture }}
