alias: Gate Bell
id: c228fcbc-a5ea-4d1f-8094-a884be31e362
trigger:
  platform: state
  entity_id: binary_sensor.front_gate
  to: 'on'
action:
  - service: notify.iphones
    data:
      message: the front gate just opened!
      data:
        push:
          category: camera
        entity_id: camera.pergola
        attachment:
          url: |
            https://home.jnewland.com{{ states.camera.pergola.attributes.entity_picture }}
          content-type: jpeg
          hide-thumbnail: false
  - service: script.notify_with_lights
  - service: script.notify_all_channels
    data:
      message: the front gate just opened
  - service: notify.slack
    data:
      title: ':camera_with_flash:'
      message: The front gate just opened!
      data:
        file:
          url: |
            https://home.jnewland.com{{ states.camera.pergola.attributes.entity_picture }}
