alias: Notify about stuff when we're away
trigger:
  platform: state
  entity_id:
    - lock.front_door
    - alarm_control_panel.alarm
    - binary_sensor.entry_door
    - binary_sensor.garage
    - binary_sensor.gate
    - binary_sensor.master_patio_door
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: input_select.mode
    state: Away
  - condition: template
    value_template: |
      {% set old_state = trigger.from_state %}
      {% set new_state = trigger.to_state %}
      {{
        old_state != None and
        new_state.state != old_state.state
      }}
action:
  service: notify.mobile_app_jphone_11_pro
  data_template:
    message: >
      {% set old_state = trigger.from_state %}
      {% set new_state = trigger.to_state %}
      {{ new_state.name | capitalize -}}{{ " " -}}
      is {{ new_state.state | capitalize }}{{ new_state.attributes.unit_of_measurement }}{{ " " -}}
      after being {{ old_state.state | capitalize }}{{ old_state.attributes.unit_of_measurement }}{{ " " -}}
      for {{ relative_time(old_state.last_changed) }}
    data:
      push:
        category: camera
      entity_id: >
        {%- if trigger.to_state.entity_id == "binary_sensor.gate" -%}
        camera.gate
        {%- elif trigger.to_state.entity_id == "binary_sensor.garage" -%}
        camera.garage
        {%- else -%}
        camera.front_yard_left
        {%- endif -%}
      attachment:
        url: >
          https://home.jnewland.com/
          {%- if trigger.to_state.entity_id == "binary_sensor.gate" -%}
          {{ states.camera.gate.attributes.entity_picture }}
          {%- elif trigger.to_state.entity_id == "binary_sensor.garage" -%}
          {{ states.camera.garage.attributes.entity_picture }}
          {%- else -%}
          {{ states.camera.front_yard_left.attributes.entity_picture }}
          {%- endif -%}
        content-type: jpeg
        hide-thumbnail: false
