alias: notify when master ac is leaking
trigger:
  platform: state
  entity_id: binary_sensor.master_ac_water
  from: 'off'
  to: 'on'
action:
  service: notify.mobile_app_jphone_12
  data:
    message: 'the master AC water sensor detected a leak'
