alias: Office lights
trigger:
  - platform: state
    entity_id:
      - device_tracker.katies_iphone
      - device_tracker.jphone_x
    to: Office
  - platform: state
    entity_id: binary_sensor.office_motion_82
    to: 'on'
condition:
  condition: template
  value_template: '
    {{
      states.input_select.mode.state != "Pause" and
      states.input_select.mode.state != "Movie"
    }}'
action:
  - service: script.turn_on
    entity_id: script.working
