alias: Playlist selector
trigger:
  platform: state
  entity_id: input_select.playlist
condition:
  condition: template
  value_template: '{{ states.input_select.playlist != "Idle" }}'
action:
  service: script.turn_on
  data_template:
    entity_id: script.house_music
    variables:
      playlist: '{{ trigger.to_state.state }}'
