alias: Powder room motion lights
trigger:
  platform: state
  entity_id: binary_sensor.powder_room_motion_75
  from: 'off'
  to: 'on'
condition:
  condition: template
  value_template: |
    {{
      states.light.powder_room_80.state == "off" and
      states.input_select.mode.state != "Pause"
    }}
action:
  service: light.turn_on
  entity_id:
    - light.powder_room_80
