# If Katie and I are both in the master for a few minutes after the sun has set,
# turn on Reading
alias: Reading
trigger:
  platform: state
  entity_id:
    - device_tracker.jphone_6s
    - device_tracker.katies_iphone
  to: Master
  for:
    minutes: 1
condition:
  condition: and
  conditions:
  - condition: template
    value_template: |
      {% set jphone = states.device_tracker.jphone_6s.state %}
      {% set kphone = states.device_tracker.katies_iphone.state %}
      {{
        (jphone == kphone or (jnewland == "not_home" or kphone == "not_home")) and
        states.input_select.mode.state != "Reading" and
        states.input_select.mode.state != "Sleeping" and
        states.input_select.mode.state != "Pause"
      }}
  - condition: state
    entity_id: sun.sun
    state: below_horizon
action:
  - service: script.turn_on
    entity_id: script.mode_reading
