alias: log media to slack
id: 6c040050-a715-4a44-a34f-68f80d9e43fd
trigger:
  platform: state
  entity_id:
    - media_player.music_room
condition:
  condition: template
  value_template: |
    {% set old_state = trigger.from_state %}
    {% set new_state = trigger.to_state %}
    {{
      (
        new_state.state == "playing" and
        state_attr(new_state.entity_id, 'media_content_type') == "music" and
        state_attr(new_state.entity_id, 'entity_picture') is defined and
        state_attr(new_state.entity_id, 'entity_picture') != state_attr(old_state.entity_id, 'entity_picture')
      )
    }}
action:
  service: notify.slack
  data:
    title: |
      {{ trigger.to_state.name | capitalize }}
    message: |
      {{ state_attr(trigger.to_state.entity_id, 'media_artist') }} - {{ state_attr(trigger.to_state.entity_id, 'media_album_name') | default("") }} - {{ state_attr(trigger.to_state.entity_id, 'media_title') }}
    data:
      file:
        url: |
          https://home.jnewland.com{{ state_attr(trigger.to_state.entity_id, 'entity_picture') }}

