alias: state debugging
initial_state: off
trigger:
  platform: state
  entity_id:
    - device_tracker.katie_s_iphone
    - device_tracker.jphone_11_pro
    - sensor.jphone_11_pro_battery_state
    - sensor.katies_iphone_battery_state
condition:
  condition: template
  value_template: |
    {% set old_state = trigger.from_state %}
    {% set new_state = trigger.to_state %}
    {{
      old_state != None and
      new_state.state != old_state.state
    }}
action:
  service: notify.mobile_app_jphone_11_pro
  data_template:
    message: >
      {% set old_state = trigger.from_state %}
      {% set new_state = trigger.to_state %}
      {{ new_state.name | capitalize -}}{{ " " -}}
      is {{ new_state.state | capitalize }}{{ new_state.attributes.unit_of_measurement }}{{ " " -}}
      after being {{ old_state.state | capitalize }}{{ old_state.attributes.unit_of_measurement }}{{ " " -}}
      for {{ relative_time(old_state.last_changed) }}
