# If Katie and I are both in the office for a few minutes and the sun is up,
# set the mode to Working.
alias: Working
trigger:
  platform: state
  entity_id:
    - device_tracker.jphone_6s
    - device_tracker.katies_iphone
  to: Office
  for:
    minutes: 2
condition:
  condition: and
  conditions:
  - condition: sun
    after: sunrise
    after_offset: '-1:00:00'
  - condition: template
    value_template: '
      {% set jphone = states.device_tracker.jphone_6s.state %}
      {% set kphone = states.device_tracker.katies_iphone.state %}
      {{
        (jphone == kphone or (jnewland == "not_home" or kphone == "not_home")) and
        states.input_select.mode.state != "Movie" and
        states.input_select.mode.state != "Pause" and
        states.input_boolean.guests.state == "off" and
        states.input_select.mode.state != "Working"
      }}'
action:
  - service: script.turn_on
    entity_id: script.mode_working
