alias: Turn on lights when devices enter zones
trigger:
  platform: state
  entity_id:
  - device_tracker.jphone_11_pro
  - device_tracker.katie_s_iphone
condition:
  condition: template
  value_template: |
    {{ trigger.from_state.state != trigger.to_state.state }}
action:
  service_template: |
    {{ trigger.to_state.attributes.trigger_service | default('light.turn_on') }}
  data_template:
    entity_id: |
      {{ trigger.to_state.attributes.trigger_entity_id_on | default(trigger.to_state.attributes.trigger_entity_id) | default('') }}
    brightness: |
      {{ trigger.to_state.attributes.fixed_brightness | default(states('input_number.brightness') | int) }}
