sensor:
  - platform: template
    sensors:
      jphone_areas_of_interest:
        friendly_name: jPhone areas of interest
        value_template: |
          {{ state_attr('sensor.jphone_geocoded_location', 'Areas Of Interest') | join(' ,') }}
