script:
  ask_about_turning_on:
    sequence:
      - service: >
          {{ service | default("notify.iphones") }}
        data:
          message: |
            {{ message | default("Turn on " + entity_id) }}
          data:
            tag: >
              {{ tag | default(entity_id) }}
            actions:
              - action: ACK_TURN_ON
                title: Hell yeah
                destructive: true
                authenticationRequired: |
                  {{ secure | default("false") != "false" }}
              - action: ACK_NO
                title: Nah
            action_data:
              tag: >
                {{ tag | default(entity_id) }}
              entity_id: |
                {{ entity_id }}
              notify_service: >
                {{ service | default("notify.iphones") }}
              confirmation_message: |
                {{ confirmation_message | default("turned on " + entity_id) }}
      - service: notify.slack
        data:
          title: ':question:'
          message: |
            Asked {{ message | default("about turning on " + entity_id) }}

automation:
- alias: Ack no
  mode: parallel
  id: 7326c4e1-2f25-4619-be0b-07025456e3c7
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: ACK_NO
  action:
    - service: notify.slack
      data:
        title: ':-1:'
        message: nope to {{ trigger.event.data.action_data.entity_id }} from {{ trigger.event.data.sourceDeviceName }}
- alias: Ack
  id: 097d52cd-442e-40ab-9d25-bbee32bc1fe4
  mode: parallel
  trigger:
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: ACK_TURN_ON
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: '{{ trigger.event.data.action_data.entity_id }}'
    - service: '{{ trigger.event.data.action_data.notify_service }}'
      data:
        message: >
          {{ trigger.event.data.sourceDeviceName }} {{ trigger.event.data.action_data.confirmation_message }}.
        data:
          tag: >
            {{ trigger.event.data.action_data.tag | default(trigger.event.data.action_data.entity_id) }}
    - service: notify.slack
      data:
        title: ':+1:'
        message: yep to {{ trigger.event.data.action_data.entity_id }} from {{ trigger.event.data.sourceDeviceName }}

