automation:
  - alias: Double check location katie
    id: 5dee9e89-cac9-437e-a1a2-a4a8cc52133c
    trigger:
      platform: state
      entity_id:
        - device_tracker.katie_s_iphone
      to: not_home
      for:
        minutes: 5
    action:
      - service: notify.mobile_app_katie_s_iphone
        data:
          message: request_location_update

  - alias: Double check location jesse
    id: a5bc68dd-5989-4bbd-a7cc-4e38859cd4b8
    trigger:
      platform: state
      entity_id:
        - device_tracker.jphone_12
      to: not_home
      for:
        minutes: 5
    action:
      - service: notify.mobile_app_jphone_12
        data:
          message: request_location_update

  - alias: Away mode
    id: d9daa55b-e9a8-4066-8924-39ddbc7257f7
    trigger:
      - platform: state
        entity_id:
          - device_tracker.jphone_12
          - device_tracker.katie_s_iphone
        to: not_home
        for:
          minutes: 10
      - platform: state
        entity_id:
          - device_tracker.jphone_12
          - device_tracker.katie_s_iphone
        to: not_home
        for:
          minutes: 15
    condition:
      condition: template
      value_template: '
                      {{
                        states.input_boolean.visitor.state == "off" and
                        states.input_boolean.guests.state == "off" and
                        states.input_select.mode.state != "Away" and
                        states.device_tracker.jphone_12.state == "not_home" and
                        states.device_tracker.katie_s_iphone.state == "not_home"
                      }}
                      '
    action:
    - service: script.ask_about_turning_on
      data:
        entity_id: script.mode_away
        message: "Looks like everyone is gone. Turn on away?"
        confirmation_message: turned on away mode

  - alias: Notify about stuff when we're away
    id: 42bd3505-3443-4c3c-8ab3-75186cc628cf
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - lock.front_door
        - lock.back_porch
        - lock.garage
        - alarm_control_panel.alarm
        - binary_sensor.entry_door
        - binary_sensor.garage
        - binary_sensor.gate
        - binary_sensor.master_patio_door
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_select.mode
        state: Away
      - condition: template
        value_template: |
          {% set old_state = trigger.from_state %}
          {% set new_state = trigger.to_state %}
          {{
            old_state != None and
            new_state.state != old_state.state
          }}
    action:
      service: notify.mobile_app_jphone_12
      data:
        message: >
          {% set old_state = trigger.from_state %}
          {% set new_state = trigger.to_state %}
          {{ new_state.name | capitalize -}}{{ " " -}}
          is {{ new_state.state | capitalize }}{{ state_attr(new_state.entity_id, 'unit_of_measurement') }}{{ " " -}}
          after being {{ old_state.state | capitalize }}{{ state_attr(old_state.entity_id, 'unit_of_measurement') }}{{ " " -}}
          for {{ relative_time(old_state.last_changed) }}
        data:
          push:
            category: camera
          entity_id: >
            {%- if trigger.to_state.entity_id == "binary_sensor.gate" -%}
            camera.gate
            {%- elif trigger.to_state.entity_id == "binary_sensor.garage" -%}
            camera.garage
            {%- else -%}
            camera.front_door
            {%- endif -%}
          attachment:
            url: >
              {{ states('input_text.external_url') }}
              {%- if trigger.to_state.entity_id == "binary_sensor.gate" -%}
              {{ states.camera.gate.attributes.entity_picture }}
              {%- elif trigger.to_state.entity_id == "binary_sensor.garage" -%}
              {{ states.camera.garage.attributes.entity_picture }}
              {%- else -%}
              {{ states.camera.front_door.attributes.entity_picture }}
              {%- endif -%}
            content-type: jpeg
            hide-thumbnail: false

script:
  mode_away:
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          - group.indoor
      - service: homeassistant.turn_on
        entity_id:
          - group.indoor_cams
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.alarm
      - service: script.lock_up
      - service: input_select.select_option
        data:
          entity_id: input_select.mode
          option: Away
