automation:
  - alias: Double check location katie
    id: 5dee9e89-cac9-437e-a1a2-a4a8cc52133c
    trigger:
      platform: state
      entity_id:
        - device_tracker.katie_s_iphone
      to: not_home
      for:
        minutes: 5
    action:
      - service: notify.mobile_app_katie_s_iphone
        data:
          message: request_location_update
  - alias: Double check location jesse
    id: a5bc68dd-5989-4bbd-a7cc-4e38859cd4b8
    trigger:
      platform: state
      entity_id:
        - device_tracker.jphone_12
      to: not_home
      for:
        minutes: 5
    action:
      - service: mobile_app_jphone_12
        data:
          message: request_location_update

  - alias: Away mode
    id: d9daa55b-e9a8-4066-8924-39ddbc7257f7
    trigger:
      - platform: state
        entity_id:
          - device_tracker.jphone_12
          - device_tracker.katie_s_iphone
        to: not_home
        for:
          minutes: 10
      - platform: state
        entity_id:
          - device_tracker.jphone_12
          - device_tracker.katie_s_iphone
        to: not_home
        for:
          minutes: 15
    condition:
      condition: template
      value_template: '
                      {{
                        states.input_boolean.visitor.state == "off" and
                        states.input_boolean.guests.state == "off" and
                        states.input_select.mode.state != "Away" and
                        states.device_tracker.jphone_12.state == "not_home" and
                        states.device_tracker.katie_s_iphone.state == "not_home"
                      }}
                      '
    action:
    - service: script.ask_about_turning_on
      data:
        entity_id: script.mode_away
        message: "Looks like everyone is gone. Turn on away?"
        confirmation_message: turned on away mode