automation:
  - alias: Double check location katie
    id: 5dee9e89-cac9-437e-a1a2-a4a8cc52133c
    trigger:
      platform: state
      entity_id:
        - device_tracker.katie_s_iphone
      to: not_home
      for:
        minutes: 5
    action:
      - service: notify.mobile_app_katies_iphone
        data:
          message: request_location_update

  - alias: Double check location jesse
    id: a5bc68dd-5989-4bbd-a7cc-4e38859cd4b8
    trigger:
      platform: state
      entity_id:
        - device_tracker.jphone
      to: not_home
      for:
        minutes: 5
    action:
      - service: notify.mobile_app_jphone
        data:
          message: request_location_update

  - alias: Away mode
    id: d9daa55b-e9a8-4066-8924-39ddbc7257f7
    trigger:
      - platform: state
        entity_id:
          - device_tracker.jphone
          - device_tracker.katie_s_iphone
        to: not_home
        for:
          minutes: 10
      - platform: state
        entity_id:
          - device_tracker.jphone
          - device_tracker.katie_s_iphone
        to: not_home
        for:
          minutes: 15
    condition:
      condition: template
      value_template: '
        {{
        states.input_boolean.visitor.state == "off" and
        states.input_boolean.guests.state == "off" and
        states.input_select.mode.state != "Away" and
        states.device_tracker.jphone.state == "not_home" and
        states.device_tracker.katie_s_iphone.state == "not_home"
        }}
        '
    action:
      - service: script.ack
        data:
          entity_id: script.mode_away
          message: "Looks like everyone is gone. Turn on away?"
          confirmation_message: turned on away mode.

  - alias: Notify about stuff when we're away
    id: 42bd3505-3443-4c3c-8ab3-75186cc628cf
    mode: parallel
    trigger:
      - platform: state
        entity_id:
          - lock.front_door
          - lock.back_porch
          - lock.garage
          - alarm_control_panel.alarm
          - binary_sensor.entry_door
          - binary_sensor.garage
          - binary_sensor.gate
          - binary_sensor.master_patio_door
        not_to:
          - unknown
          - unavailable
        not_from:
          - unknown
          - unavailable
      - platform: state
        entity_id:
          - lock.front_door
          - lock.back_porch
          - lock.garage
          - alarm_control_panel.alarm
          - binary_sensor.entry_door
          - binary_sensor.garage
          - binary_sensor.gate
          - binary_sensor.master_patio_door
        to:
          - unknown
          - unavailable
        for:
          minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.mode
          state: Away
        - condition: template
          value_template: |
            {% set old_state = trigger.from_state %}
            {% set new_state = trigger.to_state %}
            {{
              old_state != None and
              new_state.state != old_state.state
            }}
    action:
      service: notify.iphones
      data:
        message: >
          {% set old_state = trigger.from_state %}
          {% set new_state = trigger.to_state %}
          {{ new_state.name | capitalize -}}{{ " " -}}
          is {{ new_state.state | capitalize }}{{ " " -}}
          after being {{ old_state.state | capitalize }}{{ " " -}}
          for {{ relative_time(old_state.last_changed) }}
        data:
          push:
            category: camera
          entity_id: >
            {%- if trigger.to_state.entity_id == "binary_sensor.gate" -%}
            camera.gate_medium
            {%- elif trigger.to_state.entity_id == "binary_sensor.garage" -%}
            camera.garage_medium
            {%- else -%}
            camera.front_door_medium
            {%- endif -%}
          attachment:
            url: >
              {{ states('input_text.external_url') }}
              {%- if trigger.to_state.entity_id == "binary_sensor.gate" -%}
              {{ states.camera.gate_medium.attributes.entity_picture }}
              {%- elif trigger.to_state.entity_id == "binary_sensor.garage" -%}
              {{ states.camera.garage_medium.attributes.entity_picture }}
              {%- else -%}
              {{ states.camera.front_door_medium.attributes.entity_picture }}
              {%- endif -%}
            content-type: jpeg
            hide-thumbnail: false

  - alias: Notify Jesse when Katie is home
    id: e483474f-9182-47f4-9c7a-726c096e732b
    trigger:
      platform: state
      entity_id: device_tracker.katie_s_iphone
      from: not_home
      to: home
    condition:
      condition: template
      value_template: |
        {{ states.device_tracker.jphone.state != "not_home" }}
    action:
      service: notify.mobile_app_jphone
      data:
        message: "Katie is home!"

script:
  mode_away:
    mode: parallel
    sequence:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.alarm
        data:
          code: " "
      - service: homeassistant.turn_off
        entity_id:
          - group.indoor
      - service: script.lock_up
      - service: input_select.select_option
        data:
          entity_id: input_select.mode
          option: Away
