automation:
  - alias: Keep the back_porch door locked
    id: 7f90d793-9f25-4690-8a88-92daf481d7d3
    trigger:
      platform: state
      entity_id: binary_sensor.back_porch_occupancy
      to: 'off'
      for:
        minutes: 30
    condition:
      condition: state
      entity_id: lock.back_porch
      state: unlocked
    action:
    - service: script.ask_about_turning_on
      data:
        entity_id: script.lock_back_porch
        message: "The back porch door has been unlocked for a bit. Lock it up?"
        confirmation_message: locked the back porch door
script:
  lock_back_porch:
    sequence:
      - service: lock.lock
        data:
          entity_id: lock.back_porch
  turn_on_switch:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: >
            {{ entity_id }}
  turn_off_switch:
    sequence:
      - service: switch.turn_off
        data:
          entity_id: >
            {{ entity_id }}

homeassistant:
  customize:
    binary_sensor.back_porch_occupancy:
      trigger_service: script.turn_on_switch
      trigger_service_off: script.turn_off_switch
      trigger_entity_id: switch.back_porch_fan
      trigger_entity_id_off: switch.back_porch_fan
