input_boolean:
  christmas:
    icon: mdi:pine-tree

group:
  trees:
    icon: mdi:pine-tree
    entities:
      - switch.great_room_tree
      # - switch.hall_tree
      # - switch.lounge_left
      - switch.treeo

homeassistant:
  customize:
    switch.great_room_tree:
      icon: mdi:pine-tree
    switch.hall_tree:
      icon: mdi:pine-tree
    switch.lounge_left:
      icon: mdi:pine-tree
    switch.treeo:
      icon: mdi:pine-tree

automation:
  - alias: Sunset
    id: 1496390b-4ca0-4a9d-9a3e-23a69ef028c8
    trigger:
      platform: sun
      event: sunset
    action:
      service: homeassistant.turn_on
      entity_id: group.trees
