sensor:
- platform: template
  sensors:
    dark_sky_temperature:
      friendly_name: dark sky
      unit_of_measurement: '°F'
      value_template: |
        {{ state_attr('weather.dark_sky', 'temperature') }}
    downstairs_humidity:
      friendly_name: downstairs humidity
      unit_of_measurement: '%'
      value_template: |
        {{ state_attr('climate.downstairs', 'current_humidity') }}
    downstairs_temperature:
      friendly_name: downstairs temperature
      unit_of_measurement: '°F'
      value_template: |
        {{ state_attr('climate.downstairs', 'current_temperature') }}
    upstairs_temperature:
      friendly_name: upstairs
      unit_of_measurement: '°F'
      value_template: |
        {{ state_attr('climate.upstairs', 'current_temperature') }}

automation:
  - alias: upstairs heat
    mode: queued
    id: 052a2e46-33e4-4964-8da4-42609ca7e683
    trigger:
      platform: numeric_state
      entity_id:
        - climate.upstairs
      value_template: "{{ state.attributes.current_temperature }}"
      below: 68
      for:
        minutes: 3
    condition:
      condition: numeric_state
      entity_id: weather.dark_sky
      below: 68
      value_template: "{{ state.attributes.temperature }}"
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: "{{ trigger.to_state.entity_id }}"
          hvac_mode: heat
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: "{{ trigger.to_state.entity_id }}"
          temperature: 69

  - alias: upstairs AC
    mode: queued
    id: c66cded8-2a60-4dd4-96cc-677ff080934c
    trigger:
      - platform: numeric_state
        entity_id:
          - climate.upstairs
        value_template: "{{ state.attributes.current_temperature }}"
        above: 73
        for:
          minutes: 3
      - platform: numeric_state
        entity_id:
          - climate.upstairs
        value_template: "{{ state.attributes.current_temperature }}"
        above: 74
      - platform: numeric_state
        entity_id:
          - climate.upstairs
        value_template: "{{ state.attributes.current_temperature }}"
        above: 75
    action:
      - service: cover.close_cover
        data:
          entity_id: cover.bedroom_shades
      - service: climate.set_hvac_mode
        data:
          entity_id: "{{ trigger.to_state.entity_id }}"
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: "{{ trigger.to_state.entity_id }}"
          temperature: 73

  - alias: upstairs reading
    mode: queued
    id: f9784a98-1586-4f2f-b9fe-129bee235ac5
    trigger:
    - platform: state
      entity_id: input_select.mode
      to: Reading
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69
      - delay:
          seconds: 10
      - service: climate.set_fan_mode
        entity_id:  climate.upstairs
        data:
          fan_mode: "on"

  - alias: upstairs sleeping
    mode: queued
    id: de717eac-9b51-4f6e-b636-9c8ddcd7e610
    trigger:
    - platform: state
      entity_id: input_select.mode
      to: Sleeping
    action:
      - service: climate.set_fan_mode
        entity_id: climate.upstairs
        data:
          fan_mode: "on"
      - delay:
          seconds: 10
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs morning climate reset
    mode: queued
    id: 16456902-c3b2-44ab-8765-454eab93d4b3
    trigger:
    - platform: state
      entity_id: input_select.mode
      to: Morning
    action:
      - service: climate.set_hvac_mode
        entity_id:  climate.upstairs
        data:
          hvac_mode: "off"
      - delay:
          seconds: 10
      - service: climate.set_fan_mode
        entity_id:  climate.upstairs
        data:
          fan_mode: "auto"
