sensor:
- platform: template
  sensors:
    dark_sky_temperature:
      friendly_name: dark sky
      unit_of_measurement: '°F'
      value_template: |
        {{ state_attr('weather.dark_sky', 'temperature') }}

automation:
  - alias: poll GoControl GC-TBZ48
    # I've set param 23 to 8319, which should cause the thing to report
    # No such luck, so poll it every minute
    id: 7195ed64-b3c1-4940-96bf-77251ea54b6b
    trigger:
    - platform: time_pattern
      minutes: "*"
    action:
    - service: zwave_js.refresh_value
      data:
        entity_id: climate.upstairs
        refresh_all_values: true
    - service: zwave_js.refresh_value
      data:
        entity_id: sensor.upstairs_thermostat_air_temperature

  - alias: upstairs heat
    mode: queued
    id: 052a2e46-33e4-4964-8da4-42609ca7e683
    trigger:
      platform: numeric_state
      entity_id: sensor.upstairs_thermostat_air_temperature
      below: 68
      for:
        minutes: 3
    condition:
      condition: numeric_state
      entity_id: weather.dark_sky
      attribute: temperature
      below: 68
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: heat
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs AC
    mode: queued
    id: c66cded8-2a60-4dd4-96cc-677ff080934c
    trigger:
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 74
        for:
          minutes: 3
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 75
    action:
      - service: cover.close_cover
        data:
          entity_id: cover.bedroom_shades
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 74

  - alias: upstairs reading
    mode: queued
    id: f9784a98-1586-4f2f-b9fe-129bee235ac5
    trigger:
    - platform: state
      entity_id: input_select.mode
      to: Reading
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69
      - delay:
          seconds: 10
      - service: climate.set_fan_mode
        entity_id:  climate.upstairs
        data:
          fan_mode: "Low"

  - alias: upstairs sleeping
    mode: queued
    id: de717eac-9b51-4f6e-b636-9c8ddcd7e610
    trigger:
    - platform: state
      entity_id: input_select.mode
      to: Sleeping
    action:
      - service: climate.set_fan_mode
        entity_id: climate.upstairs
        data:
          fan_mode: "Low"
      - delay:
          seconds: 10
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs morning climate reset
    mode: queued
    id: 16456902-c3b2-44ab-8765-454eab93d4b3
    trigger:
    - platform: state
      entity_id: input_select.mode
      to: Morning
    action:
      - service: climate.set_hvac_mode
        entity_id:  climate.upstairs
        data:
          hvac_mode: "off"
      - delay:
          seconds: 10
      - service: climate.set_fan_mode
        entity_id:  climate.upstairs
        data:
          fan_mode: "Auto low"
