me:
  upstairs_thermostat_target_temperature:
    name: upstairs daytime AC target
    initial: 76
    min: 67
    max: 78
    step: 1
    mode: slider

  upstairs_nighttime_target_temperature:
    name: upstairs nighttime AC target
    initial: 69
    min: 67
    max: 78
    step: 1
    mode: slider

template:
  - binary_sensor:
      - name: "Upstairs HVAC Active"
        unique_id: upstairs_hvac_active
        state: >
          {{ state_attr('climate.upstairs', 'hvac_action')
               in ['cooling', 'heating'] }}
      - name: "Downstairs HVAC Active"
        unique_id: downstairs_hvac_active
        state: >
          {{ state_attr('climate.downstairs', 'hvac_action')
               in ['cooling', 'heating'] }}

sensor:
  ## Duty-cycle (% of current hour the system is ON)
  - platform: history_stats
    name: Upstairs HVAC Duty Cycle Hourly
    entity_id: binary_sensor.upstairs_hvac_active
    state: "on"
    type: ratio
    start: "{{ now().replace(minute=0, second=0, microsecond=0) }}"
    duration: { hours: 1 }

  - platform: history_stats
    name: Downstairs HVAC Duty Cycle Hourly
    entity_id: binary_sensor.downstairs_hvac_active
    state: "on"
    type: ratio
    start: "{{ now().replace(minute=0, second=0, microsecond=0) }}"
    duration: { hours: 1 }

  ## Runtime (hours so far today)
  - platform: history_stats
    name: Upstairs HVAC Runtime Daily
    entity_id: binary_sensor.upstairs_hvac_active
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    duration: { hours: 24 }

  - platform: history_stats
    name: Downstairs HVAC Runtime Daily
    entity_id: binary_sensor.downstairs_hvac_active
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    duration: { hours: 24 }

automation:
  - alias: upstairs heat
    id: 052a2e46-33e4-4964-8da4-42609ca7e683
    trigger:
      # controls
      - id: input_number
        platform: state
        entity_id: input_number.upstairs_thermostat_target_temperature
      # mode changes
      - platform: state
        entity_id: input_select.mode
      # stopgap
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        below: 67
        for:
          minutes: 3
    conditions:
      - "{{ not is_state('climate.upstairs', 'heat') }}"
      - condition: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        below: 67
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: heat
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: >
            {{ states('input_number.upstairs_nighttime_target_temperature') | int }}

  - alias: upstairs daytime AC
    id: c66cded8-2a60-4dd4-96cc-677ff080934c
    mode: queued
    trigger:
      # controls
      - id: input_number
        platform: state
        entity_id: input_number.upstairs_thermostat_target_temperature
      # mode changes
      - platform: state
        entity_id: input_select.mode
      # stopgap for when the upstairs thermostat is set to heat while away or something
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 78
        for:
          minutes: 3
    conditions:
      - condition: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 67
      - "{{ not is_state('input_select.mode', 'Sleeping') }}"
      - "{{ not is_state('input_select.mode', 'Reading') }}"
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: >
            {{ states('input_number.upstairs_thermostat_target_temperature') | int }}

  - alias: upstairs nighttime AC
    id: f9784a98-1586-4f2f-b9fe-129bee235ac5
    trigger:
      # controls
      - platform: state
        entity_id: input_number.upstairs_nighttime_target_temperature
      # stopgap
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 78
        for:
          minutes: 3
      # mode changes
      - platform: state
        entity_id: input_select.mode
        to: Reading
      - platform: state
        entity_id: input_select.mode
        to: Sleeping
    conditions:
      - "{{ is_state('input_select.mode', 'Sleeping') or is_state('input_select.mode', 'Reading') }}"
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: >
            {{ states('input_number.upstairs_nighttime_target_temperature') | int }}

  - alias: notify when leak sensor trips
    id: 85023ab0-13e5-4b4a-aba1-3e7d58973ad1
    trigger:
      platform: state
      entity_id: binary_sensor.leak_sensor_water_alarm_water_leak_detected
      from: "off"
      to: "on"
    action:
      - service: notify.iphones
        data:
          message: leak sensor detected a leak

  - alias: notify us when the downstairs climate current_temperature goes above setpoint in cool mode
    id: 1b2b0b5e-5b0a-4b0e-8b0a-2b0b5e5b0a4b
    trigger:
      platform: template
      value_template: |
        {{
          state_attr('climate.downstairs', 'hvac_action') == 'cooling' and
          state_attr('climate.downstairs', 'current_temperature') > state_attr('climate.downstairs', 'temperature')
        }}
    condition:
      condition: template
      value_template: "{{ state_attr('climate.downstairs', 'hvac_action') == 'cooling' }}"
    action:
      - service: notify.iphones
        data:
          message: >
            downstairs AC isn't keeping up.
            Current temp is {{ state_attr('climate.downstairs', 'current_temperature') }}
            and target temp is {{ state_attr('climate.downstairs', 'temperature') }}.

  - alias: notify us when downstairs climate is idle
    id: 59b0a151-122a-46dc-81bd-fd099fba0018
    trigger:
      platform: state
      entity_id: climate.downstairs
      to: "idle"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ state_attr('climate.downstairs', 'current_temperature') > state_attr('climate.downstairs', 'temperature') }}"
        - condition: template
          value_template: "{{ state_attr('climate.upstairs', 'hvac_action') == 'cooling' }}"
    action:
      - service: notify.iphones
        data:
          message: >
            downstairs AC has given up.
            Current temp is {{ state_attr('climate.downstairs', 'current_temperature') }}
            and target temp is {{ state_attr('climate.downstairs', 'temperature') }}.
