automation:
  - alias: poll GoControl GC-TBZ48
    # I've set param 23 to 8319, which should cause the thing to report
    # No such luck, so poll it every 5 minutes
    id: 7195ed64-b3c1-4940-96bf-77251ea54b6b
    trigger:
      - platform: time_pattern
        minutes: "/5"
    action:
      - service: zwave_js.refresh_value
        data:
          entity_id: climate.upstairs
          refresh_all_values: true
      - service: zwave_js.refresh_value
        data:
          entity_id: sensor.upstairs_thermostat_air_temperature

  - alias: upstairs heat
    id: 052a2e46-33e4-4964-8da4-42609ca7e683
    trigger:
      platform: numeric_state
      entity_id: sensor.upstairs_thermostat_air_temperature
      below: 68
      for:
        minutes: 3
    condition:
      condition: numeric_state
      entity_id: weather.tomorrow_io_home_nowcast
      attribute: temperature
      below: 68
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: heat
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs AC
    id: c66cded8-2a60-4dd4-96cc-677ff080934c
    trigger:
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 74
        for:
          minutes: 3
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 75
    conditions: >-
      {{ not is_state('climate.upstairs', 'cool') }}
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 74

  - alias: upstairs reading
    id: f9784a98-1586-4f2f-b9fe-129bee235ac5
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Reading
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69
      - delay:
          seconds: 10
      - service: climate.set_fan_mode
        entity_id: climate.upstairs
        data:
          fan_mode: "Low"

  - alias: upstairs sleeping
    id: de717eac-9b51-4f6e-b636-9c8ddcd7e610
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Sleeping
    action:
      - service: climate.set_fan_mode
        entity_id: climate.upstairs
        data:
          fan_mode: "Low"
      - delay:
          seconds: 10
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 10
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs morning climate reset
    id: 16456902-c3b2-44ab-8765-454eab93d4b3
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Morning
    action:
      - service: climate.set_hvac_mode
        entity_id: climate.upstairs
        data:
          hvac_mode: "off"
      - delay:
          seconds: 10
      - service: climate.set_fan_mode
        entity_id: climate.upstairs
        data:
          fan_mode: "Auto low"

  - alias: notify when leak sensor trips
    id: 85023ab0-13e5-4b4a-aba1-3e7d58973ad1
    trigger:
      platform: state
      entity_id: binary_sensor.leak_sensor_water_alarm_water_leak_detected
      from: "off"
      to: "on"
    action:
      - service: notify.iphones
        data:
          message: leak sensor detected a leak

  - alias: notify us when the downstairs climate current_temperature goes above setpoint in cool mode
    id: 1b2b0b5e-5b0a-4b0e-8b0a-2b0b5e5b0a4b
    trigger:
      platform: template
      value_template: |
        {{
          state_attr('climate.downstairs', 'hvac_action') == 'cooling' and
          state_attr('climate.downstairs', 'current_temperature') > state_attr('climate.downstairs', 'temperature')
        }}
    condition:
      condition: template
      value_template: "{{ state_attr('climate.downstairs', 'hvac_action') == 'cooling' }}"
    action:
      - service: notify.iphones
        data:
          message: >
            downstairs AC isn't keeping up.
            Current temp is {{ state_attr('climate.downstairs', 'current_temperature') }}
            and target temp is {{ state_attr('climate.downstairs', 'temperature') }}.

  - alias: notify us when downstairs climate is idle
    id: 59b0a151-122a-46dc-81bd-fd099fba0018
    trigger:
      platform: state
      entity_id: climate.downstairs
      to: "idle"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ state_attr('climate.downstairs', 'current_temperature') > state_attr('climate.downstairs', 'temperature') }}"
        - condition: template
          value_template: "{{ state_attr('climate.upstairs', 'hvac_action') == 'cooling' }}"
    action:
      - service: notify.iphones
        data:
          message: >
            downstairs AC has given up.
            Current temp is {{ state_attr('climate.downstairs', 'current_temperature') }}
            and target temp is {{ state_attr('climate.downstairs', 'temperature') }}.
