template:
  - sensor:
      - name: "Indoor Dew Point"
        unique_id: indoor_dew_point
        unit_of_measurement: "°F"
        device_class: temperature
        state_class: measurement
        state: >
          {% set T_f = states('sensor.downstairs_temperature') | float(default=0) %}
          {% set RH = states('sensor.downstairs_humidity') | float(default=0) %}
          {# Convert Fahrenheit to Celsius for the Magnus formula #}
          {% set T = (T_f - 32) * 5 / 9 %}
          {# Magnus formula constants for calculating dew point #}
          {% set a = 17.625 %}
          {% set b = 243.04 %}
          {# Calculate gamma using the Magnus approximation formula #}
          {# This combines temperature and humidity to find the saturation point #}
          {% set gamma = ((((a * T) / (b + T)) + (RH / 100)) | log) %}
          {# Calculate dew point in Celsius using the Magnus formula #}
          {% set dpC = (b * gamma) / (a - gamma) %}
          {# Convert dew point back to Fahrenheit and round to 1 decimal place #}
          {{ ((dpC * 9 / 5) + 32) | round(1) }}

  - sensor:
      - name: Perceived Indoor Humidity
        unique_id: perceived_indoor_humidity_description
        state: >
          {% set dp = states('sensor.indoor_dew_point') | float(-100) %}
          {% if dp >= 75 %}
            Oppressive
          {% elif dp >= 70 %}
            Uncomfortable
          {% elif dp >= 65 %}
            Muggy
          {% elif dp >= 60 %}
            Noticeable
          {% elif dp >= 55 %}
            Comfortable
          {% elif dp >= 50 %}
            Dry
          {% elif dp >= 45 %}
            Extremely Comfortable
          {% else %}
            Unknown
          {% endif %}

  - binary_sensor:
      - name: "Upstairs HVAC Active"
        unique_id: upstairs_hvac_active
        state: >
          {{ state_attr('climate.upstairs', 'hvac_action')
               in ['cooling', 'heating'] }}
      - name: "Downstairs HVAC Active"
        unique_id: downstairs_hvac_active
        state: >
          {{ state_attr('climate.downstairs', 'hvac_action')
               in ['cooling', 'heating'] }}

sensor:
  ## Duty-cycle (% of current hour the system is ON)
  - platform: history_stats
    name: Upstairs HVAC Duty Cycle Hourly
    entity_id: binary_sensor.upstairs_hvac_active
    state: "on"
    type: ratio
    start: "{{ now().replace(minute=0, second=0, microsecond=0) }}"
    duration: { hours: 1 }

  - platform: history_stats
    name: Downstairs HVAC Duty Cycle Hourly
    entity_id: binary_sensor.downstairs_hvac_active
    state: "on"
    type: ratio
    start: "{{ now().replace(minute=0, second=0, microsecond=0) }}"
    duration: { hours: 1 }

  ## Runtime (hours so far today)
  - platform: history_stats
    name: Upstairs HVAC Runtime Daily
    entity_id: binary_sensor.upstairs_hvac_active
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    duration: { hours: 24 }

  - platform: history_stats
    name: Downstairs HVAC Runtime Daily
    entity_id: binary_sensor.downstairs_hvac_active
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    duration: { hours: 24 }

automation:
  - alias: upstairs heat
    id: 052a2e46-33e4-4964-8da4-42609ca7e683
    trigger:
      platform: numeric_state
      entity_id: sensor.upstairs_thermostat_air_temperature
      below: 67
      for:
        minutes: 3
    conditions: >-
      {{ not is_state('climate.upstairs', 'heat') }}
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: heat
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs AC
    id: c66cded8-2a60-4dd4-96cc-677ff080934c
    trigger:
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 74
        for:
          minutes: 3
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 75
    conditions: >-
      {{ not is_state('climate.upstairs', 'cool') }}
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 74

  - alias: upstairs reading
    id: f9784a98-1586-4f2f-b9fe-129bee235ac5
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Reading
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs sleeping
    id: de717eac-9b51-4f6e-b636-9c8ddcd7e610
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Sleeping
    action:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.upstairs
          hvac_mode: cool
      - delay:
          seconds: 3
      - service: climate.set_temperature
        data:
          entity_id: climate.upstairs
          temperature: 69

  - alias: upstairs morning climate reset
    id: 16456902-c3b2-44ab-8765-454eab93d4b3
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Morning
    action:
      - service: climate.set_preset_mode
        entity_id: climate.upstairs
        data:
          preset_mode: home

  - alias: notify when leak sensor trips
    id: 85023ab0-13e5-4b4a-aba1-3e7d58973ad1
    trigger:
      platform: state
      entity_id: binary_sensor.leak_sensor_water_alarm_water_leak_detected
      from: "off"
      to: "on"
    action:
      - service: notify.iphones
        data:
          message: leak sensor detected a leak

  - alias: notify us when the downstairs climate current_temperature goes above setpoint in cool mode
    id: 1b2b0b5e-5b0a-4b0e-8b0a-2b0b5e5b0a4b
    trigger:
      platform: template
      value_template: |
        {{
          state_attr('climate.downstairs', 'hvac_action') == 'cooling' and
          state_attr('climate.downstairs', 'current_temperature') > state_attr('climate.downstairs', 'temperature')
        }}
    condition:
      condition: template
      value_template: "{{ state_attr('climate.downstairs', 'hvac_action') == 'cooling' }}"
    action:
      - service: notify.iphones
        data:
          message: >
            downstairs AC isn't keeping up.
            Current temp is {{ state_attr('climate.downstairs', 'current_temperature') }}
            and target temp is {{ state_attr('climate.downstairs', 'temperature') }}.

  - alias: notify us when downstairs climate is idle
    id: 59b0a151-122a-46dc-81bd-fd099fba0018
    trigger:
      platform: state
      entity_id: climate.downstairs
      to: "idle"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ state_attr('climate.downstairs', 'current_temperature') > state_attr('climate.downstairs', 'temperature') }}"
        - condition: template
          value_template: "{{ state_attr('climate.upstairs', 'hvac_action') == 'cooling' }}"
    action:
      - service: notify.iphones
        data:
          message: >
            downstairs AC has given up.
            Current temp is {{ state_attr('climate.downstairs', 'current_temperature') }}
            and target temp is {{ state_attr('climate.downstairs', 'temperature') }}.
