sensor:
  - name: config_branch
    platform: command_line
    command: "tail -n 1 /config/.git/logs/HEAD | rev | cut -f 1 -d \\/ | rev"
  - name: config_sha
    platform: command_line
    command: "tail -n 1 /config/.git/logs/HEAD | awk '{print $2'}"
  - name: latest_deployment_sha
    platform: command_line
    command: "curl -s -H \"Accept: application/vnd.github.ant-man-preview+json\" \"https://api.github.com/repos/jnewland/ha-config/deployments?environment=production\" | jq -r '.[0].sha'"

script:
  deploy:
    sequence:
    - service: shell_command.deploy

shell_command:
  deploy: /bin/bash ./script/deploy {{ sha }}
