sensor:
  - name: config_sha
    platform: command_line
    command: "tail -n 1 /config/.git/logs/HEAD | awk '{print $2'}"
  - name: latest_deployment_sha
    platform: command_line
    scan_interval: 90
    command: >
      curl
      -s
      -H "Accept: application/vnd.github.ant-man-preview+json"
      "https://api.github.com/repos/jnewland/ha-config/deployments?environment=production" |
      jq -r '.[0].sha'

script:
  deploy:
    sequence:
    - service: notify.slack
      data:
        title: ':shipit:'
        message: 'https://github.com/jnewland/ha-config/commit/{{ sha }}/checks'
    - service: shell_command.deploy
      data:
          sha: "{{ sha }}"

shell_command:
  deploy: /bin/bash ./script/deploy {{ sha }}

automation:
- alias: Deploy latest deployment
  id: ef2019dd-0eda-437e-a8b1-b5860e262a7e
  trigger:
    platform: state
    entity_id: sensor.latest_deployment_sha
  action:
    service: script.deploy
    data:
      sha: >
        {{ states('sensor.latest_deployment_sha') }}
