sensor:
  - name: config_sha
    platform: command_line
    command: "tail -n 1 /config/.git/logs/HEAD | awk '{print $2'}"
  - name: latest_deployment_sha
    platform: command_line
    scan_interval: 90
    command: >
      curl
      -s
      -H "Accept: application/vnd.github.ant-man-preview+json"
      "https://api.github.com/repos/jnewland/ha-config/deployments?environment=production" |
      jq -r '.[0].sha'

shell_command:
  deploy: /bin/bash ./script/deploy {{ sha }}

automation:
  - alias: Deploy latest deployment
    id: ef2019dd-0eda-437e-a8b1-b5860e262a7e
    trigger:
      platform: state
      entity_id: sensor.latest_deployment_sha
    action:
      - service: notify.slack
        data:
          message: ":rocket: Deploying https://github.com/jnewland/ha-config/commit/{{ states('sensor.latest_deployment_sha') }}/checks ..."
      - service: shell_command.deploy
        data:
          sha: >
            {{ states('sensor.latest_deployment_sha') }}
      - service: homeassistant.reload_all

  - alias: Announce deployment success
    id: 313a3fa3-a1b1-45fd-b739-71b7f8010c54
    trigger:
      platform: state
      entity_id: sensor.config_sha
    action:
      - service: notify.slack
        data:
          message: ":octocat: Config loaded from https://github.com/jnewland/ha-config/commit/{{ states('sensor.config_sha') }}"
