command_line:
  - sensor:
      name: Config SHA
      unique_id: 39e7636e-c767-4787-b497-4ef7adfdf49c
      command: "tail -n 1 /config/.git/logs/HEAD | awk '{print $2'}"

  - sensor:
      name: Latest Deployment SHA
      unique_id: 1f3312ec-3976-43a6-afdc-88720472a96d
      scan_interval: 90
      command: |
        curl \
        -s \
        -H "Accept: application/vnd.github.ant-man-preview+json" \
        "https://api.github.com/repos/jnewland/ha-config/deployments?environment=production" | \
        jq -r '.[0].sha'

shell_command:
  deploy: /bin/bash ./script/deploy {{ sha }}

automation:
  - alias: Deploy latest deployment
    id: ef2019dd-0eda-437e-a8b1-b5860e262a7e
    trigger:
      - platform: state
        entity_id: sensor.latest_deployment_sha
      - platform: state
        entity_id: automation.deploy_latest_deployment
        to: "on"
    condition: |
      {{ has_value('sensor.latest_deployment_sha') }}
    action:
      - service: notify.slack
        data:
          message: ":rocket: Deploying https://github.com/jnewland/ha-config/commit/{{ states('sensor.latest_deployment_sha') }}/checks ..."
      - service: shell_command.deploy
        data:
          sha: >
            {{ states('sensor.latest_deployment_sha') }}
      - service: homeassistant.restart

  - alias: Announce deployment success
    id: 313a3fa3-a1b1-45fd-b739-71b7f8010c54
    trigger:
      platform: state
      entity_id: sensor.config_sha
    condition: |
      {{ has_value('sensor.config_sha') }}
    action:
      - service: notify.slack
        data:
          message: "@jnewland :octocat: Config loaded from https://github.com/jnewland/ha-config/commit/{{ states('sensor.config_sha') }}"

  - alias: shutdown
    id: 2783965d-f361-41da-99eb-02a4241fdaf5
    trigger:
      platform: event
      event_type: homeassistant_stop
    action:
      service: script.turn_on
      entity_id: script.shutdown
