command_line:
  - sensor:
      name: Config SHA
      unique_id: 39e7636e-c767-4787-b497-4ef7adfdf49c
      command: "tail -n 1 /config/.git/logs/HEAD | awk '{print $2'}"

  - sensor:
      name: Latest Deployment SHA
      unique_id: 1f3312ec-3976-43a6-afdc-88720472a96d
      scan_interval: 90
      command: |
        curl \
        -s \
        -H "Accept: application/vnd.github.ant-man-preview+json" \
        "https://api.github.com/repos/jnewland/ha-config/deployments?environment=production" | \
        jq -r '.[0].sha'

shell_command:
  deploy: /bin/bash ./script/deploy {{ sha }}

automation:
  - alias: Deploy latest deployment
    id: ef2019dd-0eda-437e-a8b1-b5860e262a7e
    trigger:
      - platform: state
        entity_id: sensor.latest_deployment_sha
      - platform: state
        entity_id: automation.deploy_latest_deployment
        to: "on"
    condition: |
      {{
        has_value('sensor.latest_deployment_sha') and
        has_value('sensor.config_sha') and
        states('sensor.config_sha') != states('sensor.latest_deployment_sha')
      }}
    action:
      - service: shell_command.deploy
        data:
          sha: >
            {{ states('sensor.latest_deployment_sha') }}
      - service: homeassistant.restart
