homeassistant:
  customize:
    counter.errors:
      unit_of_measurement: errors

automation:
- alias: Count Errors
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
  action:
    service: counter.increment
    entity_id: counter.errors

counter:
  errors:
    name: Errors
    icon: mdi:alert