mqtt:
  - sensor:
      state_topic: "frigate/great_room/audio/dBFS"
      unit_of_measurement: dB
      name: "Great Room Audio dBFS"
  - sensor:
      state_topic: "frigate/great_room/audio/rms"
      unit_of_measurement: V
      name: "Great Room Audio RMS"

  - binary_sensor:
      state_topic: "frigate/great_room/audio/bark"
      name: "Great Room Audio Bark"
  - binary_sensor:
      state_topic: "frigate/great_room/audio/speech"
      name: "Great Room Audio Speech"
  - binary_sensor:
      state_topic: "frigate/great_room/audio/smoke_detector"
      name: "Great Room Audio Smoke Detector"
  - binary_sensor:
      state_topic: "frigate/great_room/audio/fire_alarm"
      name: "Great Room Audio Fire Alarm"
  - binary_sensor:
      state_topic: "frigate/great_room/audio/doorbell"
      name: "Great Room Audio Doorbell"

  - sensor:
      state_topic: "frigate/front_door/audio/dBFS"
      unit_of_measurement: dB
      name: "Front Door Audio dBFS"
  - sensor:
      state_topic: "frigate/front_door/audio/rms"
      unit_of_measurement: V
      name: "Front Door Audio RMS"

  - binary_sensor:
      state_topic: "frigate/front_door/audio/bark"
      name: "Front Door Audio Bark"
  - binary_sensor:
      state_topic: "frigate/front_door/audio/speech"
      name: "Front Door Audio Speech"
  - binary_sensor:
      state_topic: "frigate/front_door/audio/smoke_detector"
      name: "Front Door Audio Smoke Detector"
  - binary_sensor:
      state_topic: "frigate/front_door/audio/fire_alarm"
      name: "Front Door Audio Fire Alarm"
  - binary_sensor:
      state_topic: "frigate/front_door/audio/doorbell"
      name: "Front Door Audio Doorbell"

automation:
  - alias: Notify about camera failures
    id: c39da746-6928-4ff9-9fe0-0c09e5e67fae
    mode: parallel
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.ac_camera_fps
          - sensor.atrium_camera_fps
          - sensor.back_porch_camera_fps
          - sensor.front_door_camera_fps
          - sensor.front_yard_left_camera_fps
          - sensor.front_yard_right_camera_fps
          - sensor.garage_camera_fps
          - sensor.gate_camera_fps
          - sensor.great_room_camera_fps
          - sensor.veggiecam_camera_fps
          - sensor.pergola_camera_fps
          - sensor.fountain_camera_fps
        below: 1
        for:
          minutes: 2
    action:
      - service: persistent_notification.create
        data:
          message: >
            {{ trigger.to_state.name }} too low for {{ trigger.for }}!
          notification_id: >
            {{ trigger.entity_id }}_low
  - alias: Dismiss camera failure notifications
    id: b9c16063-bd35-4c1d-834f-6a1cd4bf1892
    mode: parallel
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.ac_camera_fps
          - sensor.atrium_camera_fps
          - sensor.back_porch_camera_fps
          - sensor.front_door_camera_fps
          - sensor.front_yard_left_camera_fps
          - sensor.front_yard_right_camera_fps
          - sensor.garage_camera_fps
          - sensor.gate_camera_fps
          - sensor.great_room_camera_fps
          - sensor.veggiecam_camera_fps
          - sensor.pergola_camera_fps
          - sensor.fountain_camera_fps
        below: 6
        above: 4
        for:
          minutes: 2
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: >
            {{ trigger.entity_id }}_low

  - alias: Post frigate images during events
    mode: parallel
    id: e4d0a9e9-b403-48dc-80d3-e3c750ad0cb8
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['end_time'] is none }}"
    action:
      - service: notify.slack
        data:
          title: |
            {{ trigger.payload_json["after"]["camera"] }}
          message: |
            {{ trigger.payload_json["after"]["label"] }}
          data:
            file:
              url: |
                {{ states('input_text.external_url') }}/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/thumbnail.jpg

  - alias: Post frigate clips at end of events
    mode: parallel
    id: fe6ff468-bf79-4dfe-8231-ab3f349a9b33
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['end_time'] is not none }}"
    action:
      - delay:
          # clip contains 5s after event end, needs to process a bit. give it some time
          seconds: 30
      - service: notify.slack
        data:
          title: |
            {{ trigger.payload_json["after"]["camera"] }}
          message: |
            {{ trigger.payload_json["after"]["label"] }} event has ended
          data:
            file:
              url: |
                {{ states('input_text.external_url') }}/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/{{ trigger.payload_json["after"]["camera"] }}/clip.mp4

  - alias: Notify when person detected in front yard
    mode: single
    id: 35b6ace2-2cd3-46a1-9477-c044d11336b5
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
      - "{{ trigger.payload_json['after']['camera'] in ['front_yard_left', 'front_yard_right', 'front_door', 'pergola'] }}"
      - condition: or
        conditions:
          - "{{ trigger.payload_json['type'] == 'new' }}"
          - "{{ trigger.payload_json['before']['entered_zones'] | length == 0 }}"
          - "{{ trigger.payload_json['after']['end_time'] is not none }}"
    action:
      - service: script.ack
        data:
          service: homeassistant.turn_off
          entity_id: automation.notify_when_person_detected_in_front_yard
          message: >-
            {{ trigger.payload_json['after']['label'] }}
            {{ 'event ended' if trigger.payload_json['after']['end_time'] is not none else 'detected' }}
            on {{ trigger.payload_json['after']['camera'] }}.
            Disable {{ trigger.payload_json['after']['label'] }} notifications?
          tag: >-
            {{ trigger.payload_json['after']['label'] }}-{{ trigger.payload_json['after']['camera'] }}
          confirmation_message: >-
            disabled {{ trigger.payload_json['after']['label'] }} notifications.
