mqtt:
    - sensor:
          state_topic: "frigate/great_room/audio/dBFS"
          unit_of_measurement: dB
          name: "Great Room Audio dBFS"
    - sensor:
          state_topic: "frigate/great_room/audio/rms"
          unit_of_measurement: V
          name: "Great Room Audio RMS"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/whimper_dog"
          name: "Great Room Audio Whimper Dog"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/growling"
          name: "Great Room Audio Growling"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/bow-wow"
          name: "Great Room Audio Bow Wow"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/howl"
          name: "Great Room Audio Howl"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/yip"
          name: "Great Room Audio Yip"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/bark"
          name: "Great Room Audio Bark"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/dog"
          name: "Great Room Audio Dog"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/pets"
          name: "Great Room Audio Pets"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/animal"
          name: "Great Room Audio Animal"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/smoke_detector"
          name: "Great Room Audio Smoke Detector"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/fire_alarm"
          name: "Great Room Audio Fire Alarm"
    - binary_sensor:
          state_topic: "frigate/great_room/audio/doorbell"
          name: "Great Room Audio Doorbell"
    - binary_sensor:
          state_topic: "frigate/front_door/audio/smoke_detector"
          name: "Front Door Audio Smoke Detector"
    - binary_sensor:
          state_topic: "frigate/front_door/audio/fire_alarm"
          name: "Front Door Audio Fire Alarm"
    - binary_sensor:
          state_topic: "frigate/front_door/audio/doorbell"
          name: "Front Door Audio Doorbell"

binary_sensor:
    - platform: template
      sensors:
          great_room_audio_detected:
              friendly_name: Great Room Audio Detected
              device_class: sound
              value_template: >
                  {{ states('binary_sensor.great_room_audio_whimper_dog') == 'on' or
                     states('binary_sensor.great_room_audio_growling') == 'on' or
                     states('binary_sensor.great_room_audio_bow_wow') == 'on' or
                     states('binary_sensor.great_room_audio_howl') == 'on' or
                     states('binary_sensor.great_room_audio_yip') == 'on' or
                     states('binary_sensor.great_room_audio_bark') == 'on' or
                     states('binary_sensor.great_room_audio_dog') == 'on' or
                     states('binary_sensor.great_room_audio_pets') == 'on' or
                     states('binary_sensor.great_room_audio_animal') == 'on' or
                     states('binary_sensor.great_room_audio_smoke_detector') == 'on' or
                     states('binary_sensor.great_room_audio_fire_alarm') == 'on' or
                     states('binary_sensor.great_room_audio_doorbell') == 'on'
                  }}

sensor:
    - platform: template
      sensors:
          great_room_audio_reason:
              friendly_name: Great Room Audio Reason
              value_template: >
                  {% if is_state('binary_sensor.great_room_audio_whimper_dog', 'on') %}
                    whimper dog
                  {% elif is_state('binary_sensor.great_room_audio_growling', 'on') %}
                    growling
                  {% elif is_state('binary_sensor.great_room_audio_bow_wow', 'on') %}
                    bow wow
                  {% elif is_state('binary_sensor.great_room_audio_howl', 'on') %}
                    howl
                  {% elif is_state('binary_sensor.great_room_audio_yip', 'on') %}
                    yip
                  {% elif is_state('binary_sensor.great_room_audio_bark', 'on') %}
                    bark
                  {% elif is_state('binary_sensor.great_room_audio_dog', 'on') %}
                    dog
                  {% elif is_state('binary_sensor.great_room_audio_pets', 'on') %}
                    pets
                  {% elif is_state('binary_sensor.great_room_audio_animal', 'on') %}
                    animal
                  {% elif is_state('binary_sensor.great_room_audio_smoke_detector', 'on') %}
                    smoke detector
                  {% elif is_state('binary_sensor.great_room_audio_fire_alarm', 'on') %}
                    fire alarm
                  {% elif is_state('binary_sensor.great_room_audio_doorbell', 'on') %}
                    doorbell
                  {% else %}
                    unknown
                  {% endif %}

automation:
    - alias: Notify about camera failures
      id: c39da746-6928-4ff9-9fe0-0c09e5e67fae
      mode: parallel
      trigger:
          - platform: numeric_state
            entity_id:
                - sensor.ac_camera_fps
                - sensor.atrium_camera_fps
                - sensor.back_porch_camera_fps
                - sensor.front_door_camera_fps
                - sensor.front_yard_left_camera_fps
                - sensor.garage_camera_fps
                - sensor.gate_camera_fps
                # - sensor.great_room_camera_fps
                - sensor.veggiecam_camera_fps
                - sensor.pergola_camera_fps
                - sensor.fountain_camera_fps
            below: 1
            for:
                minutes: 2
      action:
          - service: persistent_notification.create
            data:
                message: >
                    {{ trigger.to_state.name }} too low for {{ trigger.for }}!
                notification_id: >
                    {{ trigger.entity_id }}_low
    - alias: Dismiss camera failure notifications
      id: b9c16063-bd35-4c1d-834f-6a1cd4bf1892
      mode: parallel
      trigger:
          - platform: numeric_state
            entity_id:
                - sensor.ac_camera_fps
                - sensor.atrium_camera_fps
                - sensor.back_porch_camera_fps
                - sensor.front_door_camera_fps
                - sensor.front_yard_left_camera_fps
                - sensor.garage_camera_fps
                - sensor.gate_camera_fps
                - sensor.great_room_camera_fps
                - sensor.veggiecam_camera_fps
                - sensor.pergola_camera_fps
                - sensor.fountain_camera_fps
            below: 6
            above: 4
            for:
                minutes: 2
      action:
          - service: persistent_notification.dismiss
            data:
                notification_id: >
                    {{ trigger.entity_id }}_low

    - alias: Reboot unreliable great room camera automatically
      id: f14e2300-ca01-4f4e-91cd-b3611c90634b
      mode: parallel
      trigger:
          - platform: numeric_state
            entity_id:
                - sensor.great_room_camera_fps
            below: 5
            for:
                minutes: 3
      action:
          - service: switch.turn_off
            entity_id: switch.great_room_camera
          - delay:
                seconds: 10
          - service: switch.turn_on
            entity_id: switch.great_room_camera

    - alias: Post frigate images during events
      mode: parallel
      id: e4d0a9e9-b403-48dc-80d3-e3c750ad0cb8
      trigger:
          platform: mqtt
          topic: frigate/events
      condition:
          - "{{ trigger.payload_json['after']['end_time'] is none }}"
      action:
          - service: notify.slack
            data:
                title: |
                    {{ trigger.payload_json["after"]["camera"] }}
                message: |
                    {{ trigger.payload_json["after"]["label"] }}
                data:
                    file:
                        url: |
                            {{ states('input_text.external_url') }}/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/thumbnail.jpg

    - alias: Post frigate clips at end of events
      mode: parallel
      id: fe6ff468-bf79-4dfe-8231-ab3f349a9b33
      trigger:
          platform: mqtt
          topic: frigate/events
      condition:
          - "{{ trigger.payload_json['after']['end_time'] is not none }}"
      action:
          - delay:
                # clip contains 5s after event end, needs to process a bit. give it some time
                seconds: 30
          - service: notify.slack
            data:
                title: |
                    {{ trigger.payload_json["after"]["camera"] }}
                message: |
                    {{ trigger.payload_json["after"]["label"] }} event has ended
                data:
                    file:
                        url: |
                            {{ states('input_text.external_url') }}/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/{{ trigger.payload_json["after"]["camera"] }}/clip.mp4

    - alias: Notify when person detected in front yard
      mode: single
      id: 35b6ace2-2cd3-46a1-9477-c044d11336b5
      trigger:
          platform: mqtt
          topic: frigate/events
      condition:
          - "{{ trigger.payload_json['after']['label'] == 'person' }}"
          - "{{ trigger.payload_json['after']['camera'] in ['front_yard_left', 'front_door', 'pergola'] }}"
      action:
          - service: notify.iphones
            data:
                message: they're here!
                data:
                    push:
                        category: camera
                    entity_id: |
                        camera.{{ trigger.payload_json['after']['camera'] }}
                    attachment:
                        url: |
                            {{ states('input_text.external_url') }}/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/thumbnail.jpg
                        content-type: jpeg
                        hide-thumbnail: false
          - service: automation.turn_off
            entity_id: automation.notify_when_person_detected_in_front_yard
