homeassistant:
  customize:
    binary_sensor.front_gate_access_control_window_door_is_open:
      device_class: opening
      icon: mdi:gate
automation:
  - alias: Gate Bell
    id: c228fcbc-a5ea-4d1f-8094-a884be31e362
    trigger:
      platform: state
      entity_id: binary_sensor.front_gate_access_control_window_door_is_open
      to: "on"
    action:
      - service: notify.iphones
        data:
          message: the front gate just opened!
          data:
            push:
              category: camera
            entity_id: camera.front_door
            attachment:
              url: |
                {{ states('input_text.external_url') }}{{ states.camera.front_door.attributes.entity_picture }}
              content-type: jpeg
              hide-thumbnail: false
      - service: script.notify_with_lights
      - service: notify.tidbyt_once
        data:
          message: The front gate just opened!
      - service: notify.slack
        data:
          title: ":camera_with_flash:"
          message: The front gate just opened!
          data:
            file:
              url: |
                {{ states('input_text.frigate_url') }}/api/front_door/latest.jpg
      - service: script.notify_all_channels
        data:
          message: the front gate just opened

  - alias: Gate open warning
    id: 3b46434a-487b-40ad-a678-24ac2c1d7d01
    trigger:
      platform: state
      entity_id: binary_sensor.front_gate_access_control_window_door_is_open
      to: "on"
      for:
        minutes: 3
    action:
      - service: notify.iphones
        data:
          message: the front gate has been open for a few minutes
          data:
            push:
              interruption-level: time-sensitive
              category: camera
            entity_id: camera.front_door
            attachment:
              url: |
                {{ states('input_text.external_url') }}{{ states.camera.front_door.attributes.entity_picture }}
              content-type: jpeg
              hide-thumbnail: false
