automation:
  - alias: Keep the garage door closed
    id: 9b4c10ce-0960-4176-9bd5-e670c75dfc0d
    trigger:
      platform: state
      entity_id: cover.garage
      to: open
      for:
        minutes: 5
    action:
    - service: script.ask_about_turning_on
      data:
        entity_id: script.close_garage
        message: "The garage has been open for a bit. Close it up?"
        confirmation_message: closed the garage
  - alias: Keep the garage door locked
    id: 85761fbe-a404-4b09-bce0-83acae8ce018
    trigger:
      platform: state
      entity_id: binary_sensor.garage_occupancy
      to: 'off'
      for:
        minutes: 30
    condition:
      condition: state
      entity_id: lock.garage
      state: unlocked
    action:
    - service: script.ask_about_turning_on
      data:
        entity_id: script.lock_garage
        message: "The garage door has been unlocked for a bit. Lock it up?"
        confirmation_message: locked the garage door
script:
  close_garage:
    sequence:
    - service: python_script.close_if_open
      entity_id: cover.garage
  lock_garage:
    sequence:
      - service: lock.lock
        data:
          entity_id: lock.garage