automation:
  - alias: Keep covers closed
    id: 9b4c10ce-0960-4176-9bd5-e670c75dfc0d
    trigger:
      platform: state
      entity_id:
        - cover.garage
        - cover.gate
      to: open
      for:
        minutes: 5
    action:
    - service: script.ack
      data:
        service: cover.close_cover
        entity_id: "{{ trigger.entity_id }}"
        message: >
          Close the {{ trigger.to_state.name }}?
        confirmation_message: >
          closed the {{ trigger.to_state.name }}.
  - alias: Cover notification clear
    id: f883428d-555d-495c-865d-63121af76939
    trigger:
      platform: state
      entity_id:
        - cover.garage
        - cover.gate
      to: closed
      for:
        seconds: 5
    action:
      - service: notify.iphones
        data:
          message: "clear_notification"
          data:
            tag: "{{ trigger.entity_id }}"

  - alias: Unlock garage door lock with tag
    id: 79bc5e96-faf8-4a56-85d4-2a5537134be0
    trigger:
      platform: event
      event_type: tag_scanned
      event_data:
        tag_id: e847f665-dbaa-4458-9d48-433964d3da29
    condition:
      condition: state
      entity_id: lock.garage
      state: locked
    action:
    - service: lock.unlock
      data:
        entity_id: lock.garage
  - alias: Lock garage door lock with tag
    id: 64664fb7-cc21-4dc9-a05f-399e4e6caec4
    trigger:
      platform: event
      event_type: tag_scanned
      event_data:
        tag_id: e847f665-dbaa-4458-9d48-433964d3da29
    condition:
      condition: state
      entity_id: lock.garage
      state: unlocked
    action:
    - service: lock.lock
      data:
        entity_id: lock.garage
script:
  close_garage:
    sequence:
    - service: python_script.close_if_open
      entity_id: cover.garage