sensor:
  - platform: bhyve

switch:
  - platform: bhyve

plant:
  # https://open.plantbook.io/browse-db
  lime_tree:
    name: lime tree
    species: citrus latifolia
    image: https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/citrus%20latifolia.jpg
    sensors:
      moisture: sensor.lime_tree_moisture
      temperature: sensor.lime_tree_temperature
      conductivity: sensor.lime_tree_soil_conductivity
      brightness: sensowr.lime_tree_light
    # appears that https://github.com/Olen/homeassistant-plant doesn't do C to F yet
    min_temperature: 41
    max_temperature: 95
  bamboo:
    name: bamboo
    species: bamboo
    image: https://objectstorage.ap-sydney-1.oraclecloud.com/n/sdyd5yr3jypo/b/plant-img/o/bamboo.jpg
    sensors:
      moisture: sensor.bamboo_moisture
      temperature: sensor.bamboo_temperature
      conductivity: sensor.bamboo_soil_conductivity
      brightness: sensowr.bamboo_light
    # appears that https://github.com/Olen/homeassistant-plant doesn't do C to F yet
    min_temperature: 41
    max_temperature: 89.6

automation:
- alias: BHyve next watering & rain delay finishing updater
  trigger:
    - platform: state
      entity_id: switch.patio_planters, switch.patio_irrigation_rain_delay
    - platform: homeassistant
      event: start
  action:
    - service: python_script.bhyve_next_watering
      data:
        entity_id: switch.patio_planters