homeassistant:
  customize:
    binary_sensor.front_gate:
      device_class: opening
      icon: mdi:gate
automation:
  - alias: Front gate Bell
    id: c228fcbc-a5ea-4d1f-8094-a884be31e362
    trigger:
      platform: state
      entity_id: binary_sensor.front_gate
      to: "on"
    action:
      - service: notify.iphones
        data:
          message: the front gate just opened!
          data:
            tag: front_gate
            push:
              category: camera
            entity_id: camera.front_door_medium
            attachment:
              url: |
                {{ states('input_text.external_url') }}{{ states.camera.front_door_medium.attributes.entity_picture }}
              content-type: jpeg
              hide-thumbnail: false
      - service: script.notify_with_lights
      - service: notify.tidbyt_once
        data:
          message: The front gate just opened!
      - service: script.notify_all_channels
        data:
          message: the front gate just opened

  - alias: Front gate open warning
    id: 3b46434a-487b-40ad-a678-24ac2c1d7d01
    trigger:
      platform: state
      entity_id: binary_sensor.front_gate
      to: "on"
      for:
        minutes: 1
    action:
      - service: notify.iphones
        data:
          message: the front gate has been open for a minute
          data:
            tag: front_gate
            push:
              interruption-level: time-sensitive
              category: camera
            entity_id: camera.front_door_medium
            attachment:
              url: |
                {{ states('input_text.external_url') }}{{ states.camera.front_door_medium.attributes.entity_picture }}
              content-type: jpeg
              hide-thumbnail: false

  - alias: Driveway gate bell
    id: d42e9c8d-95c9-4a90-8fdd-1034c4923b40
    trigger:
      platform: state
      entity_id: sensor.gate_driveway_gate_classification
      to: "open"
    action:
      - service: notify.iphones
        data:
          message: the driveway gate just opened!
          data:
            tag: driveway_gate
            push:
              category: camera
            entity_id: camera.gate_medium
            attachment:
              url: |
                {{ states('input_text.external_url') }}{{ states.camera.gate_medium.attributes.entity_picture }}
              content-type: jpeg
              hide-thumbnail: false
      - service: script.notify_with_lights
      - service: notify.tidbyt_once
        data:
          message: The driveway gate just opened!
      - service: script.notify_all_channels
        data:
          message: the driveway gate just opened
