automation:
  - alias: Disable alarm when we unlock various doors
    id: c44abe39-a4ca-4bcf-8092-fd9d81330585
    trigger:
      - platform: state
        entity_id: lock.front_door
        to: "unlocked"
      - platform: state
        entity_id: lock.garage
        to: "unlocked"

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: armed_home
    action:
      - repeat:
          until: |
            {{ is_state('alarm_control_panel.alarm', 'disarmed') }}
          sequence:
            - service: alarm_control_panel.alarm_disarm
              entity_id: alarm_control_panel.alarm
            - delay: 5
