group:
  great_room_speakers:
    icon: mdi:speaker
    entities:
      - media_player.living_speakers
      - media_player.kitchen_speakers

automation:
  - alias: Turn on related speakers
    mode: parallel
    id: 3ba3e202-4fa0-4f94-8f7d-6cf2aeb674c3
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.domain == "binary_sensor" and
          is_state(trigger.event.data.new_state.entity_id, "on") and
          trigger.event.data.new_state.attributes.speaker_entity is defined
        }}
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: |
            {{ trigger.event.data.new_state.attributes.speaker_entity }}
  - alias: Turn off related speakers
    mode: parallel
    id: d55dd41d-cd36-4544-8ed1-58b1578ec0ce
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.domain == "binary_sensor" and
          is_state(trigger.event.data.new_state.entity_id, "off") and
          trigger.event.data.new_state.attributes.speaker_entity is defined
        }}
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: |
            {{ trigger.event.data.new_state.attributes.speaker_entity }}
  - alias: Group sonos speakers
    mode: parallel
    id: fe8d95bc-f94f-4454-83b0-527b9d403107
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.domain == "binary_sensor" and
          is_state(trigger.event.data.new_state.entity_id, "on") and
          trigger.event.data.new_state.attributes.media_player_group_members is defined and
          trigger.event.data.new_state.attributes.media_player_entity_id is defined and
          trigger.event.data.new_state.attributes.media_player_group_members not in state_attr(trigger.event.data.new_state.attributes.media_player_entity_id, 'group_members') and
          ( is_state(trigger.event.data.new_state.attributes.media_player_group_members, 'idle') or
            is_state(trigger.event.data.new_state.attributes.media_player_group_members, 'paused') )
        }}
    action:
      - service: media_player.join
        data:
          group_members: |
            {{ trigger.event.data.new_state.attributes.media_player_group_members }}
          entity_id: |
            {{ trigger.event.data.new_state.attributes.media_player_entity_id }}
      - service: system_log.write
        data:
          message: >
            at=media_player.join
            group_members={{ trigger.event.data.new_state.attributes.media_player_group_members }}
            entity_id={{ trigger.event.data.new_state.attributes.media_player_entity_id }}
          logger: packages.house_speakers
          level: debug
  - alias: Ungroup sonos speakers
    mode: parallel
    id: b301d317-ef17-4285-a2de-a96353d12712
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.domain == "binary_sensor" and
          is_state(trigger.event.data.new_state.entity_id, "off") and
          trigger.event.data.new_state.attributes.media_player_group_members is defined and
          trigger.event.data.new_state.attributes.media_player_entity_id is defined
        }}
    action:
    - service: media_player.unjoin
      data: {}
      target:
        entity_id: |
          {{ trigger.event.data.new_state.attributes.media_player_group_members }}
    - service: system_log.write
      data:
        message: >
          at=media_player.unjoin
          entity_id={{ trigger.event.data.new_state.attributes.media_player_group_members }}
        logger: packages.house_speakers
        level: debug
