group:
  great_room_speakers:
    icon: mdi:speaker
    entities:
      - media_player.living_speakers
      - media_player.kitchen_speakers

automation:
  - alias: Turn on related speakers
    mode: parallel
    id: 3ba3e202-4fa0-4f94-8f7d-6cf2aeb674c3
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.state != trigger.event.data.old_state.state and
          trigger.event.data.new_state.domain == "binary_sensor" and
          trigger.event.data.new_state.state == "on" and
          trigger.event.data.new_state.attributes.speaker_entity is defined
        }}
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: |
            {{ trigger.event.data.new_state.attributes.speaker_entity }}
  - alias: Turn off related speakers
    mode: parallel
    id: d55dd41d-cd36-4544-8ed1-58b1578ec0ce
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.state != trigger.event.data.old_state.state and
          trigger.event.data.new_state.domain == "binary_sensor" and
          trigger.event.data.new_state.state == "off" and
          trigger.event.data.new_state.attributes.speaker_entity is defined
        }}
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: |
            {{ trigger.event.data.new_state.attributes.speaker_entity }}
  - alias: Group sonos speakers
    mode: parallel
    id: fe8d95bc-f94f-4454-83b0-527b9d403107
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.state != trigger.event.data.old_state.state and
          trigger.event.data.new_state.domain == "binary_sensor" and
          trigger.event.data.new_state.state == "on" and
          trigger.event.data.new_state.attributes.sonos_group_master is defined and
          trigger.event.data.new_state.attributes.sonos_group_entity_id is defined and
          ( is_state(trigger.event.data.new_state.attributes.sonos_group_entity_id, 'idle') or
            is_state(trigger.event.data.new_state.attributes.sonos_group_entity_id, 'paused') )
        }}
    action:
      - service: sonos.join
        data:
          master: |
            {{ trigger.event.data.new_state.attributes.sonos_group_master }}
          entity_id: |
            {{ trigger.event.data.new_state.attributes.sonos_group_entity_id }}
  - alias: Ungroup sonos speakers
    mode: parallel
    id: b301d317-ef17-4285-a2de-a96353d12712
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.old_state != None and
          trigger.event.data.new_state.state != trigger.event.data.old_state.state and
          trigger.event.data.new_state.domain == "binary_sensor" and
          trigger.event.data.new_state.state == "off" and
          trigger.event.data.new_state.attributes.sonos_group_master is defined and
          trigger.event.data.new_state.attributes.sonos_group_entity_id is defined
        }}
    action:
    - service: sonos.unjoin
      data: {}
      target:
        entity_id: |
          {{ trigger.event.data.new_state.attributes.sonos_group_entity_id }}
