sensor:
- platform: template
  sensors:
    image_processing_summary:
      friendly_name: Image processing summary
      entity_id:
        - image_processing.atrium
        - image_processing.back_porch
        - image_processing.front_yard_left
        - image_processing.pergola
      value_template: |
        {% for state in states.image_processing if state.attributes.total_matches > 0 -%}
          {%- if loop.first %}Detected {% elif loop.last %}, and {% else %}, {% endif -%}
          {% for thing in state.attributes.summary.keys() %}{%- if loop.first %}{% elif loop.last %} & {% else %}, {% endif -%}{{thing}}{%- endfor %} on {{ state.name | lower }} camera
        {%- endfor %}

automation:
  - alias: Post doods matches to slack
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: |
            {{
              trigger.event.data.new_state.domain == "image_processing" and
              trigger.event.data.new_state.attributes.total_matches > 0
            }}
    action:
      - service: script.notify_slack_about_camera
        data_template:
          entity_id: |
            camera.doods_{{ trigger.event.data.new_state.entity_id.split('.')[1] }}
          message: |
            {% for thing in trigger.event.data.new_state.attributes.summary.keys() %}{%- if loop.first %}{% elif loop.last %} & {% else %}, {% endif -%}{{thing}}{%- endfor %}
