sensor:
- platform: template
  sensors:
    image_processing_summary:
      friendly_name: Image processing summary
      entity_id:
        - image_processing.atrium
        - image_processing.back_porch
        - image_processing.front_yard_left
        - image_processing.pergola
      value_template: |
        {% for state in states.image_processing if state.attributes.total_matches > 0 -%}
          {%- if loop.first %}Detected {% elif loop.last %}, and {% else %}, {% endif -%}
          {% for thing in state.attributes.summary.keys() %}{%- if loop.first %}{% elif loop.last %} & {% else %}, {% endif -%}{{thing}}{%- endfor %} on {{ state.name | lower }} camera
        {%- endfor %}