binary_sensor:
  # TODO
  - platform: template
    sensors:
      garage_occupancy:
        friendly_name: garage occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('sensor.garage_person')) | default(0) > 0 }}
      pergola_occupancy:
        friendly_name: pergola occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('sensor.pergola_person')) | default(0) > 0 }}
      front_yard_left_occupancy:
        friendly_name: front yard left occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('sensor.front_yard_left_person')) | default(0) > 0 }}
      back_porch_occupancy:
        friendly_name: back porch occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('sensor.back_porch_person')) | default(0) > 0 }}


automation:
  - alias: Post frigate images during events
    mode: parallel
    id: e4d0a9e9-b403-48dc-80d3-e3c750ad0cb8
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['end_time'] is none }}"
    action:
      - service: notify.slack
        data:
          title: |
            {{ trigger.payload_json["after"]["camera"] }}
          message: |
            {{ trigger.payload_json["after"]["label"] }}
          data:
            file:
              url: https://home.jnewland.com/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/thumbnail.jpg

  - alias: Post frigate clips at end of events
    mode: parallel
    id: fe6ff468-bf79-4dfe-8231-ab3f349a9b33
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['end_time'] is not none }}"
    action:
      - delay:
          # clip contains 5s after event end, needs to process a bit. give it some time
          seconds: 30
      - service: notify.slack
        data:
          title: |
            {{ trigger.payload_json["after"]["camera"] }}
          message: |
            {{ trigger.payload_json["after"]["label"] }} event has ended
          data:
            file:
              url: https://home.jnewland.com/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/{{ trigger.payload_json["after"]["camera"] }}/clip.mp4
