binary_sensor:
  # TODO
  - platform: template
    sensors:
      garage_occupancy:
        friendly_name: garage occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('image_processing.garage')) | default(0) > 0 }}
      pergola_occupancy:
        friendly_name: pergola occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('image_processing.pergola')) | default(0) > 0 }}
      front_yard_left_occupancy:
        friendly_name: front yard left occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('image_processing.front_yard_left')) | default(0) > 0 }}
      back_porch_occupancy:
        friendly_name: back porch occupancy
        device_class: occupancy
        delay_off:
          minutes: 4
        value_template: |
          {{ float(states('image_processing.back_porch')) | default(0) > 0 }}


automation:
  - alias: Post frigate matches to slack
    mode: parallel
    id: 90fe8a3d-5171-4bc0-80db-b31435b62c33
    trigger:
      platform: mqtt
      topic: frigate/events
    action:
      - service: notify.slack
        data:
          title: |
            {{trigger.payload_json["after"]["label"]}}
          message: |
            {{trigger.payload_json['after']['entered_zones']}}
          data:
            file:
              url: https://home.jnewland.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg

