automation:
  - alias: Post doods matches to slack
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: |
            {{
              trigger.event.data.new_state.domain == "image_processing" and
              trigger.event.data.new_state.attributes.total_matches > 0
            }}
    action:
      - service: script.notify_slack_about_camera
        data_template:
          entity_id: |
            camera.doods_{{ trigger.event.data.new_state.entity_id.split('.')[1] }}
          message: |
            {% for thing in trigger.event.data.new_state.attributes.summary.keys() %}{%- if loop.first %}{% elif loop.last %} & {% else %}, {% endif -%}{{thing}}{%- endfor %}
