automation:
  - alias: Notify about camera failures
    id: c39da746-6928-4ff9-9fe0-0c09e5e67fae
    mode: parallel
    trigger:
      - platform: numeric_state
        entity_id:
        - sensor.ac_camera_fps
        - sensor.atrium_camera_fps
        - sensor.back_porch_camera_fps
        - sensor.front_door_camera_fps
        - sensor.front_yard_left_camera_fps
        - sensor.garage_camera_fps
        - sensor.gate_camera_fps
        - sensor.great_room_camera_fps
        - sensor.peppers_camera_fps
        - sensor.pergola_camera_fps
        - sensor.roof_deck_camera_fps
        below: 5
        for:
          minutes: 5
    action:
      - service: persistent_notification.create
        data:
          message: >
            {{ trigger.to_state.name }} too low for {{ trigger.for }}!

  - alias: Reboot unreliable great room camera automatically
    id: f14e2300-ca01-4f4e-91cd-b3611c90634b
    mode: parallel
    trigger:
      - platform: numeric_state
        entity_id:
        - sensor.great_room_camera_fps
        below: 5
        for:
          minutes: 3
    action:
      - service: switch.turn_off
        entity_id: switch.great_room_camera
      - delay:
          seconds: 10
      - service: switch.turn_on
        entity_id: switch.great_room_camera

  - alias: Post frigate images during events
    mode: parallel
    id: e4d0a9e9-b403-48dc-80d3-e3c750ad0cb8
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['end_time'] is none }}"
    action:
      - service: notify.slack
        data:
          title: |
            {{ trigger.payload_json["after"]["camera"] }}
          message: |
            {{ trigger.payload_json["after"]["label"] }}
          data:
            file:
              url: |
                {{ states('input_text.external_url') }}/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/thumbnail.jpg

  - alias: Post frigate clips at end of events
    mode: parallel
    id: fe6ff468-bf79-4dfe-8231-ab3f349a9b33
    trigger:
      platform: mqtt
      topic: frigate/events
    condition:
      - "{{ trigger.payload_json['after']['end_time'] is not none }}"
    action:
      - delay:
          # clip contains 5s after event end, needs to process a bit. give it some time
          seconds: 30
      - service: notify.slack
        data:
          title: |
            {{ trigger.payload_json["after"]["camera"] }}
          message: |
            {{ trigger.payload_json["after"]["label"] }} event has ended
          data:
            file:
              url: |
                {{ states('input_text.external_url') }}/api/frigate/notifications/{{ trigger.payload_json["after"]["id"] }}/{{ trigger.payload_json["after"]["camera"] }}/clip.mp4
