homeassistant:
  customize:
    binary_sensor.laundry_activity:
      trigger_service: script.laundry_room
      trigger_entity_id_off: group.laundry_room

script:
  laundry_room:
    mode: parallel
    sequence:
      - service: homeassistant.turn_on
        entity_id: fan.laundry_room
      - service: light.turn_on
        data:
          entity_id: light.laundry_room
          brightness: >
            {{ int(state_attr('switch.circadian_lighting_brightness', 'brightness'), default=255) }}

group:
  laundry_room:
    entities:
      - fan.laundry_room
      - light.laundry_room

binary_sensor:
  - platform: template
    sensors:
      laundry_activity:
        friendly_name: Laundry activity
        value_template: |
          {{ 
            is_state('binary_sensor.laundry_power', 'on') or 
            is_state('binary_sensor.laundry_room_motion_detection', 'on')
          }}
      laundry_cycle:
        friendly_name: Laundry cycle
        device_class: running
        value_template: |
          {{ 
            states('sensor.laundry_electric_consumption_w') != 'unknown' and 
            float(states('sensor.laundry_electric_consumption_w'), default=0) > 10
          }}
        delay_off:
          minutes: 10

      laundry_power:
        friendly_name: Laundry power
        device_class: power
        value_template: |
          {{ 
            states('sensor.laundry_electric_consumption_w') != 'unknown' and 
            float(states('sensor.laundry_electric_consumption_w'), default=0) > 0
          }}
        delay_off:
          minutes: 30

      laundry_door:
        friendly_name: Laundry door
        device_class: door
        value_template: |
          {{ 
            states('sensor.laundry_electric_consumption_w') != 'unknown' and 
            is_state('binary_sensor.laundry', 'off') and 
            float(states('sensor.laundry_electric_consumption_w'), default=0) > 0 and
            float(states('sensor.laundry_electric_consumption_w'), default=0) < 10 
          }}

automation:
  - alias: Laundry notifications
    id: 25fad7c4-c57e-4c67-904a-69e606682ebd
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_cycle
        from: "on"
        to: "off"
    action:
      - service: script.ack
        data:
          entity_id: script.noop
          tag: laundry
          message: Time to do the laundry thing. You have a second?
          confirmation_message: is doing the laundry thing, cool.

  - alias: Clear laundry notifications
    id: e1432f38-834f-417a-b976-2bb627e06046
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_door
        from: "off"
        to: "on"
    action:
      - service: notify.iphones
        data:
          message: "clear_notification"
          data:
            tag: laundry
