sensor:
  - platform: template
    sensors:
      laundry_power:
        friendly_name: Laundry power
        unit_of_measurement: W
        entity_id:
          - switch.laundry
        value_template: |
          {{ states.switch.laundry.attributes.current_power_w }}
      laundry_energy:
        friendly_name: Laundry energy
        unit_of_measurement: kWh
        entity_id:
          - switch.laundry
        value_template: |
          {{ states.switch.laundry.attributes.current_energy_kwh }}

binary_sensor:
  - platform: template
    sensors:
      laundry:
        friendly_name: Laundry
        entity_id:
          - sensor.laundry_power
        value_template: |
          {{ float(states.sensor.laundry_power.state) | default(0) > 0 }}
        delay_off:
          minutes: 5

automation:
  - alias: Laundry notifications
    trigger:
    - platform: state
      entity_id: binary_sensor.laundry
      from: "on"
      to: "off"
    action:
      - service: script.ask_about_turning_on
        data_template:
          entity_id: script.noop
          apns_collapse_id: laundry
          message: The laundry needs attention. Did you do the laundry thing?
          confirmation_message: did the laundry thing, cool