sensor:
  - platform: template
    sensors:
      laundry_power:
        friendly_name: Laundry power
        unit_of_measurement: W
        device_class: power
        value_template: |
          {{ state_attr('switch.laundry','current_power_w') }}

binary_sensor:
  - platform: template
    sensors:
      laundry:
        friendly_name: Laundry
        device_class: power
        value_template: |
          {{ float(states.sensor.laundry_power.state | default(0)) > 0 }}
        delay_on:
          minutes: 5
        delay_off:
          minutes: 5

automation:
  - alias: Laundry notifications
    id: 25fad7c4-c57e-4c67-904a-69e606682ebd
    trigger:
    - platform: state
      entity_id: binary_sensor.laundry
      from: "on"
      to: "off"
    action:
      - service: script.ask_about_turning_on
        data:
          entity_id: script.noop
          apns_collapse_id: laundry
          message: The laundry needs attention. Did you do the laundry thing?
          confirmation_message: did the laundry thing, cool
