binary_sensor:
  - platform: template
    sensors:
      laundry:
        friendly_name: Laundry
        device_class: power
        value_template: |
          {{ 
            states('sensor.laundry_electric_consumption_w') != 'unknown' and 
            float(states('sensor.laundry_electric_consumption_w'), default=0) > 10
          }}
        delay_off:
          minutes: 8

      laundry_door:
        friendly_name: Laundry door
        device_class: door
        value_template: |
          {{ 
            states('sensor.laundry_electric_consumption_w') != 'unknown' and 
            is_state('binary_sensor.laundry', 'off') and 
            float(states('sensor.laundry_electric_consumption_w'), default=0) > 0 and
            float(states('sensor.laundry_electric_consumption_w'), default=0) < 10 
          }}

automation:
  - alias: Laundry notifications
    id: 25fad7c4-c57e-4c67-904a-69e606682ebd
    trigger:
    - platform: state
      entity_id: binary_sensor.laundry
      from: "on"
      to: "off"
    action:
      - service: script.ack
        data:
          entity_id: script.noop
          tag: laundry
          message: Time to do the laundry thing. You have a second?
          confirmation_message: is doing the laundry thing, cool.
  - alias: Clear laundry notifications
    id: e1432f38-834f-417a-b976-2bb627e06046
    trigger:
    - platform: state
      entity_id: binary_sensor.laundry_door
      from: "off"
      to: "on"
    action:
      - service: notify.iphones
        data:
          message: "clear_notification"
          data:
            tag: laundry
