# * Automations to handle binary sensors -> lights or scripts
#   * https://www.amazon.com/gp/product/B0151Z8ZQY are great sensors

# * An input number for global brightness adjustments

# * script.notify_with_lights ==>> ducks selected lights, useful as an
#   unobtrusive "hey something is happening look at your phone for more"
#   notification

homeassistant:
  customize:
    # Configure which service or entity is triggered when the sensor
    # changes state
    #
    # trigger_service: service
    # trigger_entity_id: entity_id
    # trigger_service_off: service
    # trigger_entity_id_off: entity_id

    binary_sensor.stairs_motion:
      trigger_entity_id: light.stairs
      trigger_entity_id_off: light.stairs
    binary_sensor.upstairs_motion:
      trigger_entity_id: light.stairs
      trigger_entity_id_off: light.stairs
    binary_sensor.closet_motion:
      trigger_entity_id: light.master_closet
      trigger_entity_id_off: light.master_closet
    binary_sensor.guest_hall_motion:
      trigger_entity_id: light.guest_hall
      trigger_entity_id_off: light.guest_hall
    binary_sensor.guest_bath_motion:
      trigger_entity_id: group.guest_bath_lights
      trigger_entity_id_off: group.guest_bath
      off_delay_seconds: 1800
    binary_sensor.powder_room_motion:
      trigger_entity_id: light.powder_room
      trigger_entity_id_off: group.powder_room
    binary_sensor.office_motion:
      trigger_service: script.office_lights
      trigger_entity_id_off: group.office
      off_delay_seconds: 1800
    binary_sensor.master_bath_motion:
      trigger_service: script.master_bath_lights
      trigger_entity_id_off: group.master_bath
      off_delay_seconds: 3600
    binary_sensor.master_motion:
      trigger_service: script.master_lights
      trigger_service_off: script.master_lights_off
    binary_sensor.wine_room_motion:
      trigger_entity_id: light.wine_room
      trigger_entity_id_off: light.wine_room
    binary_sensor.great_hall_motion:
      trigger_entity_id: light.great_hall
      trigger_entity_id_off: light.great_hall
    binary_sensor.garage_hall_motion:
      trigger_entity_id: light.garage_hall
      trigger_entity_id_off: light.garage_hall
    binary_sensor.music_room_motion:
      friendly_name: music room motion
      trigger_entity_id: light.music_room
      trigger_entity_id_off: light.music_room
      off_delay_seconds: 300
    binary_sensor.great_room_occupied:
      trigger_service: script.living_lights
      trigger_entity_id_off: group.great_room
    binary_sensor.pantry_motion:
      trigger_entity_id: light.pantry
      trigger_entity_id_off: light.pantry

    counter.light_automations:
      unit_of_measurement: occurances

    # fixed_brightness: int
    # TODO: min_brightness
    # notify_action: duck
    # duck_step: int | default(127)
    light.atrium:
      notify_action: duck
      fixed_brightness: 255
    light.front_porch:
      fixed_brightness: 255
    light.front_door:
      fixed_brightness: 255
    light.patio:
      fixed_brightness: 255
    light.ac:
      fixed_brightness: 255
    light.atrium_door:
      notify_action: duck
      fixed_brightness: 255
    light.garage_door:
      fixed_brightness: 255
    light.cabinets:
      fixed_brightness: 255

    light.bookshelf:
      fixed_brightness: 255
    light.bookshelf_blue:
      fixed_brightness: 0
    light.bookshelf_brightness:
      fixed_brightness: 0
    light.bookshelf_green:
      fixed_brightness: 0
    light.bookshelf_red:
      fixed_brightness: 0
    light.bookshelf_white:
      fixed_brightness: 0

    light.back_porch_fountain_lights:
      notify_action: duck
      fixed_brightness: 255
    light.back_porch_fountain_blue:
      fixed_brightness: 0
    light.back_porch_fountain_brightness:
      fixed_brightness: 0
    light.back_porch_fountain_green:
      fixed_brightness: 0
    light.back_porch_fountain_red:
      fixed_brightness: 0
    light.back_porch_fountain_white:
      fixed_brightness: 0

    light.dining_room_table:
      notify_action: duck
      duck_step: 192
    light.exersize_bike:
      notify_action: duck
    light.kitchen:
      notify_action: duck
      duck_step: 192
    light.living:
      notify_action: duck
      duck_step: 192
    light.master_bath_overhead:
      notify_action: duck
    light.master_closet:
      notify_action: duck
    light.master_mirror:
      notify_action: duck
    light.master_nook:
      notify_action: duck
    light.master_overhead:
      notify_action: duck
    light.master_patio:
      notify_action: duck
    light.master_shower:
      notify_action: duck
    light.master_toilet:
      notify_action: duck
    light.music_room:
      notify_action: duck
    light.office_chandelier:
      notify_action: duck
    light.office_desk_lamp:
      notify_action: duck
      duck_step: 192
    light.office_overhead:
      notify_action: duck
    light.pendants:
      notify_action: duck
      duck_step: 192
    light.wine_room:
      fixed_brightness: 102

automation:
  - alias: Turn on lights when motion is detected
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: |
            {{
              trigger.event.data.old_state != None and
              trigger.event.data.new_state.state != trigger.event.data.old_state.state and
              trigger.event.data.new_state.domain == "binary_sensor" and
              trigger.event.data.new_state.state == "on" and (
                trigger.event.data.new_state.attributes.trigger_service is defined or
                trigger.event.data.new_state.attributes.trigger_entity_id is defined
              )
            }}
        - condition: template
          value_template: |
            {{ states.input_select.mode.state != "Away" }}
    action:
      - service_template: |
          {{ trigger.event.data.new_state.attributes.trigger_service | default('homeassistant.turn_on') }}
        data_template:
          entity_id: |
            {{ trigger.event.data.new_state.attributes.trigger_entity_id | default('') }}
          brightness: |
            {{ trigger.event.data.new_state.attributes.fixed_brightness | default(states('input_number.brightness') | int) }}
      - service: system_log.write
        data_template:
          message: >
            at=on
            entity_id={{ trigger.event.data.entity_id }} trigger_service={{ trigger.event.data.new_state.attributes.trigger_service }} trigger_entity_id={{ trigger.event.data.new_state.attributes.trigger_entity_id }}
          logger: packages.lights
          level: info
      - service: counter.increment
        entity_id: counter.light_automations

  - alias: Turn off lights after sensors have turned off
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: |
            {{
              trigger.event.data.old_state != None and
              trigger.event.data.new_state.state != trigger.event.data.old_state.state and
              trigger.event.data.new_state.domain == "binary_sensor" and
              trigger.event.data.new_state.state == "off" and (
                trigger.event.data.new_state.attributes.trigger_service_off is defined or
                trigger.event.data.new_state.attributes.trigger_entity_id_off is defined
              )
            }}

    action:
      # Emit a custom event with a boolean indicating whether or not to delay.
      # If this works, separate automations should be possible for lights with and without delay
      # using event_data as mentioned at https://www.home-assistant.io/docs/automation/trigger/#event-trigger
      - event: lights_motion_sensor_off
        event_data_template:
          entity_id: |
            {{ trigger.event.data.entity_id }}
          delay: |
            {{ trigger.event.data.new_state.attributes.off_delay_seconds | default(0) | int != 0 }}
      - service: system_log.write
        data_template:
          message: >
            at=delay_start
            entity_id={{ trigger.event.data.entity_id }}
            delay={{ trigger.event.data.new_state.attributes.off_delay_seconds | default(0) | int }}
          logger: packages.lights
          level: info
      # An attempt at persisting some data for debugging info
      - service: python_script.set_attribute
        data_template:
          entity_id: |
            {{ trigger.event.data.entity_id }}
          attribute: off_after
          value: |
            {{ timestamp_local(as_timestamp(now()) + (trigger.event.data.new_state.attributes.off_delay_seconds | default(0) | int)) }}
      - delay: "{{ state_attr(trigger.event.data.entity_id,'off_delay_seconds') | default(0) | int | timestamp_custom('%H:%M:%S',False) }}"
      - service: system_log.write
        data_template:
          message: >
            at=delay_end
            entity_id={{ trigger.event.data.entity_id }}
          logger: packages.lights
          level: info
      - condition: template
        value_template: |
          {{
            states(trigger.event.data.entity_id) == "off" and
            as_timestamp(now()) - as_timestamp(states[trigger.event.data.new_state.domain][trigger.event.data.new_state.object_id].last_changed)
              >
            (trigger.event.data.new_state.attributes.off_delay_seconds | default(0) | int)
          }}
      - service_template: |
          {{ trigger.event.data.new_state.attributes.trigger_service_off | default('homeassistant.turn_off') }}
        data_template:
          entity_id: |
            {{ trigger.event.data.new_state.attributes.trigger_entity_id_off | default('') }}
      - service: system_log.write
        data_template:
          message: >
            at=off
            entity_id={{ trigger.event.data.entity_id }}
            trigger_service_off={{ trigger.event.data.new_state.attributes.trigger_service_off }}
            trigger_entity_id_off={{ trigger.event.data.new_state.attributes.trigger_entity_id_off }}
          logger: packages.lights
          level: info
      - service: counter.increment
        entity_id: counter.light_automations

  - alias: React to changes of the brightness slider
    trigger:
      platform: state
      entity_id: input_number.brightness
    action:
      - service: light.turn_on
        data_template:
          entity_id: |
            {%- for l in states.light if (
                not l.attributes.fixed_brightness and
                l.state == "on") -%}
              {{l.entity_id}}{% if not loop.last %}{{ ", " }}{% endif %}
            {%- endfor -%}
          brightness: |
            {{ states('input_number.brightness') | int }}
      - service: counter.increment
        entity_id: counter.light_automations

  - alias: Set lights to correct brightness when turned on
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: |
            {{
              trigger.event.data.old_state != None and
              trigger.event.data.new_state.state != trigger.event.data.old_state.state and
              trigger.event.data.new_state.domain == "light" and
              trigger.event.data.new_state.state == "on"
            }}
        - condition: template
          value_template: |
            {{ trigger.event.data.new_state.attributes.brightness | default(255) !=
              trigger.event.data.new_state.attributes.fixed_brightness | default(states('input_number.brightness') | int) }}
    action:
      - service: light.turn_on
        data_template:
          entity_id: |
            {{ trigger.event.data.new_state.entity_id }}
          brightness: |
            {{ trigger.event.data.new_state.attributes.fixed_brightness | default(states('input_number.brightness') | int) }}
      - service: counter.increment
        entity_id: counter.light_automations

  - alias: log light changes to slack
    trigger:
      platform: event
      event_type: state_changed
    condition:
      condition: template
      value_template: |
        {{
          trigger.event.data.new_state.domain == "light" and
          trigger.event.data.old_state != None and
          ( trigger.event.data.new_state.state != trigger.event.data.old_state.state or
            trigger.event.data.new_state.attributes.brightness != trigger.event.data.old_state.attributes.brightness )
        }}
    action:
      service: notify.slack
      data_template:
        message: |
          :bulb: *{{ trigger.event.data.new_state.name | capitalize }}*{{ " " -}}
          {%- if trigger.event.data.new_state.state == "on" -%}
          *_{{ '%0.0f' % ( ( trigger.event.data.new_state.attributes.brightness / 255 | round ) * 100 ) }}%_*
          {%- else -%}
          *_Off_*
          {%- endif -%}{{ " " -}}
          after being{{ " " -}}
          {%- if trigger.event.data.old_state.state == "on" -%}
          {{ '%0.0f' % ( ( trigger.event.data.old_state.attributes.brightness / 255 | round ) * 100 ) }}%
          {%- else -%}
          Off
          {%- endif -%}{{ " " -}}
          for {{ relative_time(trigger.event.data.old_state.last_changed) }}
        target: "#general"

counter:
  light_automations:
    name: Light Automations

input_number:
  brightness:
    name: Brightness
    min: 0
    max: 255
    step: 1

script:
  living_lights:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.cabinets
      - condition: template
        value_template: >
          {{ states.input_select.mode.state != "Sleeping" }}
      - service: light.turn_on
        data_template:
          entity_id:
            - light.dining_room_table
            - light.kitchen
            - light.living
            - light.pendants
            - light.couch_lamp_right
            - light.couch_lamp_left
          brightness: |
            {{ brightness | default(states('input_number.brightness') | int) }}

  master_bath_lights:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.master_toilet
          brightness: |
            {{ brightness | default(states('input_number.brightness') | int) }}
      - condition: template
        value_template: >
          {{ states.input_select.mode.state != "Sleeping" }}
      - service: light.turn_on
        data_template:
          entity_id:
          - light.master_bath_overhead
          - light.master_shower
          - light.master_mirror
          brightness: |
            {{ brightness | default(states('input_number.brightness') | int) }}

  master_lights:
    sequence:
      - condition: template
        value_template: >
          {{ states.input_select.mode.state not in ["Reading", "Morning"] }}
      - service: homeassistant.turn_on
        data_template:
          entity_id: |
            {{ "light.master_toilet" if states.input_select.mode.state == "Sleeping" else "group.master" }}
          brightness: |
            {{ brightness | default(states('input_number.brightness') | int) }}

  master_lights_off:
    sequence:
      - condition: template
        value_template: >
          {{ states.input_select.mode.state not in ["Reading", "Morning"] }}
      - service: homeassistant.turn_off
        data_template:
          entity_id: |
            group.master

  notify_with_lights:
    sequence:
    - condition: template
      value_template: |
        {{
          states.light |
          selectattr("state", "equalto", "on") |
          selectattr("attributes.notify_action", "equalto", "duck") |
          map(attribute="entity_id") |
          list |
          length > 0
        }}
    - service: script.pulse_light
      data_template:
        entity_id: |
          {{
            states.light |
            selectattr("state", "equalto", "on") |
            selectattr("attributes.notify_action", "equalto", "duck") |
            map(attribute="entity_id") |
            join(', ')
          }}

  office_lights:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id:
          - light.office_desk_lamp
          - light.office_closet
          - light.office_overhead
          - light.office_chandelier
          - light.exercise_bike
          brightness: |
            {{ brightness | default(states('input_number.brightness') | int) }}
      - condition: template
        value_template: >
          {{ states.input_select.mode.state != "Evening" }}
      - service: light.turn_on
        data_template:
          entity_id:
          - light.office_overhead
          brightness: |
            {{ brightness | default(states('input_number.brightness') | int) }}

  pulse_light:
    sequence:
    - service: python_script.dim_step
      data_template:
        action: down
        entity_id: |
          {{ entity_id }}
    - delay:
        seconds: 2
    - service: python_script.dim_step
      data_template:
        action: up
        entity_id: |
          {{ entity_id }}
