automation:
  - alias: Sync Marigold collar light
    id: 89261115-d214-4017-94a9-d1bb66c09d93
    trigger:
      - platform: state
        entity_id:
          - device_tracker.marigold
          - sensor.front_door_front_gate_classification
          - sensor.gate_driveway_gate_classification
      - platform: homeassistant
        event: start
    variables:
      should_be_on: >
        {{
          is_state('device_tracker.marigold', 'home') and (
            is_state('sensor.front_door_front_gate_classification', 'open') or
            is_state('sensor.gate_driveway_gate_classification', 'open')
          )
        }}
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ should_be_on }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.marigold_collar_light
                data:
                  color_name: "red"
        default:
          - service: light.turn_off
            target:
              entity_id: light.marigold_collar_light
