automation:
  - alias: Morning to day
    id: 1b8d26f9-de80-446b-90c1-da385fd0e0b7
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Morning
      - platform: state
        entity_id: binary_sensor.bathroom_home_security_motion_detection
        from: "off"
        to: "on"
      - platform: state
        entity_id:
          - sensor.jphone_battery_state
          - sensor.katie_s_iphone_battery_state
        to: "Not Charging"
        for:
          seconds: 30
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_select.mode
          state: Morning
        - condition: template
          value_template: |
            {{
              (states.device_tracker.jphone_17_pro.state == "not_home" or states.sensor.jphone_battery_state.state == "Not Charging") and
              (states.device_tracker.katie_s_iphone.state == "not_home" or states.sensor.katie_s_iphone_battery_state.state == "Not Charging")
            }}
    action:
      - service: input_select.select_option
        entity_id: input_select.mode
        data:
          option: Day

  - alias: Mode away to day
    id: 08bdb177-c691-4eb6-8cab-92f08689064b
    trigger:
      - platform: state
        entity_id: lock.garage
        to: "unlocked"
      - platform: state
        entity_id: lock.front_door
        to: "unlocked"
      - platform: state
        entity_id: binary_sensor.garage
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.gate
        from: "off"
        to: "on"
      - platform: zone
        entity_id: device_tracker.jphone_17_pro
        zone: zone.home
        event: enter
      - platform: zone
        entity_id: device_tracker.katie_s_iphone
        zone: zone.home
        event: enter
    condition:
      condition: state
      entity_id: input_select.mode
      state: Away
    action:
      - service: input_select.select_option
        entity_id: input_select.mode
        data:
          option: Day

  - alias: Mode day to evening
    id: b9bd62f2-3e44-4320-9b01-8b59ccd00fd0
    trigger:
      - platform: time
        at: "17:00:00"
    condition:
      condition: state
      entity_id: input_select.mode
      state: Day
    action:
      - service: script.turn_on
        entity_id: script.mode_evening
