input_select:
  mode:
    name: Mode
    options:
      - Morning
      - Day
      - Evening
      - Party
      - Cocktail
      - Cooking
      - Reading
      - Sleeping
      - Away
    icon: mdi:cog

automation:
  - alias: Mode selector
    id: a5d8a893-365d-4f4a-8297-ecaeff7fbe43
    trigger:
      platform: state
      entity_id: input_select.mode
    action:
      service: script.turn_on
      data:
        entity_id: script.mode_{{ trigger.to_state.state | lower }}
