automation:
  - alias: Wake up
    trigger:
      - platform: template
        value_template: |
          {{ 
            states.input_datetime.wake_up.attributes.hour == now().hour and
            states.input_datetime.wake_up.attributes.minute == now().minute and
            states.media_player.record_cabinet.state == "idle"
          }}
    action:
    - service: homeassistant.turn_off
      entity_id: group.outdoor_speakers
    - service: homeassistant.turn_on
      entity_id:
        - media_player.master_bathroom_speakers
        - media_player.master_bedroom_speakers
        - media_player.record_cabinet_output_master
    - service: media_player.select_source
      data:
        entity_id: media_player.record_cabinet
        select_source: nature (playlist)
  - alias: Morning mode
    trigger:
      - platform: state
        entity_id: binary_sensor.closet_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.master_bath_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id:
        - sensor.jphone_11_pro_battery_state
        - sensor.katie_s_iphone_battery_state
        to: 'Not Charging'
        for:
          seconds: 30
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_select.mode
        state: Sleeping
      - condition: time
        after: '05:00:00'
        before: '12:00:00'
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.mode
        option: Morning

  - alias: Run default morning actions
    trigger:
    - platform: state
      entity_id: input_select.mode
      to: Morning
    action:   
    - service: light.turn_off
      entity_id: group.master
    - service: input_number.set_value
      data:
        entity_id: input_number.brightness
        value: 255
    - service: light.turn_on
      entity_id:
        - group.speakers
        - light.cabinets
        - light.record_cabinet_left
        - light.record_cabinet_right
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm