automation:
  - alias: network closet lights
    id: ed3adf55-e054-4236-8971-f7e87767ec6a
    trigger:
    - platform: event
      event_type: tag_scanned
      event_data:
        tag_id: a5740e2e-58ec-47bc-8bc4-953c619cded4
    action:
      - service: light.toggle
        data:
          entity_id: light.network_closet
