homeassistant:
  customize:

    binary_sensor.great_room_occupancy:
      trigger_service: script.great_room_lights
      trigger_entity_id_off: group.great_room
      haunt: light.bookshelf_right
      speaker_entity: group.great_room_speakers
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.sub

    binary_sensor.lounge_occupancy:
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.lounge_surround

    binary_sensor.bedroom_occupancy:
      speaker_entity: media_player.master_bedroom_speakers

    binary_sensor.bathroom_occupancy:
      speaker_entity: media_player.master_bathroom_speakers
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.shower

    binary_sensor.front_porch_occupancy:
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.front_porch

    binary_sensor.back_porch_occupancy:
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.back_porch
      trigger_service: script.turn_on_entity_id
      trigger_entity_id: group.back_porch_fan
      trigger_entity_id_off: group.back_porch_fan

    binary_sensor.garage_occupancy:
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.move

    binary_sensor.atrium_occupancy:
      speaker_entity: media_player.atrium_speakers

    binary_sensor.yoga_room_motion:
      haunt: light.bookshelf_middle

    binary_sensor.yoga_room_occupancy:
      trigger_entity_id: group.yoga_room
      trigger_entity_id_off: group.yoga_room
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.yoga

    binary_sensor.garage_hall_motion:
      trigger_entity_id: light.garage_hall
      trigger_entity_id_off: light.garage_hall
      haunt: light.drums
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.record_cabinet

    binary_sensor.guest_hall_home_security_motion_detection:
      trigger_entity_id: light.guest_hall_overhead
      trigger_entity_id_off: light.guest_hall_overhead
      haunt: light.couch
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.record_cabinet

    binary_sensor.great_hall_motion:
      trigger_entity_id: light.great_hall
      trigger_entity_id_off: light.great_hall
      haunt: light.drums
      sonos_group_master: media_player.house
      sonos_group_entity_id: media_player.record_cabinet

    binary_sensor.stairs_occupancy:
      trigger_entity_id: light.stairs
      trigger_entity_id_off: light.stairs

    binary_sensor.stairs_motion:
      haunt: light.bookshelf_right

    binary_sensor.upstairs_home_security_motion_detection:
      haunt: light.bookshelf_right


binary_sensor:
  - platform: template
    sensors:
      great_room_occupancy:
        friendly_name: great room occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.living_room_motion') == 'on' or
            states('binary_sensor.kitchen_motion') == 'on' or
            states('device_tracker.katie_s_iphone') == 'Kitchen' or
            states('device_tracker.jphone_12') == 'Kitchen'
          }}
        delay_off:
          minutes: 30

      lounge_occupancy:
        friendly_name: lounge occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.lounge_home_security_motion_detection') == 'on' or
            states('device_tracker.katie_s_iphone') == 'Lounge' or
            states('device_tracker.jphone_12') == 'Lounge'
          }}
        delay_off:
          minutes: 15

      bedroom_occupancy:
        friendly_name: bedroom occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.master_bath_motion') == 'on' or
            states('binary_sensor.closet_motion') == 'on' or
            states('binary_sensor.master_door') == 'off'
          }}
        delay_off:
          minutes: 15

      bathroom_occupancy:
        friendly_name: bathroom occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.master_bath_motion') == 'on'
          }}
        delay_off:
          minutes: 15

      yoga_room_occupancy:
        friendly_name: yoga room occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.yoga_room_motion') == 'on'
          }}
        delay_off:
          minutes: 30

      garage_occupancy:
        friendly_name: garage occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('cover.garage') == 'open' or 
            states('lock.garage') == 'unlocked' or 
            float(states('sensor.garage_person')) | default(0) > 0 
          }}

      back_porch_occupancy:
        friendly_name: back porch occupancy
        device_class: occupancy
        value_template: |
          {{ 
            states('lock.back_porch') == 'unlocked' or
            float(states('sensor.back_porch_person')) | default(0) > 0 
          }}

      front_porch_occupancy:
        friendly_name: front porch occupancy
        device_class: occupancy
        # dog / packages etc
        delay_on:
          seconds: 10
        value_template: |
          {{ 
            states('lock.front_door') == 'unlocked' or
            float(states('sensor.front_yard_left_person')) | default(0) > 0 
          }}

      atrium_occupancy:
        friendly_name: atrium occupied
        device_class: occupancy
        value_template: |
          {{
            float(states('sensor.atrium_person')) | default(0) > 0
          }}
        delay_off:
          minutes: 30

  - platform: template
    sensors:
      stairs_occupancy:
        friendly_name: stairs occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.stairs_motion') == 'on' or
            states('binary_sensor.upstairs_home_security_motion_detection') == 'on'
          }}
