binary_sensor:
  - platform: template
    sensors:
      great_room_occupancy:
        friendly_name: great room occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.living_room_motion') == 'on' or
            states('binary_sensor.kitchen_motion') == 'on' or
            states('device_tracker.katie_s_iphone') == 'Kitchen' or
            states('device_tracker.jphone_12') == 'Kitchen'
          }}
        delay_off:
          minutes: 30
      lounge_occupancy:
        friendly_name: lounge occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('binary_sensor.lounge_motion') == 'on' or
            states('device_tracker.katie_s_iphone') == 'Lounge' or
            states('device_tracker.jphone_12') == 'Lounge'
          }}
        delay_off:
          minutes: 15
      garage_occupancy:
        friendly_name: garage occupied
        device_class: occupancy
        value_template: |
          {{ 
            states('cover.garage') == 'open' or 
            states('lock.garage') == 'unlocked'
          }}
      back_porch_occupancy:
        friendly_name: back porch occupancy
        device_class: occupancy
        value_template: |
          {{ 
            states('lock.back_porch') == 'unlocked'
          }}
      front_porch_occupancy:
        friendly_name: front purch occupancy
        device_class: occupancy
        # dog / packages etc
        delay_on:
          seconds: 10
        value_template: |
          {{ 
            states('lock.front_door') == 'unlocked'
          }}