homeassistant:
  customize:
    binary_sensor.great_room_occupancy:
      trigger_service: script.great_room_lights
      trigger_entity_id_off: group.great_room
      haunt: light.bookshelf_right
      speaker_entity: group.great_room_speakers
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.sub

    binary_sensor.lounge_occupancy:
      trigger_service: script.lounge_lights
      trigger_entity_id_off: group.lounge
      off_delay_seconds: 1800
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.lounge_surround

    binary_sensor.bedroom_occupancy:
      speaker_entity: media_player.master_bedroom_speakers

    binary_sensor.bathroom_occupancy:
      speaker_entity: media_player.master_bathroom_speakers
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.shower

    binary_sensor.front_porch_occupancy:
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.front_porch

    binary_sensor.back_porch_occupancy:
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.back_porch
      # trigger_entity_id: group.back_porch_fan
      # trigger_entity_id_off: group.back_porch_fan

    binary_sensor.garage_occupancy:
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.move

    binary_sensor.atrium_occupancy:
      trigger_entity_id: switch.atrium_fan
      trigger_entity_id_off: switch.atrium_fan
      speaker_entity: media_player.atrium_speakers
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.rock

    binary_sensor.pergola_occupancy:
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.pergola

    binary_sensor.yoga_room_home_security_motion_detection:
      haunt: light.bookshelf_middle

    binary_sensor.yoga_room_occupancy:
      trigger_entity_id: group.yoga_room
      trigger_entity_id_off: group.yoga_room
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.yoga

    binary_sensor.garage_hall_home_security_motion_detection:
      trigger_entity_id: light.garage_hall
      trigger_entity_id_off: light.garage_hall
      haunt: light.drums

    binary_sensor.guest_hall_home_security_motion_detection:
      trigger_entity_id: light.guest_hall_overhead
      trigger_entity_id_off: light.guest_hall_overhead
      haunt: light.couch

    binary_sensor.great_hall_home_security_motion_detection:
      trigger_entity_id: light.great_hall
      trigger_entity_id_off: light.great_hall
      haunt: light.drums

    binary_sensor.common_area_occupancy:
      media_player_entity_id: media_player.house
      media_player_group_members: media_player.record_cabinet

    binary_sensor.stairs_occupancy:
      trigger_entity_id: light.stairs
      trigger_entity_id_off: light.stairs

    binary_sensor.stairs_home_security_motion_detection:
      haunt: light.bookshelf_right

    binary_sensor.upstairs_home_security_motion_detection:
      haunt: light.bookshelf_right

template:
  - binary_sensor:
      - name: music room occupancy
        device_class: occupancy
        state: |
          {{
            is_state('binary_sensor.music_room_dev_apple_device_detected', 'on') or
            is_state('binary_sensor.music_room_home_security_motion_detection', 'on')
          }}

      - name: common area occupancy
        device_class: occupancy
        state: |
          {{
            is_state('binary_sensor.great_room_occupancy', 'on') or
            is_state('binary_sensor.garage_hall_home_security_motion_detection', 'on') or
            is_state('binary_sensor.guest_hall_home_security_motion_detection', 'on') or
            is_state('binary_sensor.great_hall_home_security_motion_detection', 'on') or
            is_state('binary_sensor.stairs_home_security_motion_detection', 'on')
          }}

      - name: atrium occupancy
        device_class: occupancy
        state: |
          {{
            is_state('binary_sensor.atrium_couch_motion', 'on') or
            float(states('sensor.atrium_person_count'), default=0) > 0
          }}
        delay_off:
          minutes: 10

      - name: pergola occupancy
        device_class: occupancy
        state: |
          {{
            is_state('binary_sensor.pergola_motion', 'on')
          }}
        delay_off:
          minutes: 10

binary_sensor:
  - platform: template
    sensors:
      great_room_occupancy:
        friendly_name: great room occupied
        device_class: occupancy
        value_template: |
          {{
            states('binary_sensor.living_room_motion') == 'on' or
            states('binary_sensor.dining_room_home_security_motion_detection') == 'on' or
            (
              states('device_tracker.katie_s_iphone') == 'Kitchen' and
              states.device_tracker.katie_s_iphone.last_changed > (now() - timedelta(minutes=5))
            ) or
            (
              states('device_tracker.jphone_14') == 'Kitchen' and
              states.device_tracker.jphone_14.last_changed > (now() - timedelta(minutes=5))
            )
          }}
        delay_off:
          minutes: 30

      lounge_occupancy:
        friendly_name: lounge occupied
        device_class: occupancy
        value_template: |
          {{
            states('binary_sensor.lounge_home_security_motion_detection') == 'on' or
            (
              states('device_tracker.katie_s_iphone') == 'Lounge' and
              states.device_tracker.katie_s_iphone.last_changed > (now() - timedelta(minutes=5))
            ) or
            (
              states('device_tracker.jphone_14') == 'Lounge' and
              states.device_tracker.jphone_14.last_changed > (now() - timedelta(minutes=5))
            )
          }}
        delay_off:
          minutes: 15

      bedroom_occupancy:
        friendly_name: bedroom occupied
        device_class: occupancy
        value_template: |
          {{
            states('binary_sensor.bathroom_home_security_motion_detection') == 'on' or
            states('binary_sensor.closet_motion_any') == 'on' or
            states('binary_sensor.bedroom_door_access_control_window_door_is_open') == 'off' or
            (
              states('device_tracker.katie_s_iphone') == 'Bedroom' and
              states.device_tracker.katie_s_iphone.last_changed > (now() - timedelta(minutes=5))
            ) or
            (
              states('device_tracker.jphone_14') == 'Bedroom' and
              states.device_tracker.jphone_14.last_changed > (now() - timedelta(minutes=5))
            )
          }}
        delay_off:
          minutes: 15

      bathroom_occupancy:
        friendly_name: bathroom occupied
        device_class: occupancy
        value_template: |
          {{
            states('binary_sensor.bathroom_home_security_motion_detection') == 'on'
          }}
        delay_off:
          minutes: 15

      yoga_room_occupancy:
        friendly_name: yoga room occupied
        device_class: occupancy
        value_template: |
          {{
            states('binary_sensor.yoga_room_home_security_motion_detection') == 'on' or
            states('binary_sensor.yoga_chair_home_security_motion_detection') == 'on'
          }}
        delay_off:
          minutes: 30

      garage_occupancy:
        friendly_name: garage occupied
        device_class: occupancy
        value_template: |
          {{
            states('cover.garage') == 'open' or
            states('lock.garage') == 'unlocked' or
            float(states('sensor.garage_person_count'), default=0) > 0  or
            states.sensor.garage_person_count.last_changed > (now() - timedelta(minutes=10))
          }}

      back_porch_occupancy:
        friendly_name: back porch occupancy
        device_class: occupancy
        value_template: |
          {{
            states('lock.back_porch') == 'unlocked' or
            float(states('sensor.back_porch_person_count'), default=0) > 0 or
            states.sensor.back_porch_person_count.last_changed > (now() - timedelta(minutes=5))
          }}

      front_porch_occupancy:
        friendly_name: front porch occupancy
        device_class: occupancy
        # dog / packages etc
        delay_on:
          seconds: 15
        value_template: |
          {{
            states('lock.front_door') == 'unlocked' or
            float(states('sensor.front_yard_left_person_count'), default=0) > 0 or
            states.sensor.front_yard_left_person_count.last_changed > (now() - timedelta(minutes=5))
          }}

  - platform: template
    sensors:
      stairs_occupancy:
        friendly_name: stairs occupied
        device_class: occupancy
        value_template: |
          {{
            states('binary_sensor.stairs_home_security_motion_detection') == 'on' or
            states('binary_sensor.upstairs_home_security_motion_detection') == 'on'
          }}
