automation:
  - alias: Log Pico events
    mode: parallel
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
    action:
      - service: system_log.write
        data:
          message: >
            at=lutron_caseta_button_event
            data={{ trigger.event.data }}
          logger: packages.picos
          level: debug


  - alias: Sonos Pico
    trigger:
      - platform: event
        event_type: lutron_caseta_button_event
        event_data:
          serial: 82522729
          action: press
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.button_number == 2 }}"
            sequence:
              - service: media_player.media_play_pause
                target:
                  entity_id: media_player.house

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.button_number == 5 }}"
            sequence:
              - service: media_player.volume_up
                target:
                  entity_id: media_player.house

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.button_number == 6 }}"
            sequence:
              - service: media_player.volume_down
                target:
                  entity_id: media_player.house

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.button_number == 4 }}"
            sequence:
              - service: media_player.media_next_track
                target:
                  entity_id: media_player.house

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.button_number == 3 }}"
            sequence:
              - service: media_player.play_media
                target:
                  entity_id: media_player.house
                data:
                  media_content_id: >
                    {{ state_attr("sensor.sonos_favorites", "items") | list | random }}
                  media_content_type: favorite_item_id                

        default: []
    mode: queued
    max: 10

