homeassistant:
  customize:
    binary_sensor.precipitation_in_forecast:
      icon: mdi:weather-rainy
    sensor.precipitation_in_forecast:
      icon: mdi:weather-rainy

automation:
  - alias: Precipitation notifications
    id: adeaa17d-9184-4cd4-9086-47dcc8817b71
    trigger:
    - platform: state
      entity_id: binary_sensor.precipitation_in_forecast
      from: "on"
      to: "off"
    condition: |
      {{ states('device_tracker.jphone_14') != 'not_home' }}
    action:
      - service: script.ack
        data:
          notify_service: notify.mobile_app_jphone_14
          entity_id: script.noop
          tag: precipitation
          message: Rain is forecasted soon. Prep for rain?
          confirmation_message: prepped for rain, cool.
  - alias: Sunshine notifications
    id: ad844a6c-87f8-4e72-9839-9af40bd4c500
    trigger:
    - platform: state
      entity_id: binary_sensor.precipitation_in_forecast
      from: "off"
      to: "on"
    condition: |
      {{ states('device_tracker.jphone_14') != 'not_home' }}
    action:
      - service: script.ack
        data:
          notify_service: notify.mobile_app_jphone_14
          entity_id: script.noop
          tag: precipitation
          message: No rain in the forecast. Prep for sunshine?
          confirmation_message: prepped for sunshine, cool.

input_number:
  precipitation_forecast_hours:
    name: Precipitation forecast hours
    min: 4
    max: 48
    step: 1
  precipitation_forecast_probability_threshold:
    name: Precipitation forecast probability threshold
    min: 0
    max: 100
    step: 5


binary_sensor:
  - platform: template
    sensors:
      precipitation_in_forecast:
        friendly_name: Precipitation in forecast
        value_template: |
          {{ 
            states('sensor.forecast_precipitation_probability') | float(default=0) 
            > 
            states('input_number.precipitation_forecast_probability_threshold') | float(default=100)
          }}
        delay_on:
          minutes: 30
        delay_off:
          minutes: 30
sensor:
  - platform: template
    sensors:
      forecast_precipitation_probability:
        friendly_name: Precipitation probability
        unit_of_measurement: '%'
        value_template: |
          {{
            (
              state_attr("weather.katt_hourly", "forecast") |
              default([{}]) | batch(
                states("input_number.precipitation_forecast_hours") | default(12)
              ) | first |
              rejectattr("precipitation_probability", "none") |
              rejectattr("precipitation_probability", "undefined") |
              max(attribute="precipitation_probability") | default({"precipitation_probability":0})
            )["precipitation_probability"]
          }}
      next_precipitation:
        friendly_name: Next precipitation
        unit_of_measurement: timestamp
        value_template: |
          {% set next_precip = state_attr("weather.katt_hourly", "forecast") |
              default([{}]) | batch(
                states("input_number.precipitation_forecast_hours") | default(12)
              ) | first |
              rejectattr("precipitation_probability", "none") |
              rejectattr("precipitation_probability", "undefined") |
              rejectattr("precipitation_probability", "<", states('input_number.precipitation_forecast_probability_threshold') | float(default=100)) | 
              map(attribute='datetime') |
              first |
              default(false) %}
          {{ next_precip or "" }}
      hours_until_rain:
        friendly_name: Hours until rain
        unit_of_measurement: 'hours'
        value_template: |
          {% if states('sensor.next_precipitation') == 'unavailable' or states('sensor.next_precipitation') == '' %}
            {{ state_attr("weather.katt_hourly", "forecast") | length }}
          {% else %}
            {% for item in state_attr("weather.katt_hourly", "forecast") |
                      default([{}]) %}
              {% if item.datetime == states('sensor.next_precipitation') %}
                {{ loop.index }}
              {% endif %}
            {% endfor %}
          {% endif %}