automation:
  - alias: Puppy bell
    id: 050335c4-2f3d-4dbc-ac00-cf1f69759db7
    trigger:
      platform: state
      entity_id:
        - binary_sensor.front_door_puppy_tampering_product_cover_removed
      to: "on"
    condition:
      condition: state
      entity_id: lock.front_door
      state: locked
    action:
      - service: script.ack
        data:
          entity_id: script.noop
          tag: front_door_puppy
          message: 🐶🌼 is at the front door
          confirmation_message: is letting 🐶🌼 out, cool.
