automation:
  - alias: Puppy bark
    id: 6fc7d655-2e09-4049-9392-9ac6820f70d5
    trigger:
      - platform: state
        entity_id: binary_sensor.crate_bark_sound
        to: "on"
      - platform: state
        entity_id: binary_sensor.front_door_bark_sound
        to: "on"
    action:
      - service: script.ack
        data:
          entity_id: script.noop
          tag: bark
          message: ❗️📢🐶
          confirmation_message: is handling ❗️📢🐶, cool
          decline_message: can't handle ❗️📢🐶 rn, can you?

  - alias: Puppy bell
    id: 050335c4-2f3d-4dbc-ac00-cf1f69759db7
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_puppy_tampering_product_cover_removed
        to: "on"
    condition:
      condition: state
      entity_id: lock.front_door
      state: locked
    action:
      - delay: 2
      - condition: state
        entity_id: lock.front_door
        state: locked
      - service: script.ack
        data:
          entity_id: script.noop
          tag: front_door_puppy
          message: 🐶🌼 is at the front door
          confirmation_message: is letting 🐶🌼 out, cool
          decline_message: can't handle 🐶🌼 rn, can you?

  - alias: Puppy bell dismiss
    id: 050335c4-2f3d-4dbc-ac00-cf1f69759db8
    trigger:
      platform: state
      entity_id: lock.front_door
      to: unlocked
    action:
      - service: notify.iphones
        data:
          message: clear_notification
          data:
            tag: front_door_puppy
