cover:
  - platform: group
    name: Shades
    entities:
      - cover.master_bathroom_shade
      - cover.master_bedroom_closet
      - cover.master_bedroom_corner
      - cover.master_bedroom_door
      - cover.master_bedroom_wall_bottom
      - cover.master_bedroom_wall_left
      - cover.master_bedroom_wall_right
      - cover.master_bedroom_wall_top
      - cover.yoga_bottom
      - cover.yoga_top

  - platform: group
    name: Bathroom shades
    entities:
      - cover.master_bathroom_shade

  - platform: group
    name: Bedroom shades
    entities:
      - cover.master_bedroom_closet
      - cover.master_bedroom_corner
      - cover.master_bedroom_door
      - cover.master_bedroom_wall_bottom
      - cover.master_bedroom_wall_left
      - cover.master_bedroom_wall_right
      - cover.master_bedroom_wall_top

  - platform: group
    name: Bedroom shades reading
    entities:
      - cover.master_bedroom_closet
      - cover.master_bedroom_wall_bottom
      - cover.master_bedroom_wall_left
      - cover.master_bedroom_wall_right
      - cover.master_bedroom_wall_top
      - cover.master_bathroom_shade

  - platform: group
    name: AC shades sunny
    entities:
      - cover.master_bedroom_closet
      - cover.master_bedroom_door
      - cover.master_bedroom_wall_bottom
      - cover.master_bedroom_wall_left
      - cover.master_bedroom_wall_right
      - cover.master_bedroom_wall_top

  - platform: group
    name: Yoga room shades
    entities:
      - cover.yoga_bottom
      - cover.yoga_top

automation:
  - alias: Open shades on workday mornings at 7am
    id: 81dbe453-9844-470f-af98-56673e86bdc5
    trigger:
      - platform: time
        at: "07:00:00"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "on"
        - condition: or
          conditions:
            - condition: zone
              entity_id: device_tracker.katie_s_iphone
              zone: zone.home
            - condition: zone
              entity_id: device_tracker.jphone
              zone: zone.home
    action:
      - service: cover.open_cover
        data:
          entity_id: cover.bedroom_shades
      - service: cover.open_cover
        data:
          entity_id: cover.yoga_room_shades

  - alias: Close some shades in reading mode
    id: 806d4e21-9d09-40fd-8f8f-67476d216e7c
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Reading
    action:
      - service: cover.close_cover
        data:
          entity_id: cover.bedroom_shades_reading

  - alias: Close shades in sleeping modes
    id: 806d4e21-9d09-40fd-8f8f-67476d216e7d
    trigger:
      - platform: state
        entity_id: input_select.mode
        to: Sleeping
    action:
      - service: cover.close_cover
        data:
          entity_id: cover.shades

  - alias: Close shades when it gets warm upstairs while sunny
    mode: queued
    id: bc4654f1-a45e-45f4-9b5d-50f21b446aef
    trigger:
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        above: 75
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") > 28 }}'
      - condition: state
        entity_id: weather.tomorrow_io_home_nowcast
        state: sunny
    action:
      - service: cover.close_cover
        data:
          entity_id: cover.ac_shades_sunny

  - alias: Open shades when its cool enough and the door is open
    mode: queued
    id: bc4654f1-a45e-45f4-9b5d-50f21b446ae0
    trigger:
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        below: 76
        for:
          minutes: 30
      - platform: numeric_state
        entity_id: sensor.upstairs_thermostat_air_temperature
        below: 75
      - platform: template
        value_template: '{{ state_attr("sun.sun", "elevation") < 28 }}'
    condition:
      - condition: state
        entity_id: binary_sensor.bedroom_door_access_control_window_door_is_open
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.mode
            state: Sleeping
    action:
      - service: cover.open_cover
        data:
          entity_id: cover.bedroom_shades
