sensor:
  - platform: sql
    scan_interval: 600
    queries:
      - name: Database size
        db_url: !env_var DB_URL
        query: >
          SELECT ROUND(page_count * page_size / 1024 / 1024, 1) as size FROM pragma_page_count(), pragma_page_size();
        column: "size"
