sensor:
  - platform: sql
    scan_interval: 600
    queries:
      - name: db_bytes
        query: "SELECT page_count * page_size as size FROM pragma_page_count(), pragma_page_size();"
        column: "size"
        unit_of_measurement: "Bytes"

template:
  - sensor:
      - name: Database size
        unique_id: "database_size"
        state: >
          {{ (state_attr('sensor.db_bytes','size') | filesizeformat(binary=false)) }}
