automation:
  - alias: Sunrise
    trigger:
      platform: sun
      event: sunrise
      offset: '+00:30:00'
    action:
      service: script.turn_on
      entity_id: script.sunrise

  - alias: Sunset
    trigger:
      platform: sun
      event: sunset
    action:
      service: script.turn_on
      entity_id: script.sunset

script:
  sunrise:
    sequence:
      - service: light.turn_off
        entity_id: group.security
      - service: notify.slack
        data_template:
          message: ":city_sunrise:"
  sunset:
    sequence:
      - service: light.turn_on
        entity_id: group.security
      - service: notify.slack
        data_template:
          message: ":city_sunset:"
      - condition: template
        value_template: |
          {{ states.input_select.mode.state != "Away" }}
      - service: light.turn_on
        entity_id: light.bamboo
      - condition: template
        value_template: |
          {{
            states.weather.dark_sky.attributes.visibility > 5 and
            states.weather.dark_sky.attributes.temperature > 50
          }}
      - service: notify.iphones
        data:
          message: 'Check out the sunset!'
