automation:
  - alias: Sunrise
    id: 18c7095a-3986-4a0d-b56b-4b95182a532b
    trigger:
      platform: sun
      event: sunrise
      offset: '+00:30:00'
    action:
      service: script.turn_on
      entity_id: script.sunrise

  - alias: Sunset
    id: d10e1481-8130-4d7f-b702-419628c970cd
    trigger:
      platform: sun
      event: sunset
    action:
      service: script.turn_on
      entity_id: script.sunset

script:
  sunrise:
    sequence:
      - service: light.turn_off
        entity_id: group.security
      - service: notify.slack
        data:
          title: sun
          message: ":city_sunrise:"
  sunset:
    sequence:
      - service: light.turn_on
        entity_id: group.security
      - service: notify.slack
        data:
          title: sun
          message: ":city_sunset:"
      - condition: template
        value_template: |
          {{ states.input_select.mode.state != "Away" }}
      - service: homeassistant.turn_on
        entity_id: group.trees
      - condition: template
        value_template: |
          {{
            (state_attr('weather.dark_sky', 'visibility') | default(0)) > 5 and
            (state_attr('weather.dark_sky', 'temperature') | default(0)) > 50
          }}
      - service: notify.iphones
        data:
          message: 'Check out the sunset!'
          data:
            push:
              category: camera
            entity_id: camera.roof_deck
            attachment:
              url: |
                https://home.jnewland.com{{ states.camera.roof_deck.attributes.entity_picture }}
              content-type: jpeg
              hide-thumbnail: false

