automation:
  - alias: Sunrise
    id: 18c7095a-3986-4a0d-b56b-4b95182a532b
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:30:00"
    action:
      service: script.turn_on
      entity_id: script.sunrise

  - alias: Sunset
    id: d10e1481-8130-4d7f-b702-419628c970cd
    trigger:
      platform: sun
      event: sunset
    action:
      service: script.turn_on
      entity_id: script.sunset

  - alias: Turn off outdoor mood lights
    id: 0c99aed7-1e85-42e3-9290-2975eb2cf291
    trigger:
      platform: time
      at: "01:00:00"
    action:
      service: homeassistant.turn_off
      entity_id: group.outdoor_mood

script:
  sunrise:
    mode: parallel
    sequence:
      - service: light.turn_off
        entity_id: group.security
  sunset:
    mode: parallel
    sequence:
      - service: light.turn_on
        entity_id: group.security
      - condition: template
        value_template: |
          {{ states.input_select.mode.state != "Away" }}
      - service: light.turn_on
        entity_id: group.outdoor_mood
