notify:

  - platform: group
    name: tidbyt_once
    services:
      - service: tidbyt_jesse_once
      - service: tidbyt_katie_once
      - service: tidbyt_music_room_once

  - name: tidbyt_jesse_background
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      installationID: push
      deviceID: surgically-vaulting-mutual-angelfish-704
      apiToken: !env_var TIDBYT_JESSE_API_TOKEN
      background: "true"

  - name: tidbyt_jesse_banner
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      installationID: push
      deviceID: surgically-vaulting-mutual-angelfish-704
      apiToken: !env_var TIDBYT_JESSE_API_TOKEN
      background: "false"

  - name: tidbyt_jesse_once
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      deviceID: surgically-vaulting-mutual-angelfish-704
      apiToken: !env_var TIDBYT_JESSE_API_TOKEN
      background: "false"

  - name: tidbyt_katie_background
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      installationID: push
      deviceID: blithely-celebrated-lucid-grub-f33
      apiToken: !env_var TIDBYT_KATIE_API_TOKEN
      background: "true"

  - name: tidbyt_katie_banner
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      installationID: push
      deviceID: blithely-celebrated-lucid-grub-f33
      apiToken: !env_var TIDBYT_KATIE_API_TOKEN
      background: "false"

  - name: tidbyt_katie_once
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      deviceID: blithely-celebrated-lucid-grub-f33
      apiToken: !env_var TIDBYT_KATIE_API_TOKEN
      background: "false"

  - name: tidbyt_music_room_background
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      installationID: push
      deviceID: critically-tonic-artful-okapi-423
      apiToken: !env_var TIDBYT_MUSIC_ROOM_API_TOKEN
      background: "true"

  - name: tidbyt_music_room_banner
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      installationID: push
      deviceID: critically-tonic-artful-okapi-423
      apiToken: !env_var TIDBYT_MUSIC_ROOM_API_TOKEN
      background: "false"

  - name: tidbyt_music_room_once
    platform: rest
    resource: http://pixlet:8080/api/v1/push
    method: POST_JSON
    message_param_name: msg
    data:
      deviceID: critically-tonic-artful-okapi-423
      apiToken: !env_var TIDBYT_MUSIC_ROOM_API_TOKEN
      background: "false"

  - name: tidbyt_music_room_date_progress
    platform: rest
    resource: http://date-progress:8081/api/v1/push
    method: POST_JSON
    message_param_name: value_prefix
    data:
      deviceID: critically-tonic-artful-okapi-423
      apiToken: !env_var TIDBYT_MUSIC_ROOM_API_TOKEN
      background: "true"
      installationID: date-progress
      value_multiplier: 200

automation:
  - alias: Music Room Date Progress
    mode: parallel
    id: 2567b3d9-6cfa-423f-888e-9c5b6c09fbfb
    trigger:
      - platform: time_pattern
        minutes: "/5"
    action:
      service: notify.tidbyt_music_room_date_progress
      data:
        message: "$"
