sensor:
  - platform: rest
    # All of these seem to use the same IP
    resource: http://192.168.12.1/TMI/v1/gateway?get=all
    scan_interval: 60
    method: GET
    name: tmhi_radio_status
    json_attributes:
      - signal
      - device
      - time
    value_template: "{{ value_json.device.isEnabled }}"

template:
  - sensor:
      #5G
      - default_entity_id: sensor.tmhi_5g_band
        name: "TMHI 5G Band"
        icon: mdi:signal-5g
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g'] ['bands'] [0] if '5g' in state_attr('sensor.tmhi_radio_status', 'signal') else 'N/A' }}
      - default_entity_id: sensor.tmhi_5g_bars
        name: "TMHI 5G Bars"
        icon: mdi:signal
        unit_of_measurement: "bars"
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g'] ['bars'] | int if '5g' in state_attr('sensor.tmhi_radio_status', 'signal') else 0 }}
      - default_entity_id: sensor.tmhi_5g_sinr
        name: "TMHI 5G SINR"
        unit_of_measurement: "%"
        icon: mdi:signal
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g']['sinr'] if '5g' in state_attr('sensor.tmhi_radio_status', 'signal') else 0 }}
      - default_entity_id: sensor.tmhi_5g_rsrp
        name: "TMHI 5G RSRP"
        unit_of_measurement: "dBm"
        icon: mdi:signal
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g']['rsrp'] if '5g' in state_attr('sensor.tmhi_radio_status', 'signal') else -100 }}
      - default_entity_id: sensor.tmhi_5g_rssi
        name: "TMHI 5G RSSI"
        unit_of_measurement: "dBm"
        icon: mdi:signal
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g']['rssi'] if '5g' in state_attr('sensor.tmhi_radio_status', 'signal') else -100 }}
      #4G
      - default_entity_id: sensor.tmhi_4g_band
        name: "TMHI 4G Band"
        icon: mdi:signal-4g
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['4g']['bands'][0] if '4g' in state_attr('sensor.tmhi_radio_status', 'signal') else 'N/A' }}
      - default_entity_id: sensor.tmhi_4g_bars
        name: "TMHI 4G Bars"
        icon: mdi:signal
        unit_of_measurement: "bars"
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['4g']['bars'] | int if '4g' in state_attr('sensor.tmhi_radio_status', 'signal') else 0 }}
      - default_entity_id: sensor.tmhi_4g_sinr
        name: "TMHI 4G SINR"
        unit_of_measurement: "%"
        icon: mdi:signal
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['4g']['sinr'] if '4g' in state_attr('sensor.tmhi_radio_status', 'signal') else 0 }}
      - default_entity_id: sensor.tmhi_4g_rsrp
        name: "TMHI 4G RSRP"
        unit_of_measurement: "dBm"
        icon: mdi:signal
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['4g']['rsrp'] if '4g' in state_attr('sensor.tmhi_radio_status', 'signal') else -100 }}
      - default_entity_id: sensor.tmhi_4g_rssi
        name: "TMHI 4G RSSI"
        unit_of_measurement: "dBm"
        icon: mdi:signal
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'signal') ['4g']['rssi'] if '4g' in state_attr('sensor.tmhi_radio_status', 'signal') else -100 }}
      #Device
      - default_entity_id: sensor.tmhi_software_version
        name: "TMHI Software Version"
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'device') ['softwareVersion'] }}
      - default_entity_id: sensor.tmhi_serial
        name: "TMHI Serial"
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'device') ['serial']   }}
      - default_entity_id: sensor.tmhi_update_state
        name: "TMHI Update State"
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'device') ['updateState']   }}
      - default_entity_id: sensor.tmhi_mac_id
        name: "TMHI MAC Id"
        state: >
          {{ state_attr('sensor.tmhi_radio_status', 'device') ['macId']   }}
