binary_sensor:
  - platform: template
    sensors:
      ups_voltage_low:
        value_template: |
          {{ float(states('sensor.ups_input_voltage'), default=0) <= 114 }}

automation:
  - alias: Notify Jesse when UPS voltage is low
    id: e03bf271-a580-41f0-81e0-ca0c13cefae3
    trigger:
      platform: state
      entity_id: binary_sensor.ups_voltage_low
      to: "on"
    action:
      service: notify.mobile_app_jphone
      data:
        message: |
          Core UPS reports status of {{ states('sensor.ups_status') | default("Unknown") }} with input of {{ float(states('sensor.ups_input_voltage', default=0)) | round }}{{ state_attr('sensor.ups_input_voltage','unit_of_measurement') }}.{{" "-}}
          Battery runtime estimated to be {{ float(states('sensor.ups_battery_runtime', default=60)/60) | round }} minutes.
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
