input_boolean:
  visitor:
    name: Visitor mode
    icon: mdi:home-import-outline

automation:
  - alias: Notify when visitor arrives
    id: aca50a21-eb0e-42c9-83eb-586ab90e9ced
    trigger:
      - platform: state
        entity_id: lock.front_door
        to: "unlocked"
      - platform: state
        entity_id: lock.front_door_schlage
        to: "unlocked"
    action:
      - condition: template
        value_template: |
          {{ 
            trigger.to_state.attributes.changed_by | default("") == "keypad - Visitor" or
            is_state("input_boolean.visitor", "on")
           }}
      - choose:
          - conditions: >
              {{ not is_state('alarm_control_panel.alarm', 'disarmed') }}
            sequence:
              - service: notify.iphones
                data:
                  message: >
                    visitor arrived.
                    alarm is {{ states("alarm_control_panel.alarm") }}.
                    attempting to disarm.
                  data:
                    tag: visitor
                    sound:
                      name: default
                      critical: 1
                      volume: 0.1
                    push:
                      category: camera
                    entity_id: camera.front_door
                    attachment:
                      url: |
                        {{ states('input_text.external_url') }}{{ state_attr("camera.front_door","entity_picture") }}
                      content-type: jpeg
                      hide-thumbnail: false
              - wait_template: >
                  {{ is_state('alarm_control_panel.alarm', 'disarmed') }}
              - service: notify.iphones
                data:
                  message: >
                    visitor arrived.
                    alarm is {{ states("alarm_control_panel.alarm") }}.
                  data:
                    tag: visitor
                    push:
                      category: camera
                    entity_id: camera.front_door
                    attachment:
                      url: |
                        {{ states('input_text.external_url') }}{{ state_attr("camera.front_door","entity_picture") }}
                      content-type: jpeg
                      hide-thumbnail: false
        default:
          - service: notify.iphones
            data:
              message: >
                visitor arrived.
                alarm is {{ states("alarm_control_panel.alarm") }}.
              data:
                tag: visitor
                push:
                  category: camera
                entity_id: camera.front_door
                attachment:
                  url: |
                    {{ states('input_text.external_url') }}{{ state_attr("camera.front_door","entity_picture") }}
                  content-type: jpeg
                  hide-thumbnail: false

  - alias: Turn on away when visitor departs
    id: 0c1978a8-30d2-4fc5-a126-9a5064b2eeda
    trigger:
      - platform: state
        entity_id: lock.front_door
        to: "locked"
      - platform: state
        entity_id: lock.front_door_schlage
        to: "locked"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.visitor
          state: "on"
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: "disarmed"
    action:
      - repeat:
          until: |
            {{ not is_state('alarm_control_panel.alarm', 'disarmed') }}
          sequence:
            - service: script.turn_on
              data:
                entity_id: script.mode_away
            - wait_template: |
                {{ not is_state('alarm_control_panel.alarm', 'disarmed') }}
              timeout: 5
      - service: notify.iphones
        data:
          message: >
            visitor locked the front door.
            alarm set to {{ states("alarm_control_panel.alarm") }}.
          data:
            tag: visitor
            push:
              category: camera
            entity_id: camera.front_door
            attachment:
              url: |
                {{ states('input_text.external_url') }}{{ state_attr("camera.front_door","entity_picture") }}
              content-type: jpeg
              hide-thumbnail: false
