automation:
  - id: bcef2f61-2d42-4405-bcdd-ca792b521d2c
    trigger:
      - platform: state
        entity_id:
          - switch.volcano_pump
        to: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.volcano_ready
        state: "on"
    action:
      - service: script.ack
        data:
          notify_service: notify.mobile_app_jphone_14
          entity_id: switch.volcano_pump
          tag: volcano
          message: |
            Volcano is {{ states.sensor.volcano_current_temperature.state_with_unit }}. Turn on pump?
          interruption_level: time-sensitive
          skip_confirmation: true

  - id: 1f1020ce-22d8-4b8f-a045-4b2726c840b6
    trigger:
      - platform: state
        entity_id:
          - switch.volcano_pump
        to: "on"
        for:
          seconds: 5
    condition: []
    action:
      - service: script.ack
        data:
          notify_service: notify.mobile_app_jphone_14
          service: homeassistant.turn_off
          entity_id: switch.volcano_pump
          tag: volcano
          message: |
            Volcano pump is on. Turn off?
          interruption_level: time-sensitive
          skip_confirmation: true

  - id: 47e34b79-f8f1-4da3-af5e-8e3f38508405
    trigger:
      - platform: state
        entity_id:
          - switch.volcano_heater
        to: "off"
    condition: []
    action:
      - service: script.ack
        data:
          notify_service: notify.mobile_app_jphone_14
          entity_id: switch.volcano_heater
          tag: volcano
          message: Volcano is cooling off. Turn on?
          skip_confirmation: true
          interruption_level: passive
