input_boolean:
  winterized:
    initial: off
    name: winterized
    icon: mdi:home-thermometer-outline

binary_sensor:
  - platform: template
    sensors:
      freeze_forecast:
        friendly_name: Freeze in forecast
        device_class: cold
        value_template: |
          {{ state_attr('weather.dark_sky', 'forecast') | default({'temperature':33}) | map(attribute='temperature') | min < 33 }}
      freeze:
        friendly_name: Freeze
        device_class: cold
        value_template: |
          {{ state_attr('weather.dark_sky', 'temperature') | default(33) < 33 }}

automation:
  - alias: Freeze forecast notifications
    initial_state: off
    trigger:
    - platform: state
      entity_id: binary_sensor.freeze_forecast
      from: "on"
      to: "off"
    condition:
      condition: state
      entity_id: input_boolean.winterized
      state: "off"
    action:
      - service: script.ask_about_turning_on
        data:
          entity_id: input_boolean.winterized
          message: There's a freeze in the forecast. Is everything winterized?
          confirmation_message: winterized, cool

  - alias: Freeze notifications
    initial_state: off
    trigger:
    - platform: state
      entity_id: binary_sensor.freeze
      from: "on"
      to: "off"
    condition:
      condition: state
      entity_id: input_boolean.winterized
      state: "off"
    action:
      - service: script.ask_about_turning_on
        data:
          entity_id: input_boolean.winterized
          message: It's now below freezing. Is everything winterized?
          confirmation_message: winterized, cool
