input_boolean:
  winterized:
    name: winterized
    icon: mdi:home-thermometer-outline

binary_sensor:
  - platform: template
    sensors:
      freeze_forecast:
        friendly_name: Freeze in forecast
        device_class: cold
        value_template: |
          {{ state_attr('weather.tomorrow_io_home_daily', 'forecast') | default([{'temperature':33}]) | map(attribute='temperature') | min < 33 }}
      freeze:
        friendly_name: Freeze
        device_class: cold
        value_template: |
          {{ state_attr('weather.tomorrow_io_home_nowcast', 'temperature') | default(33) < 33 }}

automation:
  - alias: Freeze forecast notifications
    id: 63cf36f6-2881-42a6-83e3-d7ea5528dbef
    trigger:
      - platform: state
        entity_id: binary_sensor.freeze_forecast
        from: "on"
        to: "off"
    condition:
      condition: state
      entity_id: input_boolean.winterized
      state: "off"
    action:
      - service: script.ack
        data:
          entity_id: input_boolean.winterized
          message: There's a freeze in the forecast. Is everything winterized?
          confirmation_message: winterized, cool.

  - alias: Freeze notifications
    id: 23f45074-5827-4756-8f77-f592ac08cb39
    trigger:
      - platform: state
        entity_id: binary_sensor.freeze
        from: "on"
        to: "off"
    condition:
      condition: state
      entity_id: input_boolean.winterized
      state: "off"
    action:
      - service: script.ack
        data:
          entity_id: input_boolean.winterized
          message: It's now below freezing. Is everything winterized?
          confirmation_message: winterized, cool.
