# rachio
sensor:


  - platform: history_stats
    name: atrium zone daily runtime
    entity_id: switch.atrium_garden_drip
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: backyard zone daily runtime
    entity_id: switch.backyard_drip
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: pecan tree zone daily runtime
    entity_id: switch.pecan_tree_garden_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: boardwalk zone daily runtime
    entity_id: switch.boardwalk_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: driveway lawn zone daily runtime
    entity_id: switch.driveway_lawn_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: oak tree bed zone daily runtime
    entity_id: switch.oak_tree_bed_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: oak tree lawn zone daily runtime
    entity_id: switch.oak_tree_lawn_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

# bhyve 
template:

  - trigger:
      - platform: state
        entity_id: sensor.atrium_drippers_zone_history
        to:
    sensor:
      - name: atrium drippers zone last runtime
        state_class: total_increasing
        device_class: duration
        unit_of_measurement: hours
        last_reset_value_template: >
          {{ states.sensor.atrium_drippers_zone_history.last_changed }}
        state: >
          {{ state_attr('sensor.atrium_drippers_zone_history', 'run_time') | float / 60 }}

  - trigger:
      - platform: state
        entity_id: sensor.fountain_refill_zone_history
        to:
    sensor:
      - name: fountain refill zone last runtime
        state_class: total_increasing
        device_class: duration
        unit_of_measurement: hours
        last_reset_value_template: >
          {{ states.sensor.fountain_refill_zone_history.last_changed }}
        state: >
          {{ state_attr('sensor.fountain_refill_zone_history', 'run_time') | float / 60 }}

  - trigger:
      - platform: state
        entity_id: sensor.front_yard_drippers_zone_history
        to:
    sensor:
      - name: front yard drippers zone last runtime
        state_class: total_increasing
        device_class: duration
        unit_of_measurement: hours
        last_reset_value_template: >
          {{ states.sensor.front_yard_drippers_zone_history.last_changed }}
        state: >
          {{ state_attr('sensor.front_yard_drippers_zone_history', 'run_time') | float / 60 }}

  - trigger:
      - platform: state
        entity_id: sensor.patio_drippers_zone_history
        to:
    sensor:
      - name: patio drippers zone last runtime
        state_class: total_increasing
        device_class: duration
        unit_of_measurement: hours
        last_reset_value_template: >
          {{ states.sensor.patio_drippers_zone_history.last_changed }}
        state: >
          {{ state_attr('sensor.patio_drippers_zone_history', 'run_time') | float / 60 }}


  - trigger:
      - platform: state
        entity_id: sensor.pergola_drippers_zone_history
        to:
    sensor:
      - name: pergola drippers zone last runtime
        state_class: total_increasing
        device_class: duration
        unit_of_measurement: hours
        last_reset_value_template: >
          {{ states.sensor.pergola_drippers_zone_history.last_changed }}
        state: >
          {{ state_attr('sensor.pergola_drippers_zone_history', 'run_time') | float / 60 }}

