sensor:

# rachio

  - platform: history_stats
    name: atrium zone daily runtime
    entity_id: switch.atrium_garden_drip
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: backyard zone daily runtime
    entity_id: switch.backyard_drip
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: pecan tree zone daily runtime
    entity_id: switch.pecan_tree_garden_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: boardwalk zone daily runtime
    entity_id: switch.boardwalk_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: driveway lawn zone daily runtime
    entity_id: switch.driveway_lawn_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: oak tree bed zone daily runtime
    entity_id: switch.oak_tree_bed_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: oak tree lawn zone daily runtime
    entity_id: switch.oak_tree_lawn_sprayers
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

# bhyve

  - platform: history_stats
    name: atrium drippers zone daily runtime
    entity_id: switch.atrium_drippers_zone
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: fountain refill zone daily runtime
    entity_id: switch.fountain_refill_zone
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: front yard drippers zone daily runtime
    entity_id: switch.front_yard_drippers_zone
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: patio drippers zone daily runtime
    entity_id: switch.patio_drippers_zone
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: pergola zone daily runtime
    entity_id: switch.pergola_drippers_zone
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: vegepod sprayers zone daily runtime
    entity_id: switch.vegepod_sprayers_zone
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"