automation:
  - alias: debug lock zwave events
    mode: parallel
    id: 2a4654c0-122c-4166-ad30-c8bde5156ddf
    trigger:
    - platform: event
      event_type: zwave_js_notification
    action:
      - service: system_log.write
        data:
          message: >
            at=zwave_js_notification
            event={{ trigger.event }}
          logger: packages.zwave
          level: debug