template:
  - sensor:
      - name: Vera Entities
        unique_id: vera_entities
        unit_of_measurement: entities
        state: >
          {{ integration_entities('vera') | count }}

  - sensor:
      - name: ZwaveJS Entities
        unique_id: zwavejs_entities
        unit_of_measurement: entities
        state: >
          {{ integration_entities('zwave_js') | count }}

automation:
  - alias: debug lock zwave events
    mode: parallel
    id: 2a4654c0-122c-4166-ad30-c8bde5156ddf
    trigger:
    - platform: event
      event_type: zwave_js_notification
      event_data:
        node_id: 49
    action:
      - service: system_log.write
        data:
          message: >
            at=zwave_js_notification
            event={{ trigger.event }}
          logger: packages.zwave
          level: debug
  - alias: debug lock zwave value events
    mode: parallel
    id: 02f917a5-ec6a-4b19-bade-a614d8d9a7f8
    trigger:
    - platform: event
      event_type: zwave_js_notification
      event_data:
        node_id: 49
    action:
      - service: system_log.write
        data:
          message: >
            at=zwave_js_value_notification
            event={{ trigger.event }}
          logger: packages.zwave
          level: debug