name: auto merge
on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  enable:
    if: |
      ( github.event.action == 'labeled' && github.event.label.name == 'deploy:auto-merge' ) ||
      ( github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'deploy:auto-merge') )
    uses: jnewland/.github/.github/workflows/auto-merge.yaml@cf0a82376c329d9f0be4d5f8fdda94fbd641cf57 # main
    with:
      pullRequestId: ${{ github.event.pull_request.node_id }}
    secrets:
      # https://github.com/settings/personal-access-tokens/15706015
      token: ${{ secrets.UR_BOT_TOKEN }}
