name: auto merge
on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  enable:
    if: |
      ( github.event.action == 'labeled' && github.event.label.name == 'deploy:auto-merge' ) ||
      ( github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'deploy:auto-merge') )
    uses: jnewland/.github/.github/workflows/auto-merge.yaml@main
    with:
      pullRequestId: ${{ github.event.pull_request.node_id }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
