name: auto merge
on:
  pull_request:
    types:
      - labeled
jobs:
  enable:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy:auto-merge')
    steps:
      - uses: alexwilson/enable-github-automerge-action@ba565bd8c8ba820804ae19956abf6bf44966e813
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: SQUASH
