name: cd
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
concurrency:
  group: cd-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name != 'pull_request' }}
jobs:
  validate-config:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Generate fake SSL cert
        run: |
          openssl req -x509 -newkey rsa:2048 -subj '/CN=example.com' -nodes -keyout key.pem -out cert.pem
      - name: Test config
        uses: docker://homeassistant/home-assistant:2026.6.3@sha256:aed891b8f801072302815b4b0fab5adb714182967e9d2e2d4a2be558241c73ad
        with:
          entrypoint: ./script/cibuild

  update-branch:
    if: github.event_name == 'pull_request'
    uses: jnewland/.github/.github/workflows/update-branch.yaml@cf0a82376c329d9f0be4d5f8fdda94fbd641cf57 # main
    with:
      pull_number: ${{ github.event.pull_request.number }}
    secrets:
      token: ${{ secrets.UR_BOT_TOKEN }}

  script-deploy:
    runs-on: ubuntu-latest
    needs:
      - validate-config
      - update-branch
    if: |
      github.event_name == 'push' ||
      ( github.event.action == 'labeled' && github.event.label.name == 'deploy') ||
      ( github.event.action != 'opened' && github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'deploy') )
    environment: production
    concurrency: production
    steps:
      - name: deploy
        run: "true"

  create-deploy-status:
    runs-on: ubuntu-latest
    needs: script-deploy
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha:         context.payload.pull_request.head.sha,
              state:       'success',
              context:     'deploy',
              description: 'PR was deployed with GitHub Actions',
              target_url:  'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            });
