name: cd
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
concurrency:
  group: cd-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name != 'pull_request' }}
jobs:
  changes:
    runs-on: ubuntu-slim
    if: github.event_name == 'pull_request'
    outputs:
      ha-config: ${{ steps.filter.outputs.ha-config }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            ha-config:
              - '**'
              - '!.*/**'
              - '!doc/**'
              - '!**/*.md'
              - '!.*'

  validate-config:
    name: ./script/cibuild
    runs-on: ubuntu-latest
    needs: changes
    if: github.event_name == 'pull_request' && needs.changes.outputs.ha-config == 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Generate fake SSL cert
        run: |
          openssl req -x509 -newkey rsa:2048 -subj '/CN=example.com' -nodes -keyout key.pem -out cert.pem
      - name: Test config
        uses: docker://homeassistant/home-assistant:2026.8.1@sha256:6340a3de3917a9b19368e767310a96dd090f6a19aca8aeadf87fd1145cec9682
        with:
          entrypoint: ./script/cibuild

  update-branch:
    if: github.event_name == 'pull_request'
    uses: jnewland/.github/.github/workflows/update-branch.yaml@9cb74ffde4b52168439870ab437669347f3dcc07 # main
    concurrency: update-branch-main
    with:
      pull_number: ${{ github.event.pull_request.number }}
    secrets:
      token: ${{ secrets.UR_BOT_TOKEN }}

  script-deploy:
    runs-on: ubuntu-slim
    needs:
      - validate-config
      - update-branch
    if: |
      !failure() && !cancelled() &&
      (
        github.event_name == 'push' ||
        ( github.event.action == 'labeled' && github.event.label.name == 'deploy') ||
        ( github.event.action != 'opened' && github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'deploy') )
      )
    environment: production
    concurrency: production
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: github.event_name == 'pull_request'
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha:         context.payload.pull_request.head.sha,
              state:       'success',
              context:     'deploy',
              description: 'PR was deployed with GitHub Actions',
              target_url:  'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            });
