name: manually deployed
on:
  pull_request:
    types:
      - labeled
      - synchronize
jobs:
  attest:
    if: |
      ( github.event.action == 'labeled' && github.event.label.name == 'deploy:manually-deployed' ) ||
      ( github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'deploy:manually-deployed') )
    uses: jnewland/.github/.github/workflows/manually-deployed.yaml@main
    with:
      sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

