name: renovate
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron:  '0 */4 * * *'
jobs:
  renovate:
    uses: urcomputeringpal/.github/.github/workflows/renovate.yaml@main
    with:
      renovate_app_slug: jnewland-renovate
    secrets:
      RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      RENOVATE_APP_PEM: ${{ secrets.RENOVATE_APP_PEM }}
