name: renovate
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron:  '0 */4 * * *'

concurrency:
  group: renovate-${{ github.event.pull_request.number || github.event_name }}
  cancel-in-progress: true

jobs:
  renovate:
    uses: urcomputeringpal/.github/.github/workflows/renovate.yaml@59512c621c99723dfeee313e27b04385185b5f74 # main
    with:
      renovate_app_slug: jnewland-renovate
    secrets:
      RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      RENOVATE_APP_PEM: ${{ secrets.RENOVATE_APP_PEM }}
