name: renovate
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron:  '0 */4 * * *'

concurrency:
  group: renovate-${{ github.event.pull_request.number || github.event_name }}
  cancel-in-progress: true

jobs:
  renovate:
    uses: urcomputeringpal/.github/.github/workflows/renovate.yaml@484b44904881d6ef6f0d38a3401fac405f81cc2f # main
    with:
      renovate_app_slug: jnewland-renovate
    secrets:
      RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      RENOVATE_APP_PEM: ${{ secrets.RENOVATE_APP_PEM }}
