name: sync-components
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
jobs:
  sync-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - run: ./script/sync-components
      - uses: peter-evans/create-pull-request@bd72e1b7922d417764d27d30768117ad7da78a0e # tag=v4
        with:
            token: ${{ secrets.UR_BOT_TOKEN }}
            commit-message: Update custom components
            title: Update custom components
            body: Update custom components
            branch: sync-components
